### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by waldoj** [mapzen/vector-datasource#103]
This repository lacks any licensing terms, or even a copyright statement. Is that intentional—because Mapzen intends to reserve all rights—or is it an oversight? I'm looking to deploy an instance of this, but it's not clear to me if that's permissible.

**Comment by bcamper** [comment]
Oversight! MIT license, done: 

https://github.com/mapzen/vector-datasource/commit/c96dcb542689b0f8c807cadc19629e799f3ae831

:)

**Comment by waldoj** [comment]
:+1: Thank you!

**Comment by bcamper** [comment]
If you have any questions about setting this up, let us know.
