### ISSUE TITLE
Support multilingual name tags

### ISSUE THREAD

**Issue by hanchao** [mapzen/vector-datasource#105]
![multilingual name tags](https://farm9.staticflickr.com/8645/16843583062_c042a6f06e_z_d.jpg)

**Comment by rmarianski** [comment]
Thanks for submitting this. What we'd like to do is include the tags for alternate names (`name:*`) in the response only if those names are different from the `name` tag. This would help keep tile sizes down.

Some initial looking at taginfo [1] suggests that the number of features with alternate names is significantly smaller than the number of features with names. We might run some experiments to verify what the tile size impact will before rolling this out. We'll do some more research [2] into what other tags we might want to include, if any, in this scheme too.

[1] http://taginfo.openstreetmap.org/search?q=name
[2] http://wiki.openstreetmap.org/wiki/Key:name

**Comment by rmarianski** [comment]
We now include `name:*` tags for features where that value is different from the `name` tag.

**Comment by musicformellons** [comment]
@rmarianski How do I get the values? I tried e.g. replacing {name} by {name:ru} or {name_ru} but do not get any values.

**Comment by rmarianski** [comment]
@musicformellons The separator is a `:`

Here's an example:

http://vector.mapzen.com/osm/places/16/32751/21790.json

**Comment by musicformellons** [comment]
In mapbox stylesheet -using mapbox gl js- I replace {name} (which works fine) with {name:fr} and get:
![image](https://cloud.githubusercontent.com/assets/10334123/10022336/91c5e16e-614c-11e5-88cc-6576eb3fa1d2.png)

**Comment by nvkelso** [comment]
Try quoting it?

**Comment by musicformellons** [comment]
Tried various ways of (single and double) quoting, but to no avail:
![image](https://cloud.githubusercontent.com/assets/10334123/10022509/7d807b1e-614d-11e5-998f-7762d0f73f41.png)

**Comment by nvkelso** [comment]
Suggest following up with Mapbox and reporting back here.

**Comment by musicformellons** [comment]
ok, will do.

**Comment by musicformellons** [comment]
See:
https://github.com/mapbox/mapbox-gl-style-spec/issues/362#issuecomment-142677101

Could the : be altered into a _ ?
