### ISSUE TITLE
land_polygons and water_polygons

### ISSUE THREAD

**Issue by frodrigo** [mapzen/vector-datasource#108]
I have done lots of changes in https://github.com/mapzen/vector-datasource/wiki/Mapzen-Vector-Tile-Service. Update, reorder and add some small missing steps. I hope I have not done big mistakes.

Nevertheless, is still missing some data when you follow only this guide. Where are from the land_polygons and water_polygons ? There are not included nor fetched.

**Comment by dimon777** [comment]
In addition to missing these two files, running perform-sql-updates.sh throws this at the end:

psql:apply-planet_osm_polygon.sql:31: ERROR:  column "building:part" does not exist
LINE 1: ... WHERE mz_calculate_is_building_or_part(building, "building:...
                                                             ^
QUERY:  CREATE INDEX planet_osm_polygon_is_building_or_part_index ON planet_osm_polygon(mz_calculate_is_building_or_part(building, "building:part")) WHERE mz_calculate_is_building_or_part(building, "building:part") = TRUE
CONTEXT:  PL/pgSQL function inline_code_block line 14 at SQL statement

**Comment by rmarianski** [comment]
@frodrigo: thanks for the changes to improve the instructions! But, it looks like you removed the loading of this data in one of your edits. Here's the diff in question:

https://github.com/mapzen/vector-datasource/wiki/Mapzen-Vector-Tile-Service/_compare/3fcc6426258989f33a222e507bcaacde3b31f568...fd6b8079f0a203a02b32f50fd7a90df1e1920ef8

The gist file linked to there downloaded the additional data and loaded it. Can you restore those steps in the instructions?

If it's confusing to ask the user to download a gist file, maybe there's another way that we can specify these steps? Maybe we include this script file in the repo itself and ask the user to run it?

**Comment by frodrigo** [comment]
I revert this change. It's was not clear to me that we have to run local script AND the external one. But, yes an integrated script will be better.
