### ISSUE TITLE
/tilejson/tilejson.json.erb

### ISSUE THREAD

**Issue by frodrigo** [mapzen/vector-datasource#109]
I can figure how the URL /tilejson/tilejson.json is served with actual code. Need an additional ruby server or preprocessor to serve this file with the python server part ?

**Comment by rmarianski** [comment]
Yes, we end up serving those statically with a web server. We have a chef recipe that processes this file to generate the static resources, one per format.

**Comment by frodrigo** [comment]
https://github.com/mapzen/vector-datasource/wiki/Mapzen-Vector-Tile-Service/_compare/c0809892b96955d2b7136f7a93e75e1f9be3c361%5E...c0809892b96955d2b7136f7a93e75e1f9be3c361#diff-5450a019e0a3565ccbdedc971a49916cR162

This change tell us look at TileStache for serving static file. But there is no way except for static tiles or one index.

**Comment by rmarianski** [comment]
@dimon777: that was added for #110 right? Should we change the text there to be more about the cross origin config option?
