### ISSUE TITLE
8 minutes to fetch a tile?

### ISSUE THREAD

**Issue by leblowl** [mapzen/vector-datasource#112]
Is it normal for it to take 8 minutes to fetch a tile? I have been trying to get a vector tile server up with tilestache for some time now & it always seems to take forever to fetch/seed tiles. My latest attempt I followed all the instructions in the wiki. 

time curl http://localhost:5000/buildings/16/19293/24641.mvt
real	8m14.025s

It's an empty tile too...I mean all it's doing is making a psql query & then returning the data, no?
Are there any gotchas I'm missing?

Any help would be greatly appreciated!

Thank you, Luke

**Comment by rmarianski** [comment]
8 minutes is unexpectedly high. Usually, the slowest part is the database query. I'd recommend logging slow queries in postgresql to see if anything comes up. If that is indeed the slow part, run an explain analyze on it; maybe it's missing an index.

**Comment by leblowl** [comment]
Ok cool, I'll try to gather some log data & figure out what's taking so long. I am running this on a pretty fast machine with around 24 cores. What sort of time should I expect for rendering a single tile?

**Comment by rmarianski** [comment]
The slowest tiles should be on the order of seconds. When I run your curl example, it kicks back right away for me.

    curl -s http://localhost:8080/buildings/16/19293/24641.mvt > /dev/null  0.01s user 0.00s system 4% cpu 0.183 total

Btw, I do have data in that tile, but I've loaded a nyc extract.

**Comment by leblowl** [comment]
Awesome, I'd like to get there!

**Comment by leblowl** [comment]
Okay, so it turns out it was a connection issue. I threw in a bunch of prints & found it was hanging on a connect call for this query: https://github.com/mapzen/TileStache/blob/integration-1/TileStache/Goodies/VecTiles/server.py#208-209.

So then diggin in a little, I found this: `host – database host address (defaults to UNIX socket if not provided)` - from psycopg2.connect documentation.

mapzen/vector-datasource/tilestache.cfg sets the host to localhost on all the dbinfo sections & causes super slow connections somehow, atleast with my current postgresql config. Not sure. But after removing the host & port entries in my config, it's lightning fast.

`time curl http://localhost:5000/buildings/16/0/6.mvt`
`real	0m0.269s`

**Comment by rmarianski** [comment]
Glad that you were able to resolve it. Thanks for the update.
