### ISSUE TITLE
Include trunk and primary roads at zoom 7+

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#113]
At line 
https://github.com/mapzen/vector-datasource/blob/master/data/functions.sql#L249

We should start including trunk and primary along with motorway right off the bat.

        CASE WHEN highway_val IN ('motorway','trunk', 'primary') THEN 7
             WHEN highway_val IN ('secondary') THEN 10

**Comment by rmarianski** [comment]
https://github.com/mapzen/vector-datasource/commit/4e30909d25aa19674d5ada50755fc847c5166505
