### ISSUE TITLE
Ignore OSM road layer for sort for zooms < 15

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#115]
Adding ramps to the cartography at zooms less than 15 is problematic now because they often z-stack order over highways, adding noise that visually breaking up the highway line. Not displaying ramps is not ideal as there are often highway segments that connect via ramps and it looks like we're missing data when the ramps aren't shown at zooms 12, 13, 14. Ignore the OSM layer information when calculating the feature sort at zooms will allow ramps to sort under highways for these zooms.

We need to pass in the zoom level to mz_calculate_road_sort_key() and only exercise 
https://github.com/mapzen/vector-datasource/blob/master/data/functions.sql#L271
if the zoom >= 15
else do the simple bridge/tunnel & highway type sorting.

Example near: San José, California at 13/37.2554/-121.8593

Currently we don't show ramps, creating a visual gap:

<img width="283" alt="no_ramps" src="https://cloud.githubusercontent.com/assets/853051/8855982/eace67dc-311c-11e5-860d-262a50ac6012.png">

Adding the ramps in fills the gap, but too much visual noise at Blossom Hill Road: 
<img width="270" alt="with_osm_layer_sorting" src="https://cloud.githubusercontent.com/assets/853051/8855983/eae80034-311c-11e5-8780-a9dcf6dac6dc.png">

**Comment by rmarianski** [comment]
That sort key function isn't used any more, and I've made a ticket to address removing it: #116.

Where it happens now is here: https://github.com/mapzen/TileStache/blob/13e62bd0dea4e4d78dce9b28eab3e3a528035110/TileStache/Goodies/VecTiles/transform.py#L221-L279
And then it gets picked up here: https://github.com/mapzen/TileStache/blob/13e62bd0dea4e4d78dce9b28eab3e3a528035110/TileStache/Goodies/VecTiles/sort.py#L65-L66
Although now that I think about it, that logic should just move to the sort function.

Anyway, the zoom currently doesn't get passed into the transforms/sorts, but I'll go ahead and make the change to pass it through to each one.

@nvkelso: do you think that these functions might need to have access to any other state that might affect the calculation? eg the bounding box, or maybe the coordinate being processed?

**Comment by rmarianski** [comment]
We discussed this earlier, and we'll only add zoom. It doesn't seem like anything else would be immediately useful.

Scratch what I said about moving the logic to the sort from the transform. We want to return this value back to the client.

**Comment by rmarianski** [comment]
@nvkelso: this what you had in mind?

https://github.com/mapzen/TileStache/pull/36

**Comment by nvkelso** [comment]
Yes! Can we see this change on dev?

**Comment by rmarianski** [comment]
I've updated dev.

**Comment by nvkelso** [comment]
With the additional change (bringing the bridge/tunnel offset into the zoom block test), LGTM.
