### ISSUE TITLE
Start showing subway entrances at zoom 17

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#117]
Currently they are zoom 18+

**Comment by rmarianski** [comment]
#120 

We also show `amenity IN ('bench', 'waste_basket')` at zoom 18. Can/should that be moved to zoom level 17 too? Or should we leave that the way it is for now.

**Comment by nvkelso** [comment]
Let's leave that street furniture at zoom 18 and keep this just for subway entrances.
