### ISSUE TITLE
Promote major highway links to earlier zoom

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#122]
At zoom 9, 10, and 11 we're missing major highway (motorway) links. Let's close up those gaps by adding the major highway links at the same time we add the major highways.

Looks like this is controlled here:
https://github.com/mapzen/vector-datasource/blob/master/data/functions.sql#L100

             WHEN highway_val IN ('motorway_link', 'trunk_link', 'residential', 'unclassified', 'road') THEN 12

Seems fine for trunk and other links to remain at zoom 12 (that's when the minor roads come in already).

Example around Stockton, California (#10.925/37.8195/-121.4428):

<img width="461" alt="screen shot 2015-08-04 at 12 28 50" src="https://cloud.githubusercontent.com/assets/853051/9070425/71de5c88-3aa4-11e5-8785-b8bae80e69e6.png">

**Comment by rmarianski** [comment]
Yup, that's where it's controlled.

https://github.com/mapzen/vector-datasource/pull/123

**Comment by rmarianski** [comment]
Just merged the branch in.

**Comment by nvkelso** [comment]
Verified in prod.
