### ISSUE TITLE
Add zoo, aerodrome, urban, rural areas to landuse polygons

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#124]
The SF zoo is missing, and the animals there are sad.
tourism:zoo

**Comment by nvkelso** [comment]
And pilots at SFO are rioting. Or was that the London Underground people? Whatever.

**Comment by nvkelso** [comment]
And we're missing Pt Reyes national seashore north of SF, which has these tags
leisure:nature_reserve
landuse:conservation

**Comment by nvkelso** [comment]
Urban areas are in:
place:locality

**Comment by rmarianski** [comment]
> The SF zoo is missing, and the animals there are sad.
> tourism:zoo

Taginfo says that tourism=zoo exists for some points as well. Should we add this to the pois layer? If so, maybe at z16?

> And we're missing Pt Reyes national seashore north of SF, which has these tags
> leisure:nature_reserve
> landuse:conservation

We are already pulling in `leisure=nature_reserve`. I did some digging, and it looks like it does appear in the tiles. But I'm not sure why it's not rendering when I view it in tangram (I was expecting green).
http://vector.mapzen.com/osm/all/12/649/1579.json

As an aside, we're not querying for `landuse=conservation`, but that can be added.

> Urban areas are in:
> place:locality

Looks like there are lots of nodes tagged like this. Should it be added to the pois layer too, z16?

**Comment by bcamper** [comment]
It looks like a style problem, not a data one -- looks like the landuse layer in the demo is only showing specific `kind` values, and that is not one of them. I think this was @meetar's attempt to cut out some of the notorious New Jersey "farm" areas, but perhaps went too far. Easy to change: https://github.com/tangrams/tangram/blob/master/demos/scene.yaml#L195

(side note, that layer is also requiring features to have a name, but that's overly restrictive since that's just a polygon layer, I can fix that)

**Comment by rmarianski** [comment]
That explains it, thanks @bcamper! My vote would be to keep the name requirement for the `landuse_labels` layer, but drop it for `landuse`.

**Comment by bcamper** [comment]
Name is required for `landuse_labels` at the query level (can't label
something without a name :), but not for the actual `landuse` polygons
(which you could also label using some other data field if you wanted).

**Comment by souperneon** [comment]
@nvkelso love that you are looking out for the pilots. I was trying to make a map of airports recently and the polygon data was not available so I started tracing them out and it's a lengthy process and not that accurate. Does the aeroway:aerodrome return polygons or points?
Thanks @meetar :)

**Comment by rmarianski** [comment]
> Does the aeroway:aerodrome return polygons or points?

@souperneon both [1]. Currently the pr has things set up such that the polygon areas will appear in the `landuse` layer, and the points in the `pois` layer.

[1] http://wiki.openstreetmap.org/wiki/Tag:aeroway%3Daerodrome

**Comment by nvkelso** [comment]
@rmarianski You're right, Point Reyes was hiding in plain site as landuse:conservation only. Updated the original commit above.

**Comment by nvkelso** [comment]
@rmarianski For urban areas, reviewing https://taginfo.openstreetmap.org/keys/residential#values it looks like landuse=urban and landuse=rural are more likely candidates. These should just be landuse polygons without poi or landuse_labels (if they have names, we should probably ignore them).

**Comment by nvkelso** [comment]
@rmarianski For zoos, let's set the default min_zoom to 13 (not z16), yes for also include the labels. Is it better to put it into landuse_labels than POI?

**Comment by nvkelso** [comment]
@rmarianski For the landuse=urban and landuse=rural, I suspect our grouping of several OSM keys into the same "kind" bucket results in odd stuff happening where a less interesting key's value overwrites the more interesting landuse key's value. For instance, I'm seeing a bunch of "residential" values in the returned landuse tiles, and those are usually a refinement of urban/rural.

**Comment by rmarianski** [comment]
I updated the pr (#125):

* removed `place=locality`
* add `landuse=urban` and `landuse=rural` to landuse layer
* add `tourism=zoo` to pois layer at z13

Wrt the `kind` collisions, we can always return back the `landuse` value in addition to providing a `kind`. I think we've done something like that for the roads layer already, where just the `kind` might not have been able to provide sufficient information.

**Comment by nvkelso** [comment]
PR updates look good.

Yes, let's try returning back also the explicate landuse value in addition to the kind object. We might also need to do that for boundaries, I'll make a new issue for that.

**Comment by rmarianski** [comment]
Is it ok for me to merge in the pull request as is, and create a new issue for adding in the landuse value in the response?

**Comment by nvkelso** [comment]
Yes.

**Comment by rmarianski** [comment]
Created ticket to include landuse tag: #132
