### ISSUE TITLE
Suppress parking and bus_stop POIs until zoom 17

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#126]
Parking comes in too early at z15 now, bus_stop too early at z16 now.

Potentially I can see including bus_stop earlier for TRANSIT layer only, but not for a general purpose reference map.

**Comment by nvkelso** [comment]
<img width="872" alt="screen shot 2015-08-11 at 12 22 27" src="https://cloud.githubusercontent.com/assets/853051/9207685/e0014b38-4023-11e5-8e93-1362379bc66b.png">

**Comment by rmarianski** [comment]
I also moved highway=bus_stop from z16 -> z17. Let me know if that was in error.

**Comment by nvkelso** [comment]
LGTM. Looks like most bus_stop are in highway, good catch.
