### ISSUE TITLE
Natural Earth data looks over generalized

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#130]
We're using Natural Earth from zooms 0-8. The source data is already generalized for display at that zoom, but it looks like we're applying additional generalization on top of that.

**Comment by rmarianski** [comment]
We do introduce some osm data at earlier levels:

* boundaries at z8
* transit at z6

I assume that we should continue to apply simplification for these layers, and only suppress it for Natural Earth data.

**Comment by nvkelso** [comment]
Yes.

**Comment by rmarianski** [comment]
@zerebubuth mind reviewing these?

**Comment by nvkelso** [comment]
Looking better!

With change, zoom 4 at USA:
![after](https://cloud.githubusercontent.com/assets/853051/9667762/92da794e-5232-11e5-9cad-baf6bb18965d.png)

Before, without change:
![before](https://cloud.githubusercontent.com/assets/853051/9667767/9946e6be-5232-11e5-979f-4a6abdb9abfb.png)

**Comment by rmarianski** [comment]
:shipit:?
