### ISSUE TITLE
How are the ne_XXXm datasets created?

### ISSUE THREAD

**Issue by leblowl** [mapzen/vector-datasource#146]
I'm in the process of building my own tile service & am trying to get a better picture of the underlying data. So yea, how are these datasets created & then updated? Thank you!

**Comment by leblowl** [comment]
I think I may have answered my own question as to their origins. Is this correct: http://www.naturalearthdata.com/downloads/10m-cultural-vectors/roads/ ?

**Comment by rmarianski** [comment]
Yes, exactly right. Those all come from the natural earth datasets.

We do some light processing on them first though. The shape files from natural earth are in the latlong projection (epsg:4326) and we reproject it into web mercator (epsg:3857). These are what get checked into the repo. We use ogr to do it:

    ogr2ogr -f "ESRI Shapefile" -s_srs EPSG:4326 -t_srs EPSG:3857 <destination.shp> <source.shp>

And if there are encoding issues:

    ogr2ogr -f "ESRI Shapefile" -s_srs EPSG:4326 -t_srs EPSG:3857 -lco ENCODING=UTF-8 <destination.shp> <source.shp>

Additionally, if the dataset that we include has very few features in them, we tile them up first, and then use that. This is to improve query performance. The script that we use for that can be found [here](https://github.com/mapzen/vector-datasource/blob/0622718ee5de6cdb5d9e4e577b153627f6585f0e/data/split_to_tiles.sql).

**Comment by leblowl** [comment]
Awesome, thank you!
