### ISSUE TITLE
Source neighborhoods from WOF / Quattroshapes

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#147]
The OSM neighborhoods are... still a work in progress and weird shit appears in NYC and other cities.

**Comment by bcamper** [comment]
+++++++++++++++++++++++++

**Comment by nvkelso** [comment]
Seems like a struck a nerve (in a good way)!

**Comment by mjcunningham** [comment]
:+1:

**Comment by nvkelso** [comment]
source: whosonfirst

**Comment by rmarianski** [comment]
@nvkelso will we want a layer with just neighborhood name and label position? Or will we need the actual geometries of the neighborhoods?

**Comment by nvkelso** [comment]
For this issue, we put WOF neighborhoods into 'places' layer as points alone, in addition to the OSM points, and source them to whosonfirst.

**Comment by rmarianski** [comment]
At what zoom do we want to start including the WOF neighborhoods?

**Comment by nvkelso** [comment]
For now, the same zoom as for OSM neighborhoods: zoom 12+. 

Since WOF includes area and relative importance, we might later throttle that so some (smaller, less important) are visible only at later zooms. But that's later optimization.

**Comment by nvkelso** [comment]
Looking good. Turns out some neighborhood like things are hiding in WOF Macrohoods – I've added that work in https://github.com/mapzen/vector-datasource/issues/337.

**Comment by nvkelso** [comment]
@bcamper and @mjcunningham and @sensescape Please review this in `dev`. You'll need to add `source: whosonfirst` to any neighborhood style layer to filter out the OSM features.

**Comment by rmarianski** [comment]
It seems like there are only 2 rows for [macrohoods](https://github.com/whosonfirst/whosonfirst-data/blob/master/meta/wof-macrohood-latest.csv). Am I looking at the wrong place?

**Comment by nvkelso** [comment]
That’s the right thing. It needs to be data gardened.

On Mon, Oct 26, 2015 at 10:12 AM, Robert Marianski <notifications@github.com

**Comment by nvkelso** [comment]
Browsing around, comparing and contrasting it's clear that sometimes WOF is better, sometimes OSM is better. There are some obvious funk in WOF that is different than the obvious OSM funk. The question is do we wait for the obvious funk to resolve itself before enabling this or push it out as a way to force more WOF edits.

**Comment by nvkelso** [comment]
Let's pull the plug on OSM sourced neighborhoods entirely this release and cut over completely to WOF sourced neighborhoods. New issue: https://github.com/mapzen/vector-datasource/issues/359.

**Comment by nvkelso** [comment]
Tracking adding `macrohoods` with https://github.com/mapzen/vector-datasource/issues/337 and adding `importance` with https://github.com/mapzen/vector-datasource/issues/338.
