### ISSUE TITLE
Include national parks and other significant OSM landuse earlier

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#149]
- [x] National Parks at zoom 4
- [x] National Forest like things at zoom 5+
- [x] Keep Natural Earth urban areas as zoom 8

Punting this one:
- [x] ~~Urban / Rural at zoom 6+~~

**Comment by rmarianski** [comment]
> National Parks at zoom 4

We include the 50m urban areas and zoom 4. Is it ok to mix the 10m parks dataset with this one?

> National Forest like things at zoom 5+

Is there a dataset that you had in mind for this one? I browsed through ne but didn't find any that seemed to match.

> Urban / Rural at zoom 6+

We're including urban areas starting at zoom 6. Is there an equivalent dataset for rural areas? I couldn't find one in ne.

**Comment by nvkelso** [comment]
> We include the 50m urban areas and zoom 4. Is it ok to mix the 10m parks dataset with this one?

Yes. Let's preview this on dev and see how it looks. This will only add National Parks for the USA at first, but that may be enough for first cut. We'd need to do a non-trivial amount of work to pull out just National Parks from OSM for the same purpose world wide, which is beyond the scope of this issue.

> Is there a dataset that you had in mind for this one? I browsed through ne but didn't find any that seemed to match.

This should come from OSM, but make sure it's generalized.

> We're including urban areas starting at zoom 6. Is there an equivalent dataset for rural areas? I couldn't find one in ne.

For OSM, let's investigate only including Urban polygons earlier and make sure they are generalized. (Urban and rural are all tied up in Urban in Natural Earth so the distinction isn't important.)

**Comment by zerebubuth** [comment]
> For OSM, let's investigate only including Urban polygons earlier and make sure they are generalized. 

OSM doesn't really have the concept of "urban polygons". We could try using various values of landuse polygons, but I'm not sure the quality will be any good. Most landuse polygons in OSM are pretty small and their coverage is patchy. See below the area around NYC:

![landuse_nyc](https://cloud.githubusercontent.com/assets/271360/9998046/5a967016-6087-11e5-9a80-7781b8364325.png)

The red/purple/blue are landuse values associated with urban areas (e.g: residential, commercial, industrial) and the green-ish ones are associated with rural areas (e.g: forest, conservation, farm). The brown are neither. As you can see, the coverage is patchy, and many landuse polygons have voids between them that we would need to fill in, which will make for expensive queries or complex preprocessing.

I reckon it might be better to just stick with Natural Earth urban polygons - @nvkelso, what do you think?

**Comment by nvkelso** [comment]
Yeah, I agree about keeping the Natural Earth urban areas instead of switching to OSM early.

Talking with Geraldine more last week about the urban areas, we'd like to keep the Natural Earth data thru zoom 8 (transitioning to OSM at zoom 9+). See that in action in the Eraser Map cartography [here](http://tangrams.github.io/eraser-map/#8/37.804/-122.271). I've updated the issue to reflect no change (well, we need to keep the NE data at zoom 8, not switch to OSM). 

The urban areas in OSM seem to be much better in Europe than the USA. We use it as a blush treatment in the cartography – if it's in the data then good, else it's not a huge eye sore.

**Comment by zerebubuth** [comment]
Should we roll back most of #225, then? If we now don't want OSM at zoom 8?

**Comment by nvkelso** [comment]
Yeah, mix and match (sorry). We still want the OSM roads earlier (in https://github.com/mapzen/vector-datasource/pull/225) and we still want the green areas much earlier (forest, parks, etc in PR https://github.com/mapzen/vector-datasource/issues/227 in this issue). And Natural Earth urban should stick around thru zoom 8.

It looks like the changes to landuse and landuse-labels in 82507a5 and 5f112c5 have a blanket Natural Earth to OSM transition, where we need something like a cross-fade where most features switch over, but the Natural Earth urban areas are preferered over the OSM urban areas until zoom 9.

**Comment by nvkelso** [comment]
This looks good, let's take it to prod.

The landuse-labels also need to update, that's covered in #248 (and shouldn't block this going out).
