### ISSUE TITLE
clockwise Polygon order with quantized coordinates 

### ISSUE THREAD

**Issue by gronke** [mapzen/vector-datasource#151]
I am using `d3.geo.path()` to render data from this datasource. At certain zoom levels some items are rendered improperly, because d3 expects the Polygon data to be ordered clockwise. 

The example below shows a response containing a quantized Polygon that is correct (in my understanding of clockwise ordered coordinates), but looking at the static longitude *50.87531* it could be rendered as LineString rather than a Polygon.

My suggestion is to remove this kind of 1-dimensional polygons from the GeoJSON response, for the reason that it is not visible at the specific zoom/quantization level.

### Example
http://vector.mapzen.com/osm/water/13/4253/2746.json
```json
{
  "type": "FeatureCollection",
  "features": [
    ...
    {
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              6.91268,
              50.87531
            ],
            [
              6.91269,
              50.87531
            ],
            [
              6.91270,
              50.87531
            ],
            [
              6.91268,
              50.87531
            ]
          ]
        ]
      },
      "type": "Feature",
      "properties": {
        "source": "openstreetmap.org",
        "kind": "water",
        "id": 130165730,
        "area": 9724
      }
    }
   ...
  ]
}
```

**Comment by rmarianski** [comment]
To optimize file sizes, we do trim off some of the precision on geometries based on the zoom level. With no trimming, the geometry is indeed a valid polygon:

```json
[
    6.9126808257700585,
    50.875311142200594
],
[
    6.912687297762034,
    50.87531361348527
],
[
    6.912697182431247,
    50.875311142200594
],
[
    6.9126808257700585,
    50.875311142200594
]
```

Using tangram, I dug into it a little bit, and what it looks like is going on is that the very end of a water polygon is getting cut on a tile boundary. I only end up seeing the polygon at zoom level 15 though, which might be related to this comment: https://github.com/mapzen/vector-datasource/issues/136#issuecomment-137519852

We already do use area filters, but they get applied for the entire geometry's area, not the resulting clipped one. @nvkelso, if those filters are indeed to filter out items that are smaller than a pixel, we might want to also apply that filter on the clipped geometry, or maybe just a very small one. In this case, using the full precision on the coordinates, or at least what comes out of the json without any trimming, the area on the resulting geometry is: 2.0210983054318682e-11. So even if we used a very small sanity check filter, it would catch these cases.

Also I think that this approach using area as a filter would be much more robust than trying to figure out what the precision would need to be to produce a valid geometry.

**Comment by nvkelso** [comment]
What's the cost of adding the additional sanity check (per tile'd chunk of the feature, instead of just the entire feature's area)?

**Comment by rmarianski** [comment]
Doesn't look like computing area is an intense process. This looks like it, based on me poking around:

https://github.com/libgeos/libgeos/blob/cf89e5c3669ca4b650a8eb51ed34904de31fe62e/src/algorithm/CGAlgorithms.cpp#L296-L319

I'd assume that it doesn't have a huge impact, but I can measure some tiles to see.

**Comment by gronke** [comment]
This is what helped me getting around the rendering issue in the client:

```javascript
features = features
.filter(function(feature) {
  if(feature.geometry.type === 'Polygon') {
    return !isFlatPolygon(feature.geometry.coordinates[0]);
  }
  return true;
});

function isFlatPolygon(polygon) {
  var flatX = true, flatY = true;
  polygon.reduce(function(a, b) {
    if(a[0] != b[0]) {
      flatX = false;
    }
    if(a[1] != b[1]) {
      flatY = false;
    }
    return b;
  });
  return flatX || flatY;
}
```

The second thing I had to apply to ensure the data is in clockwise winding order:
https://github.com/mbostock/topojson/blob/master/lib/topojson/clockwise.js

**Comment by zerebubuth** [comment]
Looks pretty good! Do we want to have the cut-off configurable so that we can say for particular layers it might be 1.0 sq px, but for others we might want 0.25 sq px or similar?

**Comment by rmarianski** [comment]
Hhmm, would there be a reason to include a feature if it's smaller than a pixel?

**Comment by zerebubuth** [comment]
I reckon if something's 0.9 sq px then it's pretty important, especially if you start zooming in to zoom n+0.99, then it'll be effectively 3.6 sq px. On a retina display, that might be 14.4 actual sq px.

I dunno - I just foresee us having to monkey around with this value to get it right, and figured that would be better done in the config.

**Comment by nvkelso** [comment]
+1 for configurable threshold.

**Comment by rmarianski** [comment]
Put configurability in a separate issue:

https://github.com/mapzen/vector-datasource/issues/202
