### ISSUE TITLE
US:I is tagged as `kind: minor_road`

### ISSUE THREAD

**Issue by meetar** [mapzen/vector-datasource#153]
Everything tagged as "network: US:I" also seems to be tagged as "kind: minor_road" – Should probably be `highway`, no?

**Comment by nvkelso** [comment]
Let's remove the duplicate Interstate features and instead apply the network and ref from the relation directly onto the original way feature.

(Only the duplicate features show this bug.)

**Comment by nvkelso** [comment]
Related to #121.

**Comment by nvkelso** [comment]
Example (search for 80, as in I-80): 
http://vector.mapzen.com/osm/all/15/5251/12659.topojson?api_key=vector-tiles-HqUVidw

You'll see two segments, twice. Once as highway, once as minor_road.

**Comment by rmarianski** [comment]
Yea, the relation doesn't have the appropriate `kind` set. We could update the road kind logic, but this should implicitly get fixed when #121 does.

**Comment by nvkelso** [comment]
Fixed in #170.
