### ISSUE TITLE
Explicit landuse sort order

### ISSUE THREAD

**Issue by zerebubuth** [mapzen/vector-datasource#154]
Add a server-generated parameter for sort order based on the existing sort keys in the stylesheet for landuse and water. This will help simplify the stylesheet and can be used to decide which landuse polygon "wins" for the purposes of projecting its attributes onto intercut features (see #136).

**Comment by rmarianski** [comment]
:+1: Feel free to merge in.

I put in a minor comment https://github.com/mapzen/TileStache/pull/39#discussion-diff-38975673

**Comment by zerebubuth** [comment]
Thanks! Merged.
