### ISSUE TITLE
Some zoom levels look oversimplified

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#157]
Migrating over from Trello...

From Brett:

Certain geometries look a little bit oversimplified. And with retina displays, we don't have a good option if we have already pre-simplified to a particular zoom. We might want to be a little bit more conservative with the simplifications.

**Comment by nvkelso** [comment]
From Rob in Trello:

One possible approach could be to use a more aggressively simplified version of the geometries for query purposes in the where clause, and use a less simplified version for use for rendering.

Maybe this will also have an effect on the tile tearing?

**Comment by rmarianski** [comment]
I don't think my earlier comments are relevant any more. It was at a time when we were querying different geometry columns that were pre-simplified a little for optimization purposes to speed up the intersects function, but that's been moved to python now.

The tile seam in that link is resolved now too, at least to my eye :)

**Comment by nvkelso** [comment]
@bcamper Do you think this is relevant anymore? We already have an issue to use VW simplification instead of DP, I think that would make the line fidelity per zoom look better. But I'm not seeing any specific examples that look over generalized. Propose closing this "configuration changed".

**Comment by bcamper** [comment]
Yes I think this is covered by other issues, and we'll be re-evaluating anyway once those are done.
