### ISSUE TITLE
Land polygon outline in the middle of the Hudson

### ISSUE THREAD

**Issue by souperneon** [mapzen/vector-datasource#175]
http://tangrams.github.io/multiverse/tangram.html?styles/blue-gray6#14.24875/40.8807/-73.9352

<img width="784" alt="screen shot 2015-09-08 at 11 25 11 am" src="https://cloud.githubusercontent.com/assets/6125224/9739197/ba708e7e-561c-11e5-8d80-404978a0740b.png">

**Comment by zerebubuth** [comment]
Is this the same as #140?

Certainly looks like a similar fix would be needed: turning off some parts of the polygon boundary stroke.

**Comment by souperneon** [comment]
Definitely related. @nvkelso I'm not sure if we add the same fix in the stylesheet?

**Comment by bcamper** [comment]
Yes I believe #140 should fix it. The issue is drawing an outline around the water polygons, as @zerebubuth says. Once we have an explicit coastline layer, we can just move that stroke there.

**Comment by nvkelso** [comment]
Yes, dup of https://github.com/mapzen/vector-datasource/issues/140.
