### ISSUE TITLE
Add addr_housenumber points

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#181]
We're only capturing a minority of addresses from OSM when they are attached to a building shape. Most OSM addresses are separate points with the addr_housenumber tag. These should probably go into the buildings layer.

**Comment by nvkelso** [comment]
@bcamper will including addr_housenumber points in the building layer cause any downstream problems in Tangram?

**Comment by bcamper** [comment]
Nope! Just makes the tiles a bit heavier, but better to have the data IMO.

**Comment by zerebubuth** [comment]
Do we want to try to interpolate house number lines as well?

**Comment by nvkelso** [comment]
I tend to think no, but tell me more about what the result would look like. Are the features generated guaranteed to match ground truth in terms of position & count (would there be more of them generated than there are in fact)?

**Comment by zerebubuth** [comment]
I don't think the individual addr:housenumber points are guaranteed to match ground truth in terms of position and count - there will be plenty which are out of position or missing, especially if they were imported.

As for interpolation lines; it depends where they came from. The ones I've entered have always been "full" and probably accurate enough (assuming buildings in a terrace are equal width, which they approximately are). Ones which have come in as block interpolations (e.g: from TIGER) will probably run the full X00-X99 regardless of how many houses are there.

We have a few options:

1. Don't include any interpolated stuff.
2. Include the interpolation lines.
3. Break the interpolation lines into points.
4. Break the interpolation lines into points, but mark them as having been interpolated.

I agree that the TIGER-style block interpolations are pretty useless from a display standpoint, but would think that they might come in handy for other users of the data, particularly delivery-oriented apps.

**Comment by nvkelso** [comment]
Yeah, let's skip the line interpolation for now. Side note: Pelias doesn't do any line interpolation for addresses now, so we're not the odd kid out here. I fee like routing to an interpolated address is fine, but I'm nervous about showing them on a map if they are likely to not be in the right spot.

The PR was merged. Closing this one out.
