### ISSUE TITLE
Add ferry lines to roads layer

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#187]
Routes that go from land to water to land again show gaps in the map today for the ferry part, let's fill those in.

Read up:
https://wiki.openstreetmap.org/wiki/Tag:route%3Dferry

Sounds like it has the same general structure as roads with the highway tag but are route=ferry for the primary distinction. 

Let's brainstorm how we want these kinds to end up in tiles (we don't want them to default render as roads).

**Comment by zerebubuth** [comment]
Perhaps these should end up in the transit layer, rather than the roads layer? They'd end up with `kind=ferry` by default, it looks like.

**Comment by nvkelso** [comment]
We [pack](https://github.com/mapzen/vector-datasource/blob/master/data/functions.sql#L228) `railway` in the roads layer now and a good number of ferries are more part of the road network than the public transit network, so we already have the "not road things drawing sometimes as roads" in a default styling problem. 

Reading up on the wiki, it looks like ferry=* should be included (at least for a minimum set of popular values, like we currently do for roads), and with the high-road logic extended to set `kind=ferry`.

Default OSM styling shows these coming in very early (8 or 9 I remember)? Should we do that or throttle it based on the ferry=* value (like we do for roads)?

**Comment by zerebubuth** [comment]
After mapzen/TileStache#64 and #281, it looks like this:

## Zoom 9
![187-sf-z9](https://cloud.githubusercontent.com/assets/271360/10234815/4e057648-688f-11e5-872d-e855904a0d9f.png)

## Zoom 10
![187-sf-z10](https://cloud.githubusercontent.com/assets/271360/10234819/509bd8b6-688f-11e5-925f-42e2a4000b9d.png)

## Zoom 11
![187-sf-z11](https://cloud.githubusercontent.com/assets/271360/10234821/53014104-688f-11e5-9775-84f8352ff7d7.png)

**Comment by zerebubuth** [comment]
@nvkelso could you review, please?

**Comment by nvkelso** [comment]
I dig it :)

Considerations:

1. I mentioned in the PR but we probably need a way to show select ferries
at zoom 8 (when OSM data starts coming in) as there are ferries from
Natural Earth rendered that would otherwise hide at 8, then show again at
9. See further discussion there.

2. San Francisco has a decent amount of ferries, but New York has way more.
And Athens (and Greece in general) have even more. The length buckets
should be tested in those places too.

**Comment by zerebubuth** [comment]
1. Yup, updated the PR to pull in ferries at zoom 8, and generally show more to correspond to what NE is pulling in.

## Zoom 8

![187-sf-z8](https://cloud.githubusercontent.com/assets/271360/10246484/b4fe92ce-6909-11e5-8155-5caff5799604.png)

## Zoom 9

![187-sf-z9-2](https://cloud.githubusercontent.com/assets/271360/10246485/b6bcefac-6909-11e5-8b3a-c1d8a627cd29.png)

## Zoom 10

![187-sf-z10-2](https://cloud.githubusercontent.com/assets/271360/10246486/b89d89d0-6909-11e5-9736-542c3ed1f435.png)

2. Yup, we should push this to dev so that we can test for the whole world.

**Comment by nvkelso** [comment]
@rmarianski Was this taken to `dev`? I'm not seeing ferry lines in SF or NYC tiles, for instance NYC:

* http://vector.dev.mapzen.com/osm/all/14/4823/6160.topojson?api_key=vector-tiles-HqUVidw

**Comment by rmarianski** [comment]
I took master, but it looks like this pr hasn't been merged yet: https://github.com/mapzen/vector-datasource/pull/281

**Comment by nvkelso** [comment]
I've merged this one now (the TileStache change was already merged).

**Comment by nvkelso** [comment]
I see these in NYC and SF now, thanks!
