### ISSUE TITLE
Add aerialway line features

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#189]
We're missing gondolas and other aerial cable cars in ski areas specifically and generally (they're using for public transport in some mountainous urban areas).

Background reading:
https://wiki.openstreetmap.org/wiki/Aerialway

Seems like the `roads` layer makes most sense for these features, but we'd need to think about how to create a hierarchy similar to the road highway, major, minor classes and how to distinguish it from road roads (similar problems for adding ferries).

These are the most common types:

- [ ] chair_lift
- [ ] drag_lift
- [ ] platter
- [ ] t-bar
- [ ] goods - this one is weird because it's not for people to travel on
- [ ] magic_carpet
- [ ] gondola
- [ ] cable_car
- [ ] rope_tow
- [ ] yes
- [ ] zip_line
- [ ] j-bar
- [ ] unknown
- [ ] mixed_lift
- [ ] canopy

This one has been deprecated and should be recast as a `zip_line `:

- [ ] cableway

**Comment by zerebubuth** [comment]
After mapzen/TileStache#82 and #341, I get:

## Zoom 14

![winter_park_z14](https://cloud.githubusercontent.com/assets/271360/10742206/dc9541c0-7c23-11e5-9d45-bb2347ff7517.jpg)

## Zoom 16

![winter_park_z16](https://cloud.githubusercontent.com/assets/271360/10742210/e2990ea8-7c23-11e5-983e-d2ad33017d62.jpg)

**Comment by nvkelso** [comment]
Most excellent :+1:
