### ISSUE TITLE
add underground tag to buildings

### ISSUE THREAD

**Issue by meetar** [mapzen/vector-datasource#194]
There are a couple of BART stations which are underground: https://www.openstreetmap.org/way/155378773
https://www.openstreetmap.org/way/160331904

But the tiles have them as just vanilla buildings at street level: 
http://tangrams.github.io/explorer/#17.5/37.7896/-122.4013/name/Montgomery%20Stat

https://trello-attachments.s3.amazonaws.com/55f1d2933cfa613ec481fe6c/978x816/e9e8d46c82c10fdd49e3d4af117272b5/Screen_Shot_2015-09-10_at_2.55.37_PM.png

**Comment by nvkelso** [comment]
Let's think about moving underground buildings that are transit into the transit layer (they don't have anything to extrude and are more or less just flat polygons). Regular (above ground) buildings tagged with transit should stay in the building layer (but express they are transit related in the attributes).

See also: 

* http://wiki.openstreetmap.org/wiki/Key:location?uselang=en-US

* http://wiki.openstreetmap.org/wiki/Key:layer?uselang=en-US

**Comment by nvkelso** [comment]
We'll add level and location to the buildings, but I suspect the larger issue is that the BART platforms should really be marked `railway:platform` and be included in the `transit` layer.

See how to do it right in Moscow:
http://www.openstreetmap.org/#map=17/55.75196/37.60592

**Comment by nvkelso** [comment]
`location` is coming thru, but doesn't look like `layer` is. @zerebubuth can you investigate why?

Here's Powell St in SF: 
https://www.openstreetmap.org/edit?#map=18/37.78498/-122.40639

**Before:**
http://vector.mapzen.com/osm/all/18/41938/101314.topojson?api_key=vector-tiles-HqUVidw

<img width="687" alt="screen shot 2015-10-01 at 18 11 53" src="https://cloud.githubusercontent.com/assets/853051/10237575/305c4ad0-6868-11e5-9144-7e6ef95f710e.png">


**After:**
http://vector.dev.mapzen.com/osm/all/18/41938/101314.topojson?api_key=vector-tiles-HqUVidw

<img width="651" alt="screen shot 2015-10-01 at 18 11 32" src="https://cloud.githubusercontent.com/assets/853051/10237578/366d4da2-6868-11e5-86d5-350c67773f6e.png">

**Comment by zerebubuth** [comment]
> `location` is coming thru, but doesn't look like `layer` is.

Osm2pgsql makes explicit columns from tags in its style file, and layer is one of those. A side-effect is that it removes it from the `tags` hstore, so that query was coming back as `NULL` always. Should be fixed as part of #285.

**Comment by nvkelso** [comment]
Verified.
