### ISSUE TITLE
Landuse should exclude buildings source

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#201]
In working on https://github.com/mapzen/vector-datasource/issues/186 we've discovered we're duplicating buildings with certain tags into the landuse layer as polygons. We shouldn't be doing that (the building should only appear in the building layer as a building feature, a flattened version of it shouldn't be copied to the landuse layers).

**Comment by nvkelso** [comment]
I suspect this is the root cause of too many university icons showing up in clusters where OSM has `building=yes` and `amenity=university`, but we drop `building=yes` and end up with `amenity=university` and an area, which confuses styling down stream.

#16/37.7243/-122.4790

<img width="633" alt="screen shot 2015-10-01 at 21 44 38" src="https://cloud.githubusercontent.com/assets/853051/10239649/a8cc1c4e-6885-11e5-8ecc-638ff2422d2d.png">

**Comment by nvkelso** [comment]
It's also a little weird to see `kind:university` and `landuse_kind:university`! At least for building labels, maybe for others, does it make sense to drop the feature's `kind` property if it's the same as the `landuse_kind`? 

See:

* http://vector.dev.mapzen.com/osm/all/16/10471/25342.topojson?api_key=vector-tiles-HqUVidw

**Comment by zerebubuth** [comment]
There are a few things we could try for this:

1. Dropping the feature's `kind` when it `==landuse_kind`, as you suggest.
2. Don't include buildings in landuse (i.e: if `building=*` then it's a building, not a landuse polygon).
3. Apply some de-duping filters, e.g: #267.

The first option seems pretty quick, so let's start with that.

**Comment by zerebubuth** [comment]
It sounds like we need to separate out three different things; landuse, building and POI status. Any OSM feature could have a mixture of all three. I've tried to collect together a set of reasonably plausible examples below, along with what we might want them to be exported as in the output.

1. [a building with no name](http://www.openstreetmap.org/way/243511759) has `building=yes`. This should result in a building polygon in the buildings layer with `kind=building`?
2. [a building with a name](http://www.openstreetmap.org/way/69707522) has `building=yes` and `name=*`. This should result in a building polygon in the buildings layer with `kind=building` and a label in the buildings layer with `kind=building`?
3. [a building with an address](http://www.openstreetmap.org/way/69707523) has `building=yes`, `addr:housenumber=*`. This should result in a building polygon in the buildings layer with `kind=building` and an address point in the buildings layer with `kind=addr` (or `kind=address`?).
4. a building with both `name=*` and `addr:housenumber=*` would result in both an address point and a label being generated?
5. [a building with hotel tags](http://www.openstreetmap.org/way/33808671) has `building=yes`, `tourism=hotel` and `name=*`. This should result in building polygon in the buildings layer with `kind=building` and a point in the POIs layer with `kind=hotel` and `name=*`. We don't consider the name to apply to the building when there are POI tags. But address tags would still generate an address point in the buildings layer.
6. [a building with theatre tags](http://www.openstreetmap.org/way/32866034) has `building=yes`, `amenity=theatre` and `name=*`. This should result in building polygon in the buildings layer with `kind=building` and a point in the POIs layer with `kind=theatre` and `name=*`, just like the previous case.
7. [a building with landuse and restaurant tags](http://www.openstreetmap.org/way/157809668) has `building=yes`, `landuse=retail`, `amenity=restaurant` and `name=*`. This should result in a building polygon in the buildings layer with `kind=building` and a point in the POIs layer with `kind=restaurant` and `name=*`. The landuse value for this building is ignored, although it may get `landuse_kind` from being enclosed in [another landuse polygon](http://www.openstreetmap.org/way/58169222) anyway.
8. [a building with landuse and theatre tags](http://www.openstreetmap.org/way/25759141) has `building=yes`, `leisure=stadium` and `amenity=theatre`. What should this get?
9. [a "building" with leisure tags](http://www.openstreetmap.org/way/37054313) has `building=yes` and `leisure=park`. It should get a polygon in the buildings table, and a label point in the landuse layer, but no polygon in the landuse layer?
10. [a park with a library in it](http://www.openstreetmap.org/way/231989828) has `amenity=library`, `leisure=park` and `name=*`. It should get a polygon in the landuse layer with `kind=park` but no label, and a label in the POIs layer with `kind=library` and `name=*`.

Does that all sound about right? Are there any other cases we should be considering? Particularly any which would result in a polygon being put into more than one layer?

**Comment by nvkelso** [comment]
> 1. a building with no name has building=yes. This should result in a building polygon in the buildings layer with kind=building?

It would, but we strip that out in post processing so there is effectively no `kind` property on the feature by the time it makes it to tiles as a polygon (unless an amenity & etc value is additionally set). No label_position should be generated for this feature. I think there is one now, Rob was going to change that in the generic logic (to only generate `label_position` if name, except if `pitch` or `grass` with `sport` tag).

**Comment by nvkelso** [comment]
> 2. a building with a name has building=yes and name=*. This should result in a building polygon in the buildings layer with kind=building and a label in the buildings layer with kind=building?

See comment in (1) Above re skipping `building=yes` in `kind` calculation. I understand why we do it, but it's also a little weird (to drop it) since we include kind verbosely on any other type of feature in other layers.

**Comment by nvkelso** [comment]
> 3) a building with an address has building=yes, addr:housenumber=*. This should result in a building polygon in the buildings layer with kind=building and an address point in the buildings layer with kind=addr (or kind=address?).

This makes sense to me. 

But what happens when a building **with a name** and an address has building=yes, addr:housenumber=*, name=*? Then we generate a `label_placement` using the name, and additionally generate an address point label that happens to be in the same location as the building's `label_placement` and let the client deal with it? Should the `addr:housenumber=*` still be included on the `label_placement` so the client could specify that on a second line in the name rendering?

NOTE: We revised `kind=addr` to `kind=address` earlier in the release.

**Comment by nvkelso** [comment]
> 4) a building with both name=* and addr:housenumber=* would result in both an address point and a label being generated?

Yeah. Is the `addr:housenumber=*` still included on the `label_placement` for the building so the client could specify that on a second line in the name rendering?

**Comment by nvkelso** [comment]
@zerebubuth For all of these, does `building=yes` really mean `building=*`? I think that's how the logic works now.

**Comment by zerebubuth** [comment]
> For all of these, does building=yes really mean building=*? I think that's how the logic works now.

Yeah, I managed to pick examples with `building=yes` for all of them... I was thinking that something like this would happen on the polygon:

* if `building=yes` then output `kind=building`
* elif `building=*` then output `kind=*`
* else don't output a polygon.

**Comment by nvkelso** [comment]
> 5) a building with hotel tags has building=yes, tourism=hotel and name=*. This should result in building polygon in the buildings layer with kind=building and a point in the POIs layer with kind=hotel and name=*. We don't consider the name to apply to the building when there are POI tags. But address tags would still generate an address point in the buildings layer.

What happens when there is **also** a record for that hotel in the point table? Would we get two `label_position` features, one for the building and one for the point? I think we only want one, but maybe this is a separate pass to dedup?

**Comment by nvkelso** [comment]
> 6) a building with theatre tags has building=yes, amenity=theatre and name=*. This should result in building polygon in the buildings layer with kind=building and a point in the POIs layer with kind=theatre and name=*, just like the previous case.

Ditto to 5) above.

**Comment by zerebubuth** [comment]
> I think we only want one, but maybe this is a separate pass to dedup?

I think so too. If there's something in the points table _and_ in the polygons table, that implies that it's duplicated in the original OSM data (as an individual node and also a way/relation). Ideally the data would get fixed, but there'll be some weird corner case where that's not possible, and so it's better to de-dup later on when we've got all the label points together in the same place, as we're post-processing them.

**Comment by nvkelso** [comment]
> 7) a building with landuse and restaurant tags has building=yes, landuse=retail, amenity=restaurant and name=*. This should result in a building polygon in the buildings layer with kind=building and a point in the POIs layer with kind=restaurant and name=*. The landuse value for this building is ignored, although it may get landuse_kind from being enclosed in another landuse polygon anyway.

Yep (and that's what default OSM rendering does).

**Comment by nvkelso** [comment]
> 8) a building with landuse and theatre tags has building=yes, leisure=stadium and amenity=theatre. What should this get?

* We should get a POI that is `kind=theatre` (stadium is less important than amenity in the coalesce here... which is the same logic in the osm.org renderer now – see how they accomplish that).
* We will get a polygon in the buildings layer that has `kind=theatre`.
* There should be no label_position in for the building in the building layer.
* There won't be a `kind=address` address point for this in building layer (no house address is set).

**Comment by nvkelso** [comment]
> 9) a "building" with leisure tags has building=yes and leisure=park. It should get a polygon in the buildings table, and a label point in the landuse layer, but no polygon in the landuse layer?

You managed to find the high line in NYC, which is like a data unicorn! 

Since it has other attributes like `building:color`, `building:material` and `roof:material` we assume that someone really meant it. But if it were **just** `building=yes` and `leisure=park` I'm inclined to **not** include that. Is there any harm in including it, though?

**Comment by nvkelso** [comment]
> 10) a park with a library in it has amenity=library, leisure=park and name=*. It should get a polygon in the landuse layer with kind=park but no label, and a label in the POIs layer with kind=library and name=*.

Did you mean it also has `building=yes`? In that case, I don't expect to see this building appear in the landuse layer (only in the building layer polygons). If it doesn't have `building=*` then sure, landuse only. If it's coming from buildings then this label position would end up in POIs because it's got the `amenity` tag.

**Comment by nvkelso** [comment]
Another strange case:
https://www.openstreetmap.org/way/32113743

Here there's an landuse area that has area=yes for the school grounds, with a name. Should this get a label position? What kind value?

**Comment by zerebubuth** [comment]
> Here there's an landuse area that has area=yes for the school grounds, with a name. Should this get a label position? What kind value?

Since there's no kind value, other than what we can infer from the human-readable name, I think we should ignore this and not generate a polygon or a label position.

**Comment by nvkelso** [comment]
+ @indyhurt as this (polygons with name but no other useful attributes)
seems like a good thing to measure.

**Comment by zerebubuth** [comment]
>> 4) a building with both name=* and addr:housenumber=* would result in both an address point and a label being generated?


> Yeah. Is the addr:housenumber=* still included on the label_placement for the building so the client could specify that on a second line in the name rendering?

For a building with a name and an address (e.g: ["The Corinthian"](http://www.openstreetmap.org/way/355209013)) should that result in these 3 features?

1. A polygon with `kind=apartments` (see, I didn't pick one with `building=yes` this time!) and
2. A point with `kind=address`, `addr_housenumber=512` and
3. A point with `kind=apartments` and `label_placement=yes` and `name=The Corinthian` _and_ `addr_housenumber=512`?

Or should we generate only the `label_placement` point and always merge the address onto it, even when there's no name?

**Comment by nvkelso** [comment]
For now, it should result in all 3 features:

```
1. A polygon with kind=apartments, and
2. A point with kind=address, addr_housenumber=512, and
3. A point with kind=apartments and label_placement=yes and name=The
Corinthian and addr_housenumber=512
```

The features for (2) and (3) will likely have the same x,y coordinate. The
draw order in the renderer would probably be (3) building name
(`label_placement`) first, then draw the (2) address number `kind=address`.
Because of that, advanced renderers should have the option of adding the
`addr_housenumber` on a second line of the name. But in the interest of
slightly duplicate data, basic renderers should have the more complete set
of address information. We definitely don’t want `label_placement:yes`
features without a name.

**Comment by zerebubuth** [comment]
Screenshots after mapzen/TileStache#72 and #307:

## 1. Before
![201-before-buildings-addresses](https://cloud.githubusercontent.com/assets/271360/10494889/d3616524-72b0-11e5-8d03-75628e91e87f.png)

## 1. After
![201-after-buildings-addresses](https://cloud.githubusercontent.com/assets/271360/10494893/db1c3ce4-72b0-11e5-8b27-1d65fc297145.png)

## 2. Before
![201-before-theatre](https://cloud.githubusercontent.com/assets/271360/10494907/ebd55d4a-72b0-11e5-867e-8a1c7f04584a.png)

## 2. After

NOTE: The "Capp's Corner Ristorante" POI and building next to "The Boardroom" appear to be due to old data on my system vs. newer data on dev that I used to produce the "before" image and can safely be ignored. Fugazi Hall, the building of interest, is still showing up and has the properties that we want.

![201-after-theatre](https://cloud.githubusercontent.com/assets/271360/10494906/ea0f3dd2-72b0-11e5-9615-b28fa57f83b5.png)

## 3. Before
![201-before-restaurant](https://cloud.githubusercontent.com/assets/271360/10494921/fb407dc8-72b0-11e5-98e9-7a62fc378f08.png)

## 3. After
![201-after-restaurant](https://cloud.githubusercontent.com/assets/271360/10494924/016d7a66-72b1-11e5-971c-48c232156af5.png)

## 4. Before
![201-before-auditorium](https://cloud.githubusercontent.com/assets/271360/10494942/113a3eca-72b1-11e5-9e13-412cb7dedcbc.png)

## 4. After
![201-after-auditorium](https://cloud.githubusercontent.com/assets/271360/10494949/17042a64-72b1-11e5-8681-840635442df8.png)

**Comment by nvkelso** [comment]
Screenshots look good, let's proceed.

**Comment by nvkelso** [comment]
What does it look like around SF State University (see screenshot top of this issue)?

**Comment by nvkelso** [comment]
Another place to check: Grand Central Terminal rail station in NYC:
https://www.openstreetmap.org/way/265947358

**Comment by nvkelso** [comment]
Whitehall Ferry Terminal in NYC is doing the right thing:
http://vector.mapzen.com/osm/all/19/154354/197144.topojson?api_key=vector-tiles-HqUVidw
http://vector.dev.mapzen.com/osm/all/19/154354/197144.topojson?api_key=vector-tiles-HqUVidw

**Comment by zerebubuth** [comment]
![201-after-sfu](https://cloud.githubusercontent.com/assets/271360/10516661/4684f778-7351-11e5-8c78-4f7f4237c853.png)

As you can see, some of the duplicate labels (e.g: "Fine Arts") are gone, and we only have one. Unfortunately, it's a POI, because these buildings are [incorrectly tagged as individual universities](http://www.openstreetmap.org/way/338711147). If those lose the `amenity=university` then the buildings will get labels instead.

Note that to get the buildings to show up at all, I had to make a couple of style changes:

```
--- scene.yaml 2015-10-14 13:48:58.873495950 +0100
+++ scene.yaml  2015-10-15 15:20:55.483263261 +0100
@@ -2270,7 +2270,7 @@
                 - { $zoom: { min: 13 }, area: { min: 100000 }, name: true }
                 - { $zoom: { min: 14 }, area: { min: 40000 }, name: true }
                 - { $zoom: { min: 15 }, area: { min: 5000 }, name: true }
-                - { $zoom: { min: 16 }, area: { min: 1000 }, name: true }
+                - { $zoom: { min: 16 }, area: { min: 1000 } }#, name: true }
                 - { $zoom: { min: 17 }, area: { min: 500 } }
                 - { $zoom: { min: 18 } }
             all:
@@ -2913,7 +2913,7 @@
                     all:
                         - kind: university
                         - area: true
-                        - label_placement: yes
+                        #- label_placement: yes
                     any:
                         # show labels for smaller landuse areas at higher zooms
                         - { $zoom: { min: 9 },  area: { min: 10000000 } }
```

**Comment by zerebubuth** [comment]
![201-after-grand-central-station](https://cloud.githubusercontent.com/assets/271360/10517112/385300e4-7353-11e5-9bce-417dc2f57aa0.png)

Note that the label is now correctly on "Grand Central Station" as a POI, rather than as a building. Also the duplicate label for "The Grand Hyatt" (hotel & building label) has gone, and now there's only the POI. However, there are still building labels where there are no POIs, e.g: "Socony-Mobil building" and "Chrysler building".

**Comment by nvkelso** [comment]
Cool

**Comment by nvkelso** [comment]
> The question is whether to alter all the styles, or to add label_placement=yes to all the POIs?

I updated the styling in Skin & Bones last week to account for this without needing to add `label_placement=yes` to all the POIs. Let's live with that in `dev` and see how it works out.

**Comment by nvkelso** [comment]
Related: https://github.com/nvkelso/tangram-skin-and-bones/issues/13

**Comment by nvkelso** [comment]
Regarding case 3 above, looks like the address label position `2525` in this tile should be marked `kind=address`, but is only showing up as a property attribute on the polygon with `kind=building`.

http://vector.dev.mapzen.com/osm/all/20/167699/405201.topojson?api_key=vector-tiles-HqUVidw

**Comment by nvkelso** [comment]
Regarding case 5 above and the Comfort Inn `kind=hotel` in the following tile, should we drop the feature's `area` if it ends up in the POIs layer if it doesn't have `label_position=yes`?

http://vector.dev.mapzen.com/osm/all/20/167699/405200.topojson?api_key=vector-tiles-HqUVidw

This inconsistency is causing styling bugs (where we're dropping POIs from display that are in tiles). We can probably refactor around this in the scene file (he says hopefully), but seems like if we drop `label_position`, we should also drop the `area`.

**Comment by nvkelso** [comment]
Same problems with example 6 above (has `area` but no `label_position`) for [Fugazi Hall](http://www.openstreetmap.org/way/32866034#map=19/37.79964/-122.41020), but it is correctly showing up in the [POIs layer](http://vector.dev.mapzen.com/osm/all/20/167742/405205.topojson?api_key=vector-tiles-HqUVidw).

**Comment by nvkelso** [comment]
Same problems with example 7 above (has `area` but no `label_position`) for Outback Steakhouse, but it is correctly showing up in the [POIs layer](http://vector.dev.mapzen.com/osm/all/19/84615/203305.topojson?api_key=vector-tiles-HqUVidw).

**Comment by nvkelso** [comment]
Same problems with example 8 above (has `area` but no `label_position`) for `Bill Graham Civic Auditorium`, but it is correctly showing up in the [POIs layer](http://vector.dev.mapzen.com/osm/all/19/83860/202642.topojson?api_key=vector-tiles-HqUVidw) and is correctly getting `kind=theatre`.

**Comment by nvkelso** [comment]
Hard to verify the High Line example 9. But this tile makes it seem like it's working: http://vector.dev.mapzen.com/osm/all/16/19295/24631.topojson?api_key=vector-tiles-HqUVidw. Although there's a spare `mz_is_building=true` hiding out there. There are also labels for the High Line as a building, which seems weird, though.

**Comment by nvkelso** [comment]
Example 10 with the library is working, except for the common thread of `area` && `label_position` pairing. 

* http://vector.dev.mapzen.com/osm/all/19/154913/196512.topojson?api_key=vector-tiles-HqUVidw

**Comment by nvkelso** [comment]
Action item: If we're putting a POI sourced from landuse or buildings into the POI layer, let's include both it's source `area` (already happening) and mark it as `label_position=yes` (todo).

**Comment by zerebubuth** [comment]
> Action item: If we're putting a POI sourced from landuse or buildings into the POI layer, let's include both it's source area (already happening) and mark it as label_position=yes (todo).

I don't understand the rationale behind this. If we have a POI then why do we care whether it has come from a polygon or a point table?

Is there something that `label_placement=yes` is used to signify other than the source table of the data, as that really should be an implementation detail that we don't expose. At the moment it's correlated with area, but only because we don't (yet... #348) have a good way of figuring out how to assign building area to POIs.

(As a side note, started #347 to track using `representative_point` for calculating POI positions from polygons.)

**Comment by zerebubuth** [comment]
> Regarding case 3 above, looks like the address label position 2525 in this tile should be marked `kind=address`, but is only showing up as a property attribute on the polygon with `kind=building`.

I'm getting this locally:

```json
  {
    "type": "Point",
    "properties": {
      "source": "openstreetmap.org",
      "kind": "address",
      "addr_housenumber": "2525",
      "addr_street": "Van Ness Avenue",
      "id": 69707523
    },
    "coordinates": [
      676,
      797
    ]
  }
```

So something is going on. Not sure if it's a code difference between dev and my local machine, or a database difference. Will investigate further.

**Comment by zerebubuth** [comment]
> So something is going on. Not sure if it's a code difference between dev and my local machine, or a database difference. Will investigate further.

This [tile](https://s3.amazonaws.com/mapzen-tiles-dev-us-east-20151029/osm/all/20/167699/405201.topojson) looks good in dev as of last night's deploy. So either there was a temporary regression which got fixed, or something weirder is going on.

This might be an _excellent_ candidate for a "unit test".

**Comment by nvkelso** [comment]
@zerebubuth Here's an interesting case where no name, the building is tagged as an appartment, and it has an address. Should the kind=address or kind=appartment?

http://vector.dev.mapzen.com/osm/all/19/83848/202601.topojson?api_key=vector-tiles-HqUVidw

**Comment by nvkelso** [comment]
I've gotten around the `label_position` thing by using `$geometry: point` paired with `area: true` which works in Tangram JS / WebGL and is soon to work in Tangram ES (PR landed Thursday?).

**Comment by zerebubuth** [comment]
> Here's an interesting case where no name, the building is tagged as an appartment, and it has an address=1595. Should the kind=address or kind=appartment?
>
> http://vector.dev.mapzen.com/osm/all/19/83848/202601.topojson?api_key=vector-tiles-HqUVidw

I'm seeing two features there:

```json
  {
    "type": "Polygon",
    "properties": {
      "kind": "apartments",
      "area": 544,
      "addr_street": "Greenwich Street",
      "height": 14,
      "volume": 7616,
      "source": "openstreetmap.org",
      "addr_housenumber": "1595",
      "id": 243508784
    },
    "arcs": [
      [
        2
      ]
    ]
  },
  ...
  {
    "type": "Point",
    "properties": {
      "source": "openstreetmap.org",
      "kind": "address",
      "addr_housenumber": "1595",
      "addr_street": "Greenwich Street",
      "id": 243508784
    },
    "coordinates": [
      807,
      43
    ]
  },
```

Which is what [we agreed](https://github.com/mapzen/vector-datasource/issues/201#issuecomment-147870838) before. The `addr_housenumber` is left on the building polygon in case it's useful to some renderers, but generally it should be ignored if the `kind=address` points are being rendered.

**Comment by nvkelso** [comment]
I see the same thing now, and it's to spec, so nothing more to see here.
