### ISSUE TITLE
Low zoom (NE) roads missing segments

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#204]
We've regressed the low zoom roads:

<img width="472" alt="screen shot 2015-09-11 at 15 20 41" src="https://cloud.githubusercontent.com/assets/853051/9828033/419edd92-589d-11e5-8c21-30d1149cdc19.png">

Probably related:

* https://github.com/mapzen/vector-datasource/issues/136

We've ignored the issue for now by turning off updates on zooms 0-8.

**Comment by zerebubuth** [comment]
After mapzen/TileStache#52:

![204-missing-roads-fixed](https://cloud.githubusercontent.com/assets/271360/9912059/635ed69a-5c9d-11e5-8549-5712d159cb12.png)

**Comment by zerebubuth** [comment]
@nvkelso looks good?

**Comment by nvkelso** [comment]
Yes, looks good.

I see a few gaps in the road network, but those were there before and look to be a Natural Earth road bug: https://github.com/nvkelso/natural-earth-vector/issues/147

**Comment by nvkelso** [comment]
Fixed in https://github.com/mapzen/TileStache/pull/52.
