### ISSUE TITLE
Tweak NE to OSM transition to zoom 8 (all but places)

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#205]
We adjusted the internal NE data zoom transitions with https://github.com/mapzen/vector-datasource/pull/172 and https://github.com/mapzen/vector-datasource/issues/145 but we still need to move the overall Natural Earth to OSM zoom transition from zoom 9 to zoom 8.

This needs to be for all features in all layers (there are other tickets to adjust a couple individual features earlier).

**Comment by zerebubuth** [comment]
All features in all layers, or all features in all layers but places? (Is the text body or title correct?)

**Comment by nvkelso** [comment]
Needs to start showing OSM at zoom 8 (the last NE test needs to be <8 not <9):

- [ ] boundaries
- [ ] landuse - generally we need to move this to 8, but some other issues reference a subset of feature that should show earlier.
- [ ] landuse_labels – same deal was landuse changes above
- [ ] roads

These are optional. Visually it's better to leave as-is (transition at 9 not 8), but may be required to match up with changes above.

- [ ] earth
- [ ] water

OSM should remain at zoom 9 (the last NE test should remain <9):
- [x] places - This one needs more and different work, no change now
- [x] pois - these only come in at zoom 9 now for airports only, no change needed

Not relevant/ignore:
- [x] buildings - these only come in at zoom 13 now
- [x] transit - some things come in at zoom 6 now, no change

Additionally, we're should be calculating `landuse-labels` for `parks` in earlier zooms from Natural Earth, that's a separate issue: 

- [ ] landuse_labels

**Comment by nvkelso** [comment]
Back to @zerebubuth to coordinate changes with https://github.com/mapzen/vector-datasource/issues/149.

**Comment by zerebubuth** [comment]
See screenshots in #229 for cross-fading of urban areas. Unfortunately, you can only see the limited subset of stuff loaded on my box - dev will show this better.

**Comment by nvkelso** [comment]
Primary roads need to be visible at z8, too. Else gaps are visible. Otherwise looks good.
