### ISSUE TITLE
Improve data for admin boundary in the water

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#210]
Right now vector tiles don't indicate if a boundary (country, state, region, county, etc) is over the water or not. We should indicate this case to improve styling (color them blue, hide them, etc).

**Comment by nvkelso** [comment]
See also: 

* https://github.com/mapzen/vector-datasource/issues/180

**Comment by nvkelso** [comment]
Looks like the existing [boundary_type](http://wiki.openstreetmap.org/wiki/Key:border_type) property in the boundary query doesn't give us enough information for all maritime boundaries.

We need to export tags for [boundary%3Dmaritime](http://wiki.openstreetmap.org/wiki/Tag:boundary%3Dmaritime)

**Comment by zerebubuth** [comment]
The work for #180 makes this way more difficult than just looking at a tag. Also, a maritime boundary isn't the same thing as a boundary over water. For example, [this border](http://www.openstreetmap.org/way/61602969) is entirely in the Hudson River, but isn't a maritime boundary.

If we want boundaries over water distinguished from boundaries over land for rendering purposes, then perhaps we need to intercut the water layer and boundaries layer. If we want maritime boundaries, then possibly that data can be recovered by intersecting the LineStrings, but I'm not 100% confident that it'll work.

@nvkelso, is it the former or latter that we're interested in?

**Comment by nvkelso** [comment]
We do need maritime to deal with that case, thanks for bringing this up!

**Comment by zerebubuth** [comment]
Hmm... looks like the boundary up the Hudson River is marked `maritime=yes` (e.g: ways [61602961](http://www.openstreetmap.org/way/61602961) and [61602969](http://www.openstreetmap.org/way/61602969)). In previous discussions, we'd talked about _not_ wanting to lose that boundary when intersecting with any water, so I think we'll need to think a bit more on what exactly it is that we want shown (or not shown) in the tiles.

**Comment by nvkelso** [comment]
Let's bootstrap this using the maritime=yes tag alone and see how that goes.

**Comment by zerebubuth** [comment]
After #236 and mapzen/TileStache#54, this is what it looks like. Maritime boundaries (with `maritime=yes`) are in blue, other boundaries in red:

![210-nyc-2](https://cloud.githubusercontent.com/assets/271360/10052239/cac79ca6-621d-11e5-9e45-a81814a11cd3.png)

![210-nyc-3](https://cloud.githubusercontent.com/assets/271360/10052243/ce56bd2a-621d-11e5-8b6a-15e7c25791a5.png)

![210-manhattan-2](https://cloud.githubusercontent.com/assets/271360/10052245/d055ccb0-621d-11e5-8fd8-7884461d4356.png)

@nvkelso could you review, please?

**Comment by zerebubuth** [comment]
I should note: the missing boundaries are due to cut-offs in the data I've loaded locally - not, as far as I can tell, due to the processing. But we'll need to see it on dev to be sure.

**Comment by nvkelso** [comment]
Over to @rmarianski to resolve the missing `kind` values on some boundary lines.

**Comment by rmarianski** [comment]
@nvkelso Looks ok to you?

**Comment by nvkelso** [comment]
Drrrr, the `kind` thing is complicated to solve. We're [rolling back](https://github.com/mapzen/vector-datasource/pull/256) part of this so we can take the rest of the sprint to prod.

Outstanding issues:

* Not always getting `kind` and `admin_level` back on features. Probably requires to transform function in python.
* Boundaries there are not shared are getting dropped (e.g. maritime boundaries between admin_level=[2,4] and open ocean). Root cause might be [this join logic](https://github.com/mapzen/vector-datasource/blob/4c59ac235e7fa7059f3c1db3d5b46f4bb0466bb2/queries/boundaries.jinja2#L94
).
* Often the state and country boundaries are being dropped in favor of the next admin_level down (e.g.: we're seeing state boundaries `4` instead of country boundaries `2` along the frontier. And we're seeing county boundaries `6` instead of state boundaries `4` in other places. Requires investigation.

**Comment by nvkelso** [comment]
Adding missing images.

![2-handed-versus-1-handed](https://cloud.githubusercontent.com/assets/853051/10144939/294c1a12-65d5-11e5-8af2-c9ee47e782c2.png)

![county-state-country](https://cloud.githubusercontent.com/assets/853051/10144938/2935728a-65d5-11e5-90f8-2794d3a1ab24.png)

**Comment by zerebubuth** [comment]
There's a problem with this that I can't think of a simple way around. For example, take the international boundary near Vancouver:

![210-bad-boundary](https://cloud.githubusercontent.com/assets/271360/10168496/fcb81eec-66c4-11e5-933e-9b106f310d02.png)

The red lines are international boundaries, magenta with `maritime_boundary=yes`, green are state level boundaries, cyan with `maritime_boundary=yes`.

There are a couple of interesting features:

![210-bad-boundary-annotated](https://cloud.githubusercontent.com/assets/271360/10168603/7078c746-66c5-11e5-8bb2-31c8be88bd80.png)

In both of these cases, the maritime boundary appears to be present, but isn't projecting down onto the border. The issue appears to be that there's an extra point in the representation of the maritime boundary. This is what the upper feature looks like:

![210-missing-point](https://cloud.githubusercontent.com/assets/271360/10168666/b6e3dd74-66c5-11e5-8a2d-0b54cc0835ab.png)

The large, red points are present in the polygon boundary and the smaller, blue ones are present in the maritime boundary. When these points are extracted:

```python
shape = g.linestring.LineString([[-13804958.87, 6156352.28], [-13859722, 6179044.59]])
cut_shape = g.linestring.LineString([[-13804958.87, 6156352.28],[-13816141.2857036, 6160985.96042869],[-13859722, 6179044.59]])
inside = shape.intersection(cut_shape)
print inside.wkt
# 'MULTIPOINT (-13859722 6179044.59, -13804958.87 6156352.28)'
print g.point.Point(-13816141.2857036, 6160985.96042869).distance(shape)
# 3.15023712478e-09
```

Which is saying that the point is effectively collinear with the points either side of it (3e-9 mercator meters is probably pretty close to numerical noise), but that the intersection algorithm considers it to be different enough that it excludes that segment from the result.

In the short term, we have some options:

1. Use this anyway, knowing that there'll be plenty of these places where the intersection doesn't work right, and the maritime property isn't right.
2. Don't put a maritime property on the admin boundaries - I think the rest of this patch is okay, but will need proper testing.
3. Find some other source for the maritime property, e.g: buffered coastline.

**Comment by nvkelso** [comment]
(Let’s prototype with option 3 – Find some other source for the maritime
property, e.g: buffered coastline.)

**Comment by zerebubuth** [comment]
Results of prototype 3:

![210-maritime-3](https://cloud.githubusercontent.com/assets/271360/10198074/582c20fc-6792-11e5-8487-f3c2ab1cbd1c.png)

You can see that the boundary is mostly cyan/purple which means it has `maritime_boundary=yes` on it. The parts closer to the coast don't, and are green/red. Zooming in closer you can see the left/right labelling on the international boundary:

![210-prototype-maritime](https://cloud.githubusercontent.com/assets/271360/10198055/3172954a-6792-11e5-970e-fb66e8f880da.png)

**Comment by bcamper** [comment]
Curved labels anyone? ;)

**Comment by nvkelso** [comment]
Looks pretty good. Let's take it into dev for a test drive. /cc @rmarianski

**Comment by nvkelso** [comment]
> Curved labels anyone? ;)

Yes, please!

**Comment by nvkelso** [comment]
Looks good around California. Need to review in more complicated areas.

**Comment by nvkelso** [comment]
Channel Islands off California need to be added to the maritime SHP (we shouldn't see boundary here):

<img width="836" alt="screen shot 2015-10-03 at 16 57 59" src="https://cloud.githubusercontent.com/assets/853051/10265684/0c4373c4-69f0-11e5-9480-865460931e20.png">

**Comment by nvkelso** [comment]
Near Virginia and Washington DC:
#9/37.8427/-75.6437

<img width="749" alt="screen shot 2015-10-03 at 17 05 57" src="https://cloud.githubusercontent.com/assets/853051/10265711/10867d36-69f1-11e5-9650-f1b747ed6b6d.png">

**Comment by nvkelso** [comment]
South Carolina:
#9/33.2973/-79.3591

<img width="686" alt="screen shot 2015-10-03 at 17 06 44" src="https://cloud.githubusercontent.com/assets/853051/10265717/2dcde5aa-69f1-11e5-994d-c0966b7670ac.png">

**Comment by nvkelso** [comment]
Florida:
#8/27.496/-79.579

<img width="333" alt="screen shot 2015-10-03 at 17 07 32" src="https://cloud.githubusercontent.com/assets/853051/10265724/44a3a134-69f1-11e5-9dbf-b4ff8cb7a4c5.png">

**Comment by nvkelso** [comment]
Let's call this good enough, and track the rest in #294.
