### ISSUE TITLE
filter buildings by volume (and area)

### ISSUE THREAD

**Issue by meetar** [mapzen/vector-datasource#212]
< zoom 15, many prominent buildings in downtown NYC are filtered out because they have relatively small footprints, eg One World Trade – maybe we could use building height to filter them by volume, either instead of or in addition to area, to keep some of these around.

**Comment by bcamper** [comment]
Great catch, this transition has been bothering me but it didn't click as to why.

**Comment by nvkelso** [comment]
Nice! 

If building has height data to calculate volume, filter on volume. Else still filter on building (footprint) area.

@meetar and @bcamper what volumes do you recommend per zoom?

**Comment by meetar** [comment]
After some tests, I'd suggest these minimum volumes:
z13: 300000
z14: 200000
z15: 100000

**Comment by nvkelso** [comment]
Are the volumes naive footprint area * height?

**Comment by meetar** [comment]
Yep, I was going to dunk each building into a water tank to measure the displacement but somebody else is using the 3D printer today :D

**Comment by nvkelso** [comment]
Ha!

**Comment by nvkelso** [comment]
We should filter what goes into tiles at the above zooms based on the calculated volume.

**Comment by zerebubuth** [comment]
## Zoom 13

### Before

![nyc_before_z13](https://cloud.githubusercontent.com/assets/271360/10738464/7da51f78-7c0f-11e5-9a9d-8cbc4b0be1ce.jpg)

### After

![nyc_after_z13](https://cloud.githubusercontent.com/assets/271360/10738467/8176dc90-7c0f-11e5-8c6f-048975354c2d.jpg)

## Zoom 14

### Before

![nyc_before_z14](https://cloud.githubusercontent.com/assets/271360/10738471/84ef0852-7c0f-11e5-90b6-36c34f1d9c87.jpg)

### After

![nyc_after_z14](https://cloud.githubusercontent.com/assets/271360/10738473/875a961a-7c0f-11e5-80a5-b4c53ae6286a.jpg)

## Zoom 15

### Before

![nyc_before_z15](https://cloud.githubusercontent.com/assets/271360/10738474/8b21807e-7c0f-11e5-9f6b-36447c3c3fc3.jpg)

### After

![nyc_after_z15](https://cloud.githubusercontent.com/assets/271360/10738480/8e30c392-7c0f-11e5-9225-ea0d17d639ab.jpg)

**Comment by nvkelso** [comment]
LGTM, thanks! Let's take it to `dev` so we can QA wider sample of locations (Midtown NYC etc).

cc @meetar

**Comment by nvkelso** [comment]
Looks like the `volume` is being included in tiles (good), but it's a `float` and only needs to be an `int`.

http://vector.dev.mapzen.com/osm/all/13/2412/3079.topojson?api_key=vector-tiles-HqUVidw

**Comment by nvkelso** [comment]
Other than that, looking good. We'll include `volume` as an attribute. And if we need to cull features for perf reasons from tiles, that's a later task.

**Comment by nvkelso** [comment]
LGTM.
