### ISSUE TITLE
Direction of 'oneway'

### ISSUE THREAD

**Issue by musicformellons** [mapzen/vector-datasource#215]
Using this:

     "source-layer": "roads",
      "type": "symbol",
      "layout": {
        "text-field": "{oneway}"
      }

The 'oneway' gives either 'yes' or none and sometimes 'no'. To make the oneway worthwhile it would be nice to know in which direction.

**Comment by zerebubuth** [comment]
It should be in the same direction as the LineString. Generally, values of "oneway" are "yes", "no", and "reverse", meaning in the direction of the LineString, two-way and in the opposite direction to the LineString, although it's possible that some intermediate step resolves the last option by reversing the LineString itself.

**Comment by rmarianski** [comment]
Indeed, our service does reverse the LineString for values of `reverse` and `-1`.

https://github.com/mapzen/TileStache/blob/e29248b47caed25a61441b23b6addd053e9cc58d/TileStache/Goodies/VecTiles/transform.py#L291-L308

**Comment by nvkelso** [comment]
Documentation provided, no code changes needed.

**Comment by musicformellons** [comment]
Works. Great!
