### ISSUE TITLE
Some piers not showing up in landuse

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#217]
What's special about this pier that it's not returned as a landuse feature in tiles? 

https://www.openstreetmap.org/way/23605169

**Comment by rmarianski** [comment]
I checked the database and it's correctly labeled as landuse there. My guess is that it's not included because of an area filter. Does it show up for zooms > 15?

**Comment by nvkelso** [comment]
Thanks! The area filter was partly to blame, but more importantly the layer order was set to 2 (under water), and it needs to be 4 (above water).
