### ISSUE TITLE
order of lines on top of each other

### ISSUE THREAD

**Issue by musicformellons** [mapzen/vector-datasource#219]
Although the tramrail (grey line) layer comes after the road layer (whiteline) in my stylesheet, it does not show on top. It does when they just cross, but not when the rail runs on top of road (so paralel). How do I solve this?
![image](https://cloud.githubusercontent.com/assets/10334123/9937173/e7da797a-5d5f-11e5-8fb2-99baeda95895.png)

**Comment by zerebubuth** [comment]
Are you using [tangram](https://github.com/tangrams/tangram) to render these maps? If so, then you might have to override the [order](https://github.com/tangrams/tangram-docs/blob/gh-pages/pages/draw.md#order) for the tram lines so that they draw on top of the roads. Hope that helps!

**Comment by musicformellons** [comment]
I'm using Mapbox-gl-js, so maybe I ask overthere...

**Comment by nvkelso** [comment]
Yeah, that's a renderer specific detail. Good luck!
