### ISSUE TITLE
separate cycleway from path

### ISSUE THREAD

**Issue by musicformellons** [mapzen/vector-datasource#220]
Seems to me that cycleways are part of 'path':
road_kind_path = set(('footpath', 'track', 'footway', 'steps', 'pedestrian',
                      'path', 'cycleway'))

For my purposes it would be nice to be able to separate 'walking' paths from cycle paths.

**Comment by nvkelso** [comment]
The original `highway` tags should still be available in the `highway` property. 

(You are right that `kind` is collapsing that as you describe, but the original data is still available to you.)

**Comment by musicformellons** [comment]
Great, found it!
