### ISSUE TITLE
how to filter an underground station 'building'

### ISSUE THREAD

**Issue by musicformellons** [mapzen/vector-datasource#223]
I have this:
![image](https://cloud.githubusercontent.com/assets/10334123/9963114/b595df98-5e29-11e5-8288-acec79162591.png)

Where OSM shows correctly that this is an underground station:
![image](https://cloud.githubusercontent.com/assets/10334123/9963133/d6b2ddca-5e29-11e5-975f-a2598150e2d9.png)

building=> height, min_height, roof_height do not give me any values, so what can I use for filtering this underground building out?

**Comment by zerebubuth** [comment]
Yup, this is a known issue at the moment, but we're working on it in #194. After that's done, you should be able to filter on an attribute to tell whether a building is underground or not.

**Comment by musicformellons** [comment]
Great!

**Comment by nvkelso** [comment]
As Matt mentioned, this is a dup of: https://github.com/mapzen/vector-datasource/issues/194
