### ISSUE TITLE
'preferred setup' with tileserver or tilestache fork?

### ISSUE THREAD

**Issue by musicformellons** [mapzen/vector-datasource#233]
After reference is made to the fact that Mapzen vector tile service uses a tilestache fork in its setup, in the description overhere:
https://github.com/mapzen/vector-datasource/wiki/Mapzen-Vector-Tile-Service

tileserver is used instead. Why is that, as it is a bit confusing?

**Comment by rmarianski** [comment]
Thanks for reporting this. We updated the documentation on the getting started instructions wiki that you link to, but I didn't make the corresponding update in the vector-datasource readme.

**Comment by musicformellons** [comment]
Clear now, thanks!
