### ISSUE TITLE
Traffic signals shouldn't be visible until z14

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#247]
They currently show up at z12. They shouldn't until z14.

* http://nvkelso.github.io/tangram-skin-and-bones/#12/39.9541/-75.1635

<img width="232" alt="screen shot 2015-09-25 at 00 57 59" src="https://cloud.githubusercontent.com/assets/853051/10095707/8a26baf2-6320-11e5-83d2-63142e94cfc0.png">

* http://nvkelso.github.io/tangram-skin-and-bones/#14/39.9541/-75.1635

<img width="651" alt="screen shot 2015-09-25 at 00 57 12" src="https://cloud.githubusercontent.com/assets/853051/10095681/6b7f28b4-6320-11e5-86d9-bc69dc1e08aa.png">

**Comment by zerebubuth** [comment]
I'm not seeing these until z17 now, which corresponds to what's in the query. Is this still an issue? Should we bring them up to z14?

**Comment by nvkelso** [comment]
I think this issue was filed before we changed how the POI zooms were calculated, so configuration changed and let's close this. 

After filing this issue, I modified the scene file to intervene and [preventing traffic_signals from showing up until zoom 17](https://github.com/nvkelso/tangram-skin-and-bones/blob/gh-pages/scene.yaml#L2968-L2970). I'll revert that now that tiles have better data.

**Comment by nvkelso** [comment]
See also: https://github.com/nvkelso/tangram-skin-and-bones/commit/1eba6fed31806713cd59441f183fca2e9edc5b78
