### ISSUE TITLE
Update landuse-labels to show earlier

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#248]
To match the work performed in #149.

**Comment by rmarianski** [comment]
We should get this for free once this lands: https://github.com/mapzen/tilequeue/issues/21

**Comment by zerebubuth** [comment]
We should already have this. See [the change](https://github.com/mapzen/vector-datasource/pull/227/files#diff-5) in #227.

The labels won't be de-duped, but that would be better done as part of mapzen/tilequeue#21 as @rmarianski suggests.

**Comment by nvkelso** [comment]
I’m not seeing labels for National Parks or any other landuse features at
zooms less than 8.

**Comment by zerebubuth** [comment]
Looks like a typo here: https://github.com/mapzen/vector-datasource/blob/master/queries/landuse_labels.jinja2#L9 should say `{% filter geometry %}mz_centroid{% endfilter %} AS __geometry__` instead - it's pulling the polygon out, which is being thrown away by the geometry type filter.
