### ISSUE TITLE
differing highway types on zl8

### ISSUE THREAD

**Issue by gronke** [mapzen/vector-datasource#259]
- A: http://vector.mapzen.com/osm/roads/8/132/83.json
- B: http://vector.mapzen.com/osm/roads/8/133/83.json

Adjacent vectiles  `8/132/83` and `8/132/83` both contain highways, but from different data sources having diverged property keys.

#### From URL B
```javascript
{
  "kind":"highway"
}
```

#### From URL A
```javascript
{
  "kind":"Road",
  "type":"Major Highway"
}
```

**Comment by nvkelso** [comment]
Sorry about that! We're in the middle of pushing out 0.3.0 over the weekend. You're probably experienced a burp in the edge cache while tiles are processing (eta for completion is Monday). Will research more why you saw the blip.

**Comment by gronke** [comment]
@nvkelso no worries! Just giving you a heads-up in case its unwanted. :santa: Thanks for your always quick responses.

**Comment by nvkelso** [comment]
@rmarianski Can you take a look at this, please? I'm still seeing this problem today.

**Comment by rmarianski** [comment]
Yup, I'm still seeing it too. I've verified that the tile in question hasn't been processed yet, and is still in the queue. I don't have much insight into when it'll be finished though. My guess is that it'll get processed tonight.

**Comment by rmarianski** [comment]
The tiles linked to have been updated, but some of the others are still coming through.

**Comment by nvkelso** [comment]
Looks like the update finished everywhere.
