### ISSUE TITLE
Density filter for POIs / labels

### ISSUE THREAD

**Issue by zerebubuth** [mapzen/vector-datasource#266]
As a post-process filter, we should be able to control the density of POIs and labels, preventing a whole bunch of them from rendering on top of one another. Client-side clipping will help, but it would be better to not send all of this data to begin with.

The issue arises because many buildings and other features are legitimately clustered, and each may have its own label / icon. However, once zoomed out these become all mashed together. The fix has to be something that's "zoom sensitive" as it doesn't make sense to merge these POIs at all zooms.

One possible implementation is to divide up the tile into NxN blocks (possibly even one 1x1) and rank the POIs within each block, possibly by type, taking only the most prominent and/or collapsing several of the same type into each other. For example, when binning mountain peaks, order by elevation and take only the highest within the block.

**Comment by zerebubuth** [comment]
We kind-of have this with the `keep_n_features` filter implemented as part of #268. We should evaluate the fix for #268 when it hits dev and come up with some specific examples to work on.

**Comment by zerebubuth** [comment]
Example: Lombard Motor Inn, see [these](https://github.com/mapzen/vector-datasource/issues/320#issuecomment-151364692) [comments](https://github.com/mapzen/vector-datasource/issues/320#issuecomment-151461566) for more details.

**Comment by zerebubuth** [comment]
After mapzen/TileStache#85 and #354:

### Before

![lombard_motor_inn_z18_before](https://cloud.githubusercontent.com/assets/271360/10797176/519475ce-7d99-11e5-8d51-4400838892fa.jpg)

### After

Only one "Lombard Motor Inn"!

![lombard_motor_inn_z18_after](https://cloud.githubusercontent.com/assets/271360/10797190/5abeb9b6-7d99-11e5-8b35-7d399f4ce144.jpg)

**Comment by nvkelso** [comment]
Super cool!

**Comment by zerebubuth** [comment]
I'm seeing this for the Everett Middle School / Sanchez Elementary School examples now:

![everett_middle_school_z17_after](https://cloud.githubusercontent.com/assets/271360/10800099/213f5b32-7da8-11e5-8412-243a5cb0bc21.jpg)

**Comment by nvkelso** [comment]
Great! Let's QA this in dev now :)

**Comment by nvkelso** [comment]
Huge improvement overall :)

One problem so far, though...

Looks like we're missing the `California Academy of Sciences` in SF (`kind=museum`) in dev versus prod.

* #17/37.76983/-122.46657
* http://vector.dev.mapzen.com/osm/all/17/20947/50664.topojson?api_key=vector-tiles-HqUVidw
* http://vector.mapzen.com/osm/all/17/20947/50664.topojson?api_key=vector-tiles-HqUVidw

```
geometries: [
{
type: "Polygon",
properties: {
kind: "museum",
roof_material: "grass",
name: "California Academy of Sciences",
area: 25170,
landuse_kind: "park",
addr_street: "Music Concourse Drive",
height: 95,
addr_housenumber: "55",
id: 28695389
},
```

**Comment by nvkelso** [comment]
`Costco` is missing:

* #18/37.77089/-122.41028
* http://vector.dev.mapzen.com/osm/all/15/5241/12666.topojson?api_key=vector-tiles-HqUVidw
* http://vector.mapzen.com/osm/all/15/5241/12666.topojson?api_key=vector-tiles-HqUVidw

```
{
type: "Point",
properties: {
label_placement: "yes",
kind: "supermarket",
area: 20711,
id: 43100828,
name: "Costco"
},
coordinates: [
913,
973
]
```

**Comment by nvkelso** [comment]
Westfields is missing:

* #18/37.78407/-122.40616
* http://vector.mapzen.com/osm/all/15/5242/12664.topojson?api_key=vector-tiles-HqUVidw
* http://vector.dev.mapzen.com/osm/all/15/5242/12664.topojson?api_key=vector-tiles-HqUVidw

```
{
type: "Point",
properties: {
label_placement: "yes",
kind: "retail",
name: "Westfield San Francisco Centre",
area: 38946,
height: 62,
id: 332627424
},
coordinates: [
307,
561
]
},
```

**Comment by nvkelso** [comment]
Ferry Building is missing / corrupted (only has address part?):

* #18/37.79575/-122.39259
* http://vector.mapzen.com/osm/all/16/10486/25326.topojson?api_key=vector-tiles-HqUVidw
* http://vector.dev.mapzen.com/osm/all/16/10486/25326.topojson?api_key=vector-tiles-HqUVidw

```
{
type: "Point",
properties: {
label_placement: "yes",
kind: "terminal",
name: "Ferry Building",
area: 16786,
height: 82,
id: 24460886
},
coordinates: [
979,
733
]
},
```

**Comment by nvkelso** [comment]
Generally all these things used to show up around zoom 15 (they are more important than the average POI), but now don't show up at all.

**Comment by zerebubuth** [comment]
> Generally all these things used to show up around zoom 15 (they are more important than the average POI), but now don't show up at all.

I can confirm that all of these had a null `mz_centroid` column, which is why they weren't showing. Not quite sure how this would happen, but we prefer `representative_point` now anyway, and mapzen/TileStache#88 and #362 should have fixed this, and we can check after dev is next deployed.

**Comment by nvkelso** [comment]
We're missing the building label position for the **InterContinental Hotel Mark Hopkins** in SF:

http://vector.mapzen.com/osm/all/16/10483/25327.topojson?api_key=vector-tiles-HqUVidw
http://vector.dev.mapzen.com/osm/all/16/10483/25327.topojson?api_key=vector-tiles-HqUVidw

```
{
"coordinates":
[
925,
760
],
"properties":
{
"area":
6955,
"id":
288499856,
"kind":
"hotel",
"label_placement":
"yes",
"name":
"InterContinental Hotel Mark Hopkins"
},
"type":
"Point"
},
```

**Comment by nvkelso** [comment]
We're missing the building label position for the **The Fairmont San Francisco Hotel** in SF:

http://vector.mapzen.com/osm/all/16/10483/25327.topojson?api_key=vector-tiles-HqUVidw
http://vector.dev.mapzen.com/osm/all/16/10483/25327.topojson?api_key=vector-tiles-HqUVidw

```
{
type: "Point",
properties: {
label_placement: "yes",
kind: "hotel",
area: 13558,
id: 32947165,
name: "The Fairmont San Francisco Hotel"
},
coordinates: [
929,
1016
]
},
```

**Comment by nvkelso** [comment]
We're missing a label position for **UCSF Medical Center at Mount Zion** in SF:

http://vector.mapzen.com/osm/all/14/2619/6332.topojson?api_key=vector-tiles-HqUVidw
http://vector.dev.mapzen.com/osm/all/14/2619/6332.topojson?api_key=vector-tiles-HqUVidw

```
{
type: "Point",
properties: {
label_placement: "yes",
kind: "hospital",
name: "UCSF Medical Center at Mount Zion",
area: 4545,
landuse_kind: "hospital",
id: 256633745
},
coordinates: [
674,
832
]
},
```

**Comment by nvkelso** [comment]
(All the missing centroid problems have been fixed!)

**Comment by nvkelso** [comment]
We're missing a label position for **Grace Cathedral** in SF:

http://vector.mapzen.com/osm/all/14/2620/6331.topojson?api_key=vector-tiles-HqUVidw
http://vector.dev.mapzen.com/osm/all/14/2620/6331.topojson?api_key=vector-tiles-HqUVidw

```
{
type: "Point",
properties: {
label_placement: "yes",
kind: "place_of_worship",
name: "Grace Cathedral",
area: 4079,
landuse_kind: "place_of_worship",
id: 32946942
},
coordinates: [
846,
220
]
},
```

**Comment by nvkelso** [comment]
**Best Buy** in San Francisco is was `kind:electronics` but is now showing up as `kind:building`, a regression.

* http://vector.mapzen.com/osm/all/17/20966/50665.topojson?api_key=vector-tiles-HqUVidw
* http://vector.dev.mapzen.com/osm/all/17/20966/50665.topojson?api_key=vector-tiles-HqUVidw

This is also impacting it's styled zoom visibility because the scene file hides generic building names until later zooms, but shows labels with a kind set (to something other than `building`) at earlier zooms.

dev:

```
{
type: "Point",
properties: {
label_placement: "yes",
kind: "building",
name: "Best Buy",
area: 6595,
landuse_kind: "retail",
addr_street: "Harrison Street",
source: "openstreetmap.org",
addr_housenumber: "1717",
id: 25821942
},
coordinates: [
877,
933
]
},
```

prod:
```
{
type: "Point",
properties: {
label_placement: "yes",
kind: "electronics",
name: "Best Buy",
area: 6595,
landuse_kind: "retail",
addr_street: "Harrison Street",
addr_housenumber: "1717",
id: 25821942
},
coordinates: [
877,
933
]
},
```

**Comment by zerebubuth** [comment]
* Missing California Academy of Sciences in SF: #371
* InterContinental Hotel Mark Hopkins & The Fairmont San Francisco Hotel: #372.
* Grace Cathedral: #373
* Best Buy: #374

**Comment by nvkelso** [comment]
Added the above issues to v0.6.x milestone and marking this send to prod.
