### ISSUE TITLE
Reenable simplification for OSM in low zooms

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#270]

**Comment by zerebubuth** [comment]
What's the background here? Are there particular areas / layers which aren't being simplified?

**Comment by rmarianski** [comment]
Did we move some osm data to earlier zoom levels, but aren't simplifying those because it's not configured to do so?

**Comment by zerebubuth** [comment]
Do we want to simplify all data those zooms, or just OSM at those zooms?

**Comment by nvkelso** [comment]
Sorry, the title is speculation on my part. We're seeing slowdowns in tile generation time at the low zooms and one possible cause is we might not have adjusted all the `simplification_start` settings in queries.yaml to work with moving the NE > OSM transition from 9 to 8. If that's the case, easy fix. If it's not, please open a more general issue (and close this one).

**Comment by zerebubuth** [comment]
Here's a breakdown of our current layers, when they start using OSM data and when they start simplifying. We're not terribly consistent about when we start using OSM, but it appears that we're simplifying whenever we're using it.

* water, earth: starts using OSM at z9, starts simplifying at z9.
* landuse: starts using OSM at z4 for parks, moves over to mostly-OSM at z8, starts simplifying at z4.
* roads, boundaries: starts using OSM at z8, starts simplifying at z8.
* buildings: starts at z13 - always OSM, always simplifies.
* transit: starts at z6 - always OSM, always simplifies.
* pois: starts at z9, they're all points, no generalisation.

**Comment by zerebubuth** [comment]
Looks like this isn't (just?) a simplification issue. Follow up in #280.
