### ISSUE TITLE
show airport runway lines at zoom 9

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#278]
They are coming in as minor roads, which generally don't show until z11 now.

To support Eraser Map style.

**Comment by zerebubuth** [comment]
If these are the runway lines you mean (at z13):

![278-airport-lines-z13](https://cloud.githubusercontent.com/assets/271360/10225283/fc4ec15e-6859-11e5-960c-176f053d8328.png)

I can still see them at z9 (these are prod tiles):

![278-runway-lines](https://cloud.githubusercontent.com/assets/271360/10225289/0a2cab74-685a-11e5-96a1-c348d0a1b28a.png)

Is it possible that there are other lines which aren't runways which are showing up? Could you give an example of runways which aren't showing up but should be, please?

**Comment by nvkelso** [comment]
I believe the orange lines at SFO are actually landuse polygons. In addition, there are runway lines at SFO, but most other airports (like OAK in Oakland across the bay) lack the polygons and only have the lines.

This function sets `runway` lines and `taxiway` lines to show up at the same time (zoom 11):

* https://github.com/mapzen/vector-datasource/blob/master/data/functions.sql#L224

Let's try splitting those apart so the `runway` lines come in at zoom 9 instead (no change for `taxiway` lines).

**Comment by nvkelso** [comment]
Verified.
