### ISSUE TITLE
Order of kind coalesce sometimes funky (and "yes")

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#282]
This feature is a soccer pitch, but is showing up as `kind:university` in tiles:

https://www.openstreetmap.org/way/338698145

* `amenity:university`
* `landuse:grass`
* `sport:soccer`

**Comment by nvkelso** [comment]
We also need to deal with `*=yes` values. See #335.

For instance:

http://vector.dev.mapzen.com/osm/all/18/41885/101371.topojson?api_key=vector-tiles-HqUVidw

```
{
type: "Point",
properties: {
kind: "yes",
id: 3575638173,
name: "Special Education & Communicative Disorders"
},
coordinates: [
252,
94
]
}
]
```

Matt suggests: 

```
3) Pull all the values "aerialway", ... "waterway" back to Python-land and normalise them to a kind there. This is, I think, what we'll end up doing for #282 anyway to have more control over kind selection.
```

**Comment by nvkelso** [comment]
This is coming up again for the Indy's work, scheduled in March

**Comment by rmarianski** [comment]
Do we want to put in the effort for transitioning to an explicit kind calculation for each layer at this point? Or do we want to make a smaller effort here to just transition to a smarter coalesce in python to ensure that we don't get `kind=yes` properties?

I assume the former since based on previous discussions it sounded like this was the eventual goal.

**Comment by nvkelso** [comment]
Tiles meeting: let's pursue the CSV route.

**Comment by rmarianski** [comment]
The implementation will be related to #580.

**Comment by nvkelso** [comment]
Another example for Indy's Fitness blog post:

In some tile cut runs this building is `kind:yes`, others it's `kind: fitness_centre`:

* https://www.openstreetmap.org/way/264528016

**Comment by zerebubuth** [comment]
> In some tile cut runs this building is `kind:yes`, others it's `kind: fitness_centre`

If this is displaying non-determinism, then it is a different issue. That building / fitness centre doesn't seem to have been edited recently, and we don't coalesce the `building` value in the `kind` calculation. There is some extra processing for fitness, but it only sets the kind to `fitness`, never `yes`. Likewise, there's some extra processing for buildings, but these explicitly avoid setting `kind: yes`.

Currently, I'm seeing `kind: fitness` on both dev and prod - if anyone sees a different value for this feature, please file a new bug with the full GeoJSON/TopoJSON tile attached!

**Comment by nvkelso** [comment]
Moving the fitness building discussion to: https://github.com/mapzen/vector-datasource/issues/589.

**Comment by nvkelso** [comment]
Both examples are fixed. Verified visually and in tiles.
