### ISSUE TITLE
missing Golden Gate Park in SF

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#283]
Using the same scene file

* pointed towards `prod` I see a green polygon render for Golden Gate park. 
* pointed towards `dev` I don't see the required polygon

Interestingly, I also don't see the label.

<img width="754" alt="screen shot 2015-10-01 at 22 24 13" src="https://cloud.githubusercontent.com/assets/853051/10240037/d0782ea8-688b-11e5-81c6-f526675680c9.png">

<img width="818" alt="screen shot 2015-10-01 at 22 23 55" src="https://cloud.githubusercontent.com/assets/853051/10240036/d077f6c2-688b-11e5-8a51-5b326995802a.png">

**Comment by zerebubuth** [comment]
Looks like we had a migration hiccup, resulting in Golden Gate park having `mz_is_landuse=NULL` and `mz_landuse_min_zoom=NULL`, so it wasn't displaying. I've manually set this to its usual values (`TRUE`, `9`), but we might want to re-run `apply-planet_osm_polygon.sql` at the next convenient opportunity to ensure there aren't other examples lurking.

**Comment by nvkelso** [comment]
Verified SF Golden Gate Park is back. Not sure where else to verify this.
