### ISSUE TITLE
Shouldn't see state boundary around indian reservation

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#284]
8/40.982/-122.195

<img width="555" alt="screen shot 2015-10-01 at 22 44 03" src="https://cloud.githubusercontent.com/assets/853051/10240215/ffad53b8-688d-11e5-8614-4f86afc3d414.png">

**Comment by zerebubuth** [comment]
Related to #214.

**Comment by zerebubuth** [comment]
Should be fixed by mapzen/TileStache#66 and #286.

**Comment by nvkelso** [comment]
Verified.
