### ISSUE TITLE
Error when calling orient on a multipolygon

### ISSUE THREAD

**Issue by rmarianski** [mapzen/vector-datasource#288]
Seeing an error from shapely when calling [orient](https://github.com/mapzen/TileStache/blob/2420aca942e3203910a041113bbda427791d298e/TileStache/Goodies/VecTiles/transform.py#L1402) on a multipolygon.

line 334, in orient    ring = polygon.exterior | AttributeError: 'MultiPolygon' object has no attribute 'exterior'

We're using Shapely==1.4.3 at the moment.

**Comment by rmarianski** [comment]
Confirmed the same behavior with Shapely 1.5.12

**Comment by nvkelso** [comment]
Blocks #210 from going to prod.

**Comment by nvkelso** [comment]
Opening this back up so it appears in the correct status column.
