### ISSUE TITLE
ocean water missing from dev

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#290]
<img width="909" alt="screen shot 2015-10-03 at 14 52 51" src="https://cloud.githubusercontent.com/assets/853051/10265328/b79780bc-69e1-11e5-9c35-1f22be666d4d.png">

<img width="1315" alt="screen shot 2015-10-03 at 14 52 14" src="https://cloud.githubusercontent.com/assets/853051/10265330/b7bd4ee6-69e1-11e5-8303-9b33f021e111.png">

<img width="993" alt="screen shot 2015-10-03 at 14 48 44" src="https://cloud.githubusercontent.com/assets/853051/10265329/b7bd531e-69e1-11e5-9461-cad52229ae2c.png">

**Comment by nvkelso** [comment]
An example that's not ocean water (Lake Sonoma north of SF):

http://vector.mapzen.com/osm/all/13/1296/3138.topojson?api_key=vector-tiles-HqUVidw

http://vector.dev.mapzen.com/osm/all/13/1296/3138.topojson?api_key=vector-tiles-HqUVidw

**Comment by nvkelso** [comment]
Even weirder:

<img width="1123" alt="screen shot 2015-10-03 at 16 56 50" src="https://cloud.githubusercontent.com/assets/853051/10265679/cd245ff0-69ef-11e5-88b7-de7fb6054d12.png">

**Comment by zerebubuth** [comment]
Related to #293, will see if it's fixed by @rmarianski  in mapzen/TileStache#68.
