### ISSUE TITLE
Suppress "historical" feature label_position until zoom 17+

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#291]
#15/37.7697/-122.1435
https://www.openstreetmap.org/edit?#map=16/37.7693/-122.1452
https://www.openstreetmap.org/relation/317369

Sometimes these are points, sometimes they're landuse AOIs. We should still show the AOI, but the label shouldn't show until zoom 17+ (was z15+, revised recommendation 13 Jan 2016).

<img width="305" alt="screen shot 2015-10-03 at 15 21 06" src="https://cloud.githubusercontent.com/assets/853051/10265372/abd754a4-69e2-11e5-8108-7dd85eef517c.png">

<img width="477" alt="screen shot 2015-10-03 at 15 20 56" src="https://cloud.githubusercontent.com/assets/853051/10265374/abf6f566-69e2-11e5-96d0-ae0a5a855cda.png">

**Comment by nvkelso** [comment]
Related: #267.

**Comment by zerebubuth** [comment]
A couple of questions:

1. How do we want to identify these? Looking in the North America extract, there are 49,437 points and 146 polygons with `name ILIKE '% (historical)'`. Do we want to suppress all of those, or only some of them? See below for more detail.
2. The example given, "[Naval Hospital Oakland](https://en.wikipedia.org/wiki/Naval_Hospital_Oakland)" seems like it's not just historical, but in fact no longer a hospital at all. Would this instance perhaps be better dealt with by removing `amenity=hospital` from the source data? If so, is that something we could or should apply more generally?

### Historical stuff

For the polygons, the top counts of `kind` (plus "building" when it's a building but no matching kind - usually means it has a `disused:amenity` tag or similar - [e.g](http://www.openstreetmap.org/way/346638999)):

```
        kind         | num 
---------------------+-----
 building            |  49
 school              |  41
 place_of_worship    |  14
 water               |  13
```

And the top values for points:

```
          kind           |  num  
-------------------------+-------
 school                  | 35068
 post_office             |  6262
 place_of_worship        |  6186
 hospital                |   371
 grave_yard              |   191
 park                    |   178
```

The reason there are so many more points than polygons is that many of these features came from the GNIS import and have never been touched or verified.

**Comment by nvkelso** [comment]
Your frequency list match what I've seen on the map. 

> 1) How do we want to identify these? Looking in the North America extract, there are 49,437 points and 146 polygons with name ILIKE '% (historical)'. Do we want to suppress all of those, or only some of them? See below for more detail.

Using the basic `ILIKE '% (historical)'` filter sounds good. Like you said, these are mostly GNIS points so keeping it simple like this is fine. Updating for the v0.8 meta tiling change – Include them at z16 but mark them `min_zoom:17`. I think we can use the same approach for points and polygons (there are so few of them).

> 2) The example given, "Naval Hospital Oakland" seems like it's not just historical, but in fact no longer a hospital at all. Would this instance perhaps be better dealt with by removing amenity=hospital from the source data? If so, is that something we could or should apply more generally?

Good suggestion. What would the `kind` end up being in this case and in general (especially if there were no other tags to fall back to)?

**Comment by zerebubuth** [comment]
>  What would the kind end up being in this case and in general (especially if there were no other tags to fall back to)?

We could rewrite the kind to be `historical` and remove the `(historical)` from the name? We already keep a few disambiguation tags around, so the type of whatever it was that it used to be can probably still be inferred... If not, we could always add `historical: <old value of kind>`?

From a cartographic point of view, is the "historical" name a bit like a building name - it's kinda useful, but you wouldn't want it to look like a _current_ POI? Would it be useful to, for example, display a greyed out or crossed-through hospital symbol for the old naval hospital? Or better just to display a text label only?

**Comment by nvkelso** [comment]
We'd display these with a generic dot icon only. I'm fine with `kind:historical` alone. 

Let's pass on removing the ` (historical)` part from the name, and from adding `historical: <old value of kind>` for now. Both seem potentially useful, but could be argued either way.

**Comment by nvkelso** [comment]
Verified the POI layer fix.

<img width="410" alt="screen shot 2016-03-17 at 16 59 22" src="https://cloud.githubusercontent.com/assets/853051/13864787/c3398282-ec61-11e5-9324-cd4b9101dfa1.png">

Looks like the hospital AOI still comes thru the landuse layer (the light red background color in the image above). Filed https://github.com/mapzen/vector-datasource/issues/617. Recapping Matt's findings above:

```
Looking in the North America extract, there are 
49,437 points and 
146 polygons 
with name ILIKE '% (historical)'.
```

The remaining polygons are a 1% problem, and it's probably better to fix their data tags upstream in OSM than write more code here.
