### ISSUE TITLE
Add shop=laundry to POIs

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#292]
My neighborhood dry cleaner is on the map, but the [laundromat](https://www.openstreetmap.org/node/3204993507)  is missing. Should probably come in at zoom 17 by default.

http://wiki.openstreetmap.org/wiki/Tag:shop=laundry

**Comment by zerebubuth** [comment]
With #322:

## Before

![san_francisco_z18_before](https://cloud.githubusercontent.com/assets/271360/10645193/60262d6e-7824-11e5-92bb-b4ec2fe3a939.jpg)

## After

![san_francisco_z18_after](https://cloud.githubusercontent.com/assets/271360/10645194/65484a34-7824-11e5-8e2d-b75cde90cd81.jpg)

**Comment by nvkelso** [comment]
Verified.
