### ISSUE TITLE
Investigate reducing the data payload from the database

### ISSUE THREAD

**Issue by rmarianski** [mapzen/vector-datasource#302]
We're retrieving the raw geometries from the database for all features. We will want to revisit this for certain types of features, like boundaries. Note that it could be that another layer is responsible for the payload size here, I'm just guessing that it's boundaries.

**Comment by zerebubuth** [comment]
There are two layers where we're going geometry matching requiring original, non-simplified geometry for it to work; boundaries and water polygons. Thinking about it a little more, the water ones would probably be okay with simplified boundaries, but it might increase the incidence of those "dashing" artefacts near overlapping polygons.

For the boundaries; at the moment, we just filter on `boundary='administrative'`. Might it be worth reducing that to `boundary='administrative' and admin_level in ('2', '4')` for the general case, allowing `'8'` for `zoom >` whatever zoom we want county boundaries for?

**Comment by zerebubuth** [comment]
Also, `buffered_land` is a set of very large polygons. We should try chopping that up into a series of unioned blocks so that inland intersections don't pull in the whole coastline.

**Comment by nvkelso** [comment]
Cane do more clipping (versus simplification)?
