### ISSUE TITLE
Add amenity=ferry_terminal to POIs

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#309]
We're only getting ferry terminals if they are buildings now. We should also get the ferry terminal points.

See: https://www.openstreetmap.org/node/1142601108

**Comment by zerebubuth** [comment]
After #324:

## New York islands, zoom 15

![new_york_islands_z15](https://cloud.githubusercontent.com/assets/271360/10665216/662b48e6-78c1-11e5-8fbe-72ea2afde64b.jpg)

## Disneyland, zoom 18

![disneyland_z18](https://cloud.githubusercontent.com/assets/271360/10665217/67edd1bc-78c1-11e5-8280-361cf351038b.jpg)

**Comment by nvkelso** [comment]
Nice, and Disney Jungle Cruise! Will have a closer look once it's in dev.

**Comment by nvkelso** [comment]
Verified.
