### ISSUE TITLE
Water-polygons don‘t close porperly in mapbox Studio

### ISSUE THREAD

**Issue by g12n** [mapzen/vector-datasource#310]
When using the Mapzen Source in Mapbox Studio, the water-features break at the tile edges:

![bildschirmfoto 2015-10-15 um 16 46 46](https://cloud.githubusercontent.com/assets/57556/10517327/946c08c2-735c-11e5-8e2d-de4d1a21dcad.png)

You find the source of my Style here: 
https://github.com/g12n/mapzen-slate.tm2

I use http://vector.mapzen.com/osm/tilejson/mapbox.json to import the layers

**Comment by nvkelso** [comment]
Add a selector for 
boundary not equal to yes

**Comment by zerebubuth** [comment]
For example, as described in https://github.com/mapbox/mapbox-gl-js/issues/1576#issuecomment-145044891.

**Comment by g12n** [comment]
Yeah! Exactly. 
Thank you for the pointing me into the right direction. 
I don't know if there is a way directly in carto to filter by type, but I was able to use the area-property:

I changed the selector for the water: 

```
#water {
  [area>0]{
     polygon-fill: @water;
  }
}
```

looks like a hack though ;-)

**Comment by g12n** [comment]
By the way: is http://vector.mapzen.com/osm/tilejson/mapbox.json still the proper way to integrate the source to Mapbox-Studio. Looks like this doesn't pass the API-Key to the request.

**Comment by rmarianski** [comment]
> By the way: is http://vector.mapzen.com/osm/tilejson/mapbox.json still the proper way to integrate the source to Mapbox-Studio. Looks like this doesn't pass the API-Key to the request.

It is the proper way, yes. That doesn't affect the request processing behavior and the api key is indeed getting passed through.

Would it be clearer to update the tiles url to be the following?

`http://vector.mapzen.com/osm/all/{z}/{x}/{y}.mvt?api_key={api_key}`

**Comment by g12n** [comment]
> Would it be clearer to update the tiles url to be the following?

I guess yes. We though get off track the scope if this Issue – which can be closed i guess! Thanks guys for the quick help!
