### ISSUE TITLE
Update High Road classifier (zoom, sort) for `service` and other types

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#332]
1. In [adding `service` key/values](https://github.com/mapzen/vector-datasource/issues/308) to roads and railroads, it turns out not all of these features are made equal and we should mod the High Road logic for minimum zoom and sort. 
2. Additionally, we're missing road detail until zoom 15, we should promote a few other "road" features to be viewed earlier.

# 1. SERVICE class on roads and rail

**Minimum zoom** is controlled here: https://github.com/mapzen/vector-datasource/blob/master/data/functions.sql#L239-L258

**Sort key** is in the TileStache transform logic: * https://github.com/mapzen/TileStache/blob/integration-1/TileStache/Goodies/VecTiles/transform.py#L236-L266

**Railroad values:**

* **general rail** (no additional `service` tag): zoom 11 (from 14 now)
* **spur:** zoom 12 (sort under general rail)
* **siding:** zoom 12  (sort under general rail)
* **yard:** zoom 13  (sort under spur/siding rail)
* **crossover:** zoom 14  (sort under yard rail)

**Road values:**

Looks like we're not seeing `service` roads until zoom 15 now, but that's too late for alley in SF where it looks like part of the street grid is missing at zoom 14. 

* **general service road** (no additional `service` tag): zoom 14 (from 15 now)
* **alley:** zoom 13 (sort same as service roads)
* **driveway:** zoom 15  (sort same under service roads)
* **parking_aisle:** zoom 15.  (sort same under service roads) _See: 18/37.72641/-122.45444 in SF._
* **drive-through:** zoom 15  (sort same under service roads)

_(below) SF at zoom 14 (missing alleys):_

![screen shot 2015-10-23 at 15 26 13](https://cloud.githubusercontent.com/assets/853051/10706275/6d995206-799a-11e5-9dee-1a0326ac6d7d.png)

# 2. Other non-SERVICE related changes

For Barcelona it looks like we're including pedestrian, living_street too late, and minor roads are being displayed too late (like `track`, making it hard to browse forested areas). See full [`highway=*` on the OSM wiki](https://wiki.openstreetmap.org/wiki/Key:highway).

For SF area we're missing paths at zoom 14 that are important for understanding large parks.

```
WHEN highway_val IN ('primary_link', 'secondary_link') THEN 13
             WHEN (highway_val IN ('tertiary_link', 'minor')
                OR railway_val='rail') THEN 14
             WHEN (highway_val IN ('service', 'footpath', 'track', 'footway', 'steps', 'pedestrian', 'path', 'cycleway', 'living_street')
                OR railway_val IN ('tram', 'light_rail', 'narrow_gauge', 'monorail')) THEN 15
```

Should probably read something more like:

```
WHEN (highway_val IN ('tertiary')
                OR aeroway_val IN ('taxiway')
                OR railway_val IN ('rail')) THEN 11
```
...
```
WHEN highway_val IN ('primary_link', 'secondary_link', 'track', 'pedestrian', 'living_street') THEN 13
             WHEN (highway_val IN ('tertiary_link', 'minor', 'service', 'footpath', 'track', 'footway', 'steps', 'path', 'cycleway',) THEN 14
             WHEN railway_val IN ('tram', 'light_rail', 'narrow_gauge', 'monorail')) THEN 15
```

See also:

* https://github.com/mapzen/vector-datasource/blob/master/data/functions.sql#L252-L253
* https://www.openstreetmap.org/#map=14/41.3813/2.1777

![screen shot 2015-10-23 at 15 54 51](https://cloud.githubusercontent.com/assets/853051/10706742/6fc5e6da-799e-11e5-96ff-6b1e6cbd02bd.png)

![screen shot 2015-10-23 at 16 34 50](https://cloud.githubusercontent.com/assets/853051/10707211/00bd3184-79a4-11e5-9c8b-b0c7b5579a0d.png)

**Comment by nvkelso** [comment]
Maybe the `highway=service`, and `service=alley`roads in SF need another solution, thoughts @zerebubuth ?

**Comment by zerebubuth** [comment]
After mapzen/TileStache#78 and #336 and some minor style changes to make paths visible at zoom 14:

## Alleys

![sf_z14_after](https://cloud.githubusercontent.com/assets/271360/10732755/6b2f8818-7bf3-11e5-9596-fa793b704aae.jpg)

## Paths in parks

![sf3_z14_after](https://cloud.githubusercontent.com/assets/271360/10732767/7a4dc2ec-7bf3-11e5-8a30-66e1818c427d.jpg)

**Comment by nvkelso** [comment]
LGTM.

**Comment by nvkelso** [comment]
Looking good.
