### ISSUE TITLE
Missing the sort_order on landuse labels

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#334]
http://vector.dev.mapzen.com/osm/all/15/5235/12671.topojson?api_key=vector-tiles-HqUVidw

http://vector.mapzen.com/osm/all/15/5235/12671.topojson?api_key=vector-tiles-HqUVidw

```
landuse_labels: {
type: "GeometryCollection",
geometries: [
{
type: "Point",
properties: {
name:fa: "دانشگاه ایالتی سان فرانسیسکو",
kind: "university",
name: "San Francisco State University",
area: 1003630,
sort_key: 4,
name:pt: "Universidade Estadual de São Francisco",
label_placement: "yes",
source: "openstreetmap.org",
name:fr: "Université d'État de San Francisco",
name:ru: "Университет штата в Сан-Франциско",
min_zoom: 9,
id: 28965902,
name:es: "Universidad Estatal de San Francisco"
},
coordinates: [
613,
698
]
```

The new version on `dev` is missing the `sort_key`.

**Comment by zerebubuth** [comment]
Looks like this is because we de-duped a bunch of stuff and now (after #201), the university is ending up in the POIs layer instead. This seems right to me, but we don't have a [sort order](https://github.com/mapzen/TileStache/blob/fba1168fe202a71971cc84e29d7a741fd3d6aed6/TileStache/Goodies/VecTiles/transform.py#L1086-L1116) like we do for landuse. 

Here's a list of the [top 100 kinds](https://github.com/mapzen/vector-datasource/files/23335/kinds.txt) of POIs. @nvkelso, can we make a `sort_key` lookup like we have for landuse? What should it look like to begin with?

**Comment by nvkelso** [comment]
@zerebubuth When we dedup do we merge property key/values from the looser onto the winner? Should we? We started talking about this (for `area`) in https://github.com/mapzen/vector-datasource/issues/348.

Inventing new sort order for POIs seems like a separate chunk of work (and we should research it's utility in Tangram), tracking that with new https://github.com/mapzen/vector-datasource/issues/360.

**Comment by zerebubuth** [comment]
We don't, currently. At the moment, the most important feature is left as-is, and any less important ones are simply removed.

Merging feels like it could be quite a minefield. For example, if we needed to merge a less important item with a secondary tag onto a more important one of a different kind, do we merge that? Do we have a whitelist of "universal" tags like `area`, `name:*`?

For the sake of something more concrete, imagine that there's a school POI with `kind=school` and we merge that with a nearby playing field of the same name `kind=pitch, sport=baseball`, we presumably don't want to merge that to get `kind=school, sport=baseball` - that's just confusing.

Some tags we might want to merge in other ways. For example; the sport example, we might want to merge adjacent tennis courts and baseball pitches as `sport=[tennis,baseball]`, but we might want to merge adjacent polygonal features such as buildings or parks by summing their `area` (and `volume`) to reflect that they represent more than one feature. In that case, we'd have to be careful; it's easy to imagine that a merged feature at zoom N with area A+B might pass client-side filters, whereas at zoom N+1 they might not reach the server-side threshold for merging and A, B by themselves might fail the client-side filters and disappear, only perhaps to reappear at the next zoom level.

It seems to me that merging is pretty hard, and perhaps we should think a bit more about all the possible corner cases before attempting it.

**Comment by nvkelso** [comment]
Getting proper areas for POIs is covered over: https://github.com/mapzen/vector-datasource/issues/348.

**Comment by nvkelso** [comment]
Process changed.
