### ISSUE TITLE
Indicate station type (subway, rail, light rail, etc)

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#352]
Right now we're setting `kind=station` but not indicating what type of station it is (eg: subway, rail, light rail, etc). 

To set a more appropriate icon in the stylesheet, we need to know what transport type(s) serve the station.

**Comment by zerebubuth** [comment]
Would you prefer:

1. `kind=station`, `kind=subway_station`, `kind=light_rail_station`, etc...
2. `kind=station`, `kind=station_subway`, `kind=station_light_rail`, etc...
3. `kind=station` an additional tag `rail_kind=mainline`, `rail_kind=subway`, `rail_kind=light_rail`, etc...

Or some other option?

It's important to note that this data is _very_ patchy in OSM (e.g: most of the NYC subway stations I looked at on Manhattan aren't tagged with a sub-type), so it might be of little value when styling.

**Comment by nvkelso** [comment]
Dang, that is [_really_ sparse](http://taginfo.openstreetmap.org/keys/?key=station#values). 

Is there a 4th option for including `station=*` when it's in the following list?

* subway
* light_rail

**Comment by zerebubuth** [comment]
Sure. Does that mean you want option 3, but with the whitelist on `station`?

**Comment by nvkelso** [comment]
Yes: `kind=station` with an optional `station` tag (whitelisted) for `subway` and `light_rail`, when present on the input data.

This way we won't see regressions (features already tagged `kind=station` but also `station=subway` wouldn't disappear from the map / turn into a generic icon like if we went with options 1 or 2). There is opportunity to make breaking changes in v1.0 later.

**Comment by nvkelso** [comment]
Related: we're not indicating that the station type is derived from aerialway instead of railway here: 
https://www.openstreetmap.org/way/313300141

And the data doesn't indicate directly that the station in the San Francisco Zoo is on a miniature railway.

**Comment by nvkelso** [comment]
With #506 we now have booleans for the different transit types.

**Comment by nvkelso** [comment]
Looks good in London, 15/51.5149/-0.0804:

<img width="421" alt="screen shot 2016-03-24 at 02 10 30" src="https://cloud.githubusercontent.com/assets/853051/14012826/a697679e-f165-11e5-9096-8d851afe1d97.png">
