### ISSUE TITLE
Sql error with mz_building_filter

### ISSUE THREAD

**Issue by rmarianski** [mapzen/vector-datasource#361]
Error fetching: 13/4447/2879 - Traceback (most recent call last): |   File "/usr/local/lib/python2.7/dist-packages/tilequeue/worker.py", line 132, in __call__    fetch_data = self.fetcher(coord) |   File "/usr/local/lib/python2.7/dist-packages/tilequeue/query.py", line 187, in __call__    raise async_exception | DataError: invalid input syntax for integer: "2.5"CONTEXT:  PL/pgSQL function mz_building_filter(text,text,double precision,double precision,double precision) line 3 at RETURN

**Comment by nvkelso** [comment]
@rmarianski  isn't seeing this error in the logs anymore.
