### ISSUE TITLE
Missing landuse=military AOIs

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#367]
The Old Soldiers Home in DC (15/38.9403/-77.0123) is `landuse=military` in OSM but it's missing from tiles:

http://vector.dev.mapzen.com/osm/all/17/37496/50121.topojson?api_key=vector-tiles-HqUVidw
http://vector.mapzen.com/osm/all/17/37496/50121.topojson?api_key=vector-tiles-HqUVidw

Looking at the queries it seems to be selecting correctly? Where else in the processing could it be dropped?

<img width="915" alt="screen shot 2015-11-02 at 21 13 37" src="https://cloud.githubusercontent.com/assets/853051/10901671/83bd1ee0-81a7-11e5-89fa-d1a8b12cfbae.png">

**Comment by nvkelso** [comment]
Related the the missing `school` labels (https://github.com/mapzen/vector-datasource/issues/417), we're missing a whole swath of military features that are just points:

https://taginfo.openstreetmap.org/keys/military

![screen shot 2015-12-04 at 09 46 57](https://cloud.githubusercontent.com/assets/853051/11596788/1af554ee-9a6c-11e5-9fb6-598e92e44239.png)

**Comment by zerebubuth** [comment]
Before:

![us-soldiers-and-airmens-home-z15-before](https://cloud.githubusercontent.com/assets/271360/11722317/fa7cb542-9f5f-11e5-8322-12f6accceb51.jpg)

After:

![us-soldiers-and-airmens-home-z15-after](https://cloud.githubusercontent.com/assets/271360/11722323/00a6b454-9f60-11e5-823c-0991e5fc5bd9.jpg)

**Comment by nvkelso** [comment]
Verified in SF Bay Area and Washington DC areas.
