### ISSUE TITLE
Start showing (subway) stations at zoom 12 instead of 13

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#369]
With the changes in https://github.com/mapzen/vector-datasource/issues/368, we have enough signal to consider showing subway stations at zoom 12 (instead of zoom 13+).

**Comment by zerebubuth** [comment]
A selection of stations are now visible at zoom 12, following the changes in #436:

![new-york-city-z12](https://cloud.githubusercontent.com/assets/271360/11716283/9d84b5b6-9f40-11e5-990a-cfa07312a6cf.jpg)

**Comment by nvkelso** [comment]
Looking at this zoom 12 tile in NYC (Wall Street area), I don't see stations? Nor anywhere else on the?
http://vector.dev.mapzen.com/osm/all/12/1205/1540.topojson

**Comment by nvkelso** [comment]
WFM in SF, NYC, and Paris.
