### ISSUE TITLE
Missing California Academy of Sciences in SF

### ISSUE THREAD

**Issue by zerebubuth** [mapzen/vector-datasource#371]
Looks like we're missing the California Academy of Sciences in SF (kind=museum) in dev versus prod.

#17/37.76983/-122.46657
http://vector.dev.mapzen.com/osm/all/17/20947/50664.topojson?api_key=vector-tiles-HqUVidw
http://vector.mapzen.com/osm/all/17/20947/50664.topojson?api_key=vector-tiles-HqUVidw

**Comment by nvkelso** [comment]
This is no longer a problem on either `dev` or `prod`, closing.
