### ISSUE TITLE
Roads on boundary unnecessarily broken up

### ISSUE THREAD

**Issue by zerebubuth** [mapzen/vector-datasource#384]
In tile 19/123424/200482, W 24th St is broken up into 6 individual linestrings, despite there being only 2 original objects. The arcs are [11, 12, 13, 14] in one object. This turns out to be, after un-delta encoding:

```
11: [[813, 635], [674, 522]]
12: [[674, 522], [567, 466]]
13: [[567, 466], [440, 436]]
14: [[440, 436], [314, 412]]
```

So there are no gaps in the line. There might be some really small ones which are being covered up by the quantisation, but the WKT is:

```
MULTILINESTRING (
  (-10603283.9 4713231, -10603294.25 4713222.56),
  (-10603294.25 4713222.56, -10603302.27 4713218.41),
  (-10603302.27 4713218.41, -10603311.73 4713216.12),
  (-10603311.73 4713216.12, -10603321.1 4713214.33))
```

Which would indicate no gaps. So I think this is arguably a bug in how GEOS does its intersection; that at shared nodes it will split the intersection / difference part into a `MULTI*` geometry.

**Comment by zerebubuth** [comment]
After mapzen/TileStache#92, the area in the example looks like (Note that I turned most of the round caps & joins to "butt", so it's probably uglier than it needed to be to demonstrate the point):

![naismith_drive_z20](https://cloud.githubusercontent.com/assets/271360/10947818/4112b934-8322-11e5-9f9b-ead7f78b709f.jpg)

And the geometry in the file for one ID is all in the same single arc:

```json
        {
          "type": "LineString",
          "properties": {
            "kind": "minor_road",
            "name": "W 24th St.",
            "sort_key": 17,
            "landuse_kind": "commercial",
            "source": "openstreetmap",
            "is_link": "no",
            "is_bridge": "no",
            "is_tunnel": "no",
            "id": 13039778,
            "highway": "residential"
          },
          "arcs": [
            10
          ]
        },
```

**Comment by nvkelso** [comment]
Peter reported this, over to him to verify:

* url: '//vector.dev.mapzen.com/osm/all/{z}/{x}/{y}.topojson'

**Comment by meetar** [comment]
:+1:
Before:
<img width="774" alt="screen shot 2015-11-05 at 4 13 03 pm" src="https://cloud.githubusercontent.com/assets/459970/10981873/3ab51fa8-83d8-11e5-85b6-f968d9cf42c1.png">

After:
<img width="779" alt="screen shot 2015-11-05 at 4 13 12 pm" src="https://cloud.githubusercontent.com/assets/459970/10981880/3f41fb90-83d8-11e5-951e-b45f9473d3a5.png">

:100: :white_check_mark: :shipit:
