### ISSUE TITLE
Throttle WOF neighborhood inclusion

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#386]
Something like:

```
"mz:min_zoom" <= {zoom-1} and "mz:max_zoom" >{zoom+1} and "mz:is_funky" NOT IN (1)
```

Normally it would look like:

```
"mz:min_zoom" <= {zoom} and "mz:max_zoom" >{zoom} and "mz:is_funky" NOT IN (1)
```

But we want to include **more** than we'd normally show (earlier, and later).

We don't ever want to put funky things into tiles. Those should be cleaned up on the data side.

**Comment by rmarianski** [comment]
Just verifying, we'll want to honor the max zoom as well in tiles, ie stop showing certain neighbourhoods if the zoom is greater than `mz:max_zoom`?

**Comment by nvkelso** [comment]
Yep. We'll want to show the feature 1 more zoom than recommended in that value, but not after that.

**Comment by rmarianski** [comment]
If the feature is missing min/max zooms, should those be included at all zooms?

**Comment by nvkelso** [comment]
No, it should default to min_zoom of 15 and max_zoom of 18

**Comment by rmarianski** [comment]
Do we only want to include the `is_landuse_aoi` column if it's true? And maybe include it as `is_landuse_aoi=yes` in the tile?

**Comment by nvkelso** [comment]
sounds good

**Comment by nvkelso** [comment]
Working.
