### ISSUE TITLE
city names suddenly have kind "state"

### ISSUE THREAD

**Issue by musicformellons** [mapzen/vector-datasource#397]
I get this:

#9.99/53.3147/-6.1035

![screenshot from 2015-11-06 18-09-03](https://cloud.githubusercontent.com/assets/10334123/11008881/a90bb27c-84d3-11e5-9a00-e78792307624.png)

#9.76/52.3279/5.0113

![screenshot from 2015-11-06 18-09-45](https://cloud.githubusercontent.com/assets/10334123/11008886/af286b6e-84d3-11e5-89eb-e90b9064c70d.png)

It seems to me I did not have these double tags before. When I comment out the State-label layer one of the tags dissappears, so somehow Amsterdam and Dublin (and Istanbul etc.) do have "kind" "state"...

Relevant Mapbox Stylesheet parts:

```
      "id": "state-label",
      "source": "osm",
      "source-layer": "places",
      "filter": ["all", ["==", "$type", "Point"], ["==", "kind", "state"]],
      "minzoom": 6,
      "maxzoom": 12,
```

```
      "id": "city-label",
      "source": "osm",
      "source-layer": "places",
      "filter": ["all", ["==", "$type", "Point"], ["!=", "capital", "yes"], ["in", "kind", "city", "county", "district"]],
      "minzoom": 5,
      "maxzoom": 14,
```

```
      "id": "capitalcity-label",
      "source": "osm",
      "source-layer": "places",
      "filter": ["all", ["==", "$type", "Point"], ["==", "capital", "yes"]],
      "minzoom": 2,
      "maxzoom": 14,
```

**Comment by nvkelso** [comment]
Looking at the tile [9/262/168.topojson](http://vector.mapzen.com/osm/all/9/262/168.topojson?api_key=vector-tiles-HqUVidw) I see two Amsterdam features, one from Natural Earth and one from OSM. In v0.3 of tiles we fixed that problem, but the implementation regressed country and state labels (eliminating them from the map), so that was reverted in the v0.4 tiles in prod that you're using.

There's another ticket covering the fix (to only have a city label in there once, not twice) over at: https://github.com/mapzen/vector-datasource/issues/383. 

If you can confirm this is what you're seeing (duplicate city features, not city & state/region combo), then this issue should be closed in favor of #383.

**Comment by musicformellons** [comment]
Yes, did some checks and probably messed up before..., I can confirm this issue just relates to 'city' and not to 'state' and is caused by OSM & NE city data. 

Another thing I notice is that the relevant data from NE is this JSON part:
"places":{"type":"GeometryCollection","geometries":[{"type":"Point","properties": "labelrank":8,"kind":"Admin-0 capital","scalerank":1,"name":"Amsterdam","source":"naturalearthdata.com","capital":"yes","id":7272,"pop ulation":"1031000"},"coordinates":[1014,713]}

As it contains "source":"naturalearthdata.com" and in my stylesheet I use "source": "osm", I would expect the data not to be picked up. So how come it is shown anyway?

**Comment by nvkelso** [comment]
@musicformellons Hmm. That's confusing. In Tangram we say `sources` to mean which src tile endpoints to aggregate. On individual features we indicate what the `source` is. It may vary in MapBox Studio.

For the layer sources, we aggregate everything into an `osm` grouping layer, even stuff from Natural Earth and Who's On First. That's just unfortunate history, and should really be replaced with something like `v1` to indicate what version of Mapzen vector tile's we're on. 

For the feature's source, try fully qualify your "osm" value to `openstreetmap` instead.

**Comment by musicformellons** [comment]
@nvkelso Mmmh, bit weird, yeah. Behavior I see when making changes in the mapbox gl js stylesheet:
- change "source": "osm" into "source": "openstreetmap"  (or openstreetmap.org or naturalearthdata.com) => no map/ not allowed.
- leave out "source": "osm" completely => no map/ not allowed.

My findings/ conclusions: 
1) the "source" field as used in the Mapzen topoJSON tile (openstreetmap/ openstreetmap.org/ naturalearthdata.com) is not required in the mapbox gl js stylesheet.
2) the Mapzen grouping layer ("osm") is required in Mapbox gl js stylesheet. It is referenced as "source": "osm".

Why both NE&OSM are coming through in my map is clear to me now. How exactly the "grouping layer" ("osm") is transferred/ served is not clear to me; it is not included in the Mapzen JSON data.

**Comment by nvkelso** [comment]
@musicformellons Try changing source to `places` in your MB GL stylesheet and you'll probably get back just country, region, city, and neighbourhood points? 

The `osm` source in Mapzen vector tiles is a shortcut for saying "give me all of the layers you have", one of which is the `places` layer.

Then try adding a filter like:

      "filter": ["all", ["==", "$type", "Point"], ["==", "source", "openstreetmap"]],

**Comment by musicformellons** [comment]
@nvkelso Thanks for suggestions. Replacing "osm" by "places" I can not get to work (I think you should then just delete "source-layer", but does not work). Continuing with "osm" and your filter works, and more in general I can filter on the topoJSON source. 

As cities I do want to have included are filtered then as well I do have to wait for a solution on the #383 ticket. That's ok. Thanks.

**Comment by nvkelso** [comment]
Closing this bug as #383 tracks the required tiles work.
