### ISSUE TITLE
Export flight codes on airports

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#398]
For example, `SFO` for "San Francisco International Airport". This will allow labeling at mid zooms where the full name is too long / distracting.

**Comment by nvkelso** [comment]
(Not the longer airport codes, the ones for commercial airports.)

**Comment by zerebubuth** [comment]
After #438, mapzen/TileStache#103 and changing the `text_source` for the `early` airport rule to `iata` instead of `ref`, it now shows:

![sfo-z11](https://cloud.githubusercontent.com/assets/271360/11721685/f0f4f726-9f5c-11e5-8f58-c52ebd4daa9a.jpg)

**Comment by zerebubuth** [comment]
Not sure why Oakland's "OAK" label isn't showing, but it definitely has `iata: OAK` as part of the props, and "NUQ" (a.k.a Moffett Federal Airfield) is showing near Mountain View.

**Comment by nvkelso** [comment]
I remember OAK is on a tile boundary and JS Tangram (WebGL) has issues with
placing text along those lines.

**Comment by nvkelso** [comment]
Verified in SF Bay Area, NYC, Paris.
