### ISSUE TITLE
Add island labels

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#399]
**earth layer** label positions:

* place=**island** Identifies the coastline of an island (> 1 km2), also consider place=islet for very small islands. zoom 14 default, area adjusted up to zoom 9
* place=**islet** Identifies an islet (< 1 km2). zoom 16 default, area adjusted up to zoom 15.
* place=**archipelago** {Relation} Identifies the relation of an archipelago, which contains several islands and islets. zoom 14 default, area adjusted up to zoom 9

===

These islands of southern California have names, but we don't include them yet:

z10/33.9060/-119.9944

![screen shot 2015-11-09 at 10 39 54](https://cloud.githubusercontent.com/assets/853051/11042840/507bcb5e-86ce-11e5-99cc-c187fb41f781.png)

Looks like the related tag is:

http://wiki.openstreetmap.org/wiki/Tag:place=island

But sometimes it's hiding on relation parts, fun.

**Comment by nvkelso** [comment]
Looks like these would also be useful:

* place=**archipelago**	Relation	Identifies the relation of an archipelago, which contains several islands and islets.		
* place=**island**	Area	Identifies the coastline of an island (> 1 km2), also consider place=islet for very small islands		
* place=**islet**	Node Area	Identifies an islet (< 1 km2).

**Comment by nvkelso** [comment]
Target layer: `physical-labels` or `earth` or `places`, tbd.

**Comment by nvkelso** [comment]
Load balancing to v0.8

**Comment by rmarianski** [comment]
Is that what's happening in this case? Seems like it's coming through in the tile in the `boundaries` layer. This looks to be the relevant [osm feature](http://www.openstreetmap.org/relation/3636334).

Can certainly add the `place`s you mentioned, just don't think it'll help with this example, unless I'm missing something.

**Comment by rmarianski** [comment]
Err sorry, I see it in the `landuse` layer. An example tile is: [10/171/409](http://vector.mapzen.com/osm/all/10/171/409.topojson).

**Comment by nvkelso** [comment]
Other candidates, from http://taginfo.openstreetmap.org/tags/natural=strait:

* natural=peninsula
* natural=headland
* natural=cape
* natural=isthmus

**Comment by nvkelso** [comment]
That feature is the national park, this is the (generic) island, tagged `place=island`:

* http://www.openstreetmap.org/relation/237600#map=12/34.0184/-119.7252

Distraction: The one you mention seems to have gotten corrupted somewhere (either in OSM or in our processing), the name of the "county" is not Santa Cruz Island!

**Comment by nvkelso** [comment]
@rmarianski I'd like to reprioritize adding island labels until later in the milestone. If this safe to move into the backlog or do you have partial code for it now?

**Comment by rmarianski** [comment]
De-prioritizing sounds good. The actual code change was minimal.

**Comment by nvkelso** [comment]
Related: https://github.com/mapzen/vector-datasource/issues/656

**Comment by nvkelso** [comment]
We're getting multiple island labels per feature part for each child tile:

**10/33.9741/-119.8279**
<img width="862" alt="screen shot 2016-04-30 at 07 16 32" src="https://cloud.githubusercontent.com/assets/853051/14934025/8d6bca98-0ea3-11e6-9419-34df576eb888.png">

**13/37.8595/-122.4186**
<img width="364" alt="screen shot 2016-04-30 at 07 13 20" src="https://cloud.githubusercontent.com/assets/853051/14934012/13bb2c52-0ea3-11e6-9578-f81dc1724106.png">

**14/37.8147/-122.3811**
<img width="456" alt="screen shot 2016-04-30 at 07 12 27" src="https://cloud.githubusercontent.com/assets/853051/14934011/13bb19ba-0ea3-11e6-92d4-219be1f4ed3e.png">

**Comment by zerebubuth** [comment]
Ooops, yeah. Looks like we need to pre-calculate centroids and split off the `label_placement: yes` points from the polygons.

**Comment by nvkelso** [comment]
@rmarianski can you finish this off, please? I'm fading with jet lag.

If I remove `label_position: yes` from the output for `islands`, `islets`, and `archipelago`, then that fixes the multiple points per feature problem, but then **all the node tests fail**. As Matt suggests, we need to select the points separate from the polygons. 

Additionally, these 2 polygon tests fail, likely because the resulting point is in a neighboring tile and the test just needs to be updated.

```
# LARGE island labels (from place polygons)
# http://www.openstreetmap.org/relation/4227580
# Manitoulin Island, Canada
# assert_has_feature(
#     7, 34, 45, 'earth',
#     { 'kind': 'island', 'label_placement': 'yes', 'name': 'Manitoulin Island' })

# LARGE island labels (from place polygons)
# http://www.openstreetmap.org/relation/5176042
# Trinidad, the island of the nation
# assert_has_feature(
#     7, 42, 60, 'earth',
#     { 'kind': 'island', 'label_placement': 'yes', 'name': 'Trinidad' })
```

**Comment by nvkelso** [comment]
Working for me :)

<img width="650" alt="screen shot 2016-05-04 at 09 21 08" src="https://cloud.githubusercontent.com/assets/853051/15021080/ae609024-11d9-11e6-9eb1-c0a577ab2d53.png">
<img width="641" alt="screen shot 2016-05-04 at 09 20 15" src="https://cloud.githubusercontent.com/assets/853051/15021082/ae632ae6-11d9-11e6-8bef-80537b1b0277.png">
<img width="347" alt="screen shot 2016-05-04 at 09 20 04" src="https://cloud.githubusercontent.com/assets/853051/15021081/ae60d14c-11d9-11e6-84b6-7eba95792dce.png">
<img width="965" alt="screen shot 2016-05-04 at 09 19 59" src="https://cloud.githubusercontent.com/assets/853051/15021078/ae5fb00a-11d9-11e6-8daa-5523f9bc8c5f.png">
<img width="886" alt="screen shot 2016-05-04 at 09 19 30" src="https://cloud.githubusercontent.com/assets/853051/15021079/ae6092ea-11d9-11e6-8c22-aad83dedb8f7.png">
