### ISSUE TITLE
Newly marked is_funky neighborhoods not removed from map

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#403]
I edited 3 neighbourhoods to be `is_funky:1` in WOF along with ~100 other updates. All the other updates–adjusting their label lat/lng–are live in dev tiles now (good), but those 3 neighbourhoods are still on the map (sad). I suspect the import script is skipping the `is_funky` features outright instead of looking to see if they are already loaded in the DB and also pruning them.

* Central Richmond [85844431](https://whosonfirst.mapzen.com/spelunker/id/85844431/)
* Central Sunset [85851557](https://whosonfirst.mapzen.com/spelunker/id/85851557/)
* Bayview [85865995](https://whosonfirst.mapzen.com/spelunker/id/85865995/)

![screen shot 2015-11-11 at 08 14 28](https://cloud.githubusercontent.com/assets/853051/11096019/d2136ba2-884c-11e5-99e8-92218b79f6d6.png)

**Comment by bcamper** [comment]
Is that the technical term?

**Comment by nvkelso** [comment]
Commoditizing technical mapping terms into everyday English since... ;)

**Comment by nvkelso** [comment]
See also: https://github.com/mapzen/vector-datasource/issues/393 /cc @zerebubuth
