### ISSUE TITLE
Add shop=toys to POIs

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#404]
Visibility something close to:

      WHEN shop_val     = 'dry_cleaning'     THEN LEAST(zoom + 4.90, 17)

For instance, the LEGO Store in NYC:

* https://www.openstreetmap.org/node/3810578539
* https://vector.mapzen.com/osm/all/18/77194/98533.json

**Comment by zerebubuth** [comment]
After #437, now seeing this:

![404-toys-not-found](https://cloud.githubusercontent.com/assets/271360/11716603/e1179e9a-9f42-11e5-878e-8316c366f92d.jpg)

**Comment by nvkelso** [comment]
I see a new address feature in the `buildings` layer for the LEGO store in tiles (good), but I don't see a new POI for the same in the `pois` layer (?).

http://vector.dev.mapzen.com/osm/all/19/154388/197066.topojson

**Comment by zerebubuth** [comment]
Argh, fail. The migration missed this out - I'm running another one.

**Comment by nvkelso** [comment]
Verified: #17/40.74178/-73.98937 in NYC and several places in SF :)

**Comment by nvkelso** [comment]
@sensescape We'll need new icon for Toy stores.

**Comment by nvkelso** [comment]
SF: /#19/37.75156/-122.42826
