### ISSUE TITLE
MVT tiles draw splotchy on dev v0.5-pre

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#406]
All over NYC and elsewhere, when I set the source to be dev in Eraser Map scene file I get:

/cc @rmarianski @bcamper @sensescape 

![screen shot 2015-11-11 at 15 47 29](https://cloud.githubusercontent.com/assets/853051/11106653/92edef20-888c-11e5-9d5d-ec274d082e82.png)

![screen shot 2015-11-11 at 15 42 30](https://cloud.githubusercontent.com/assets/853051/11106652/92ed9458-888c-11e5-9e65-3b730eb2510e.png)

**Comment by bcamper** [comment]
Looks like it may be another multi-polygon encoding issue? We should
compare tiles in GeoJSON and MVT to see how they diverge.

**Comment by rmarianski** [comment]
I was able to verify that it's something in the recent mapbox-vector-tile changes. I'll dig into it.

**Comment by rmarianski** [comment]
This issue gets exposed the moment that multipolygons are encoded. I dug into the encoding, and things look right from what I can tell in the encoded data. I also see the issue regardless of the winding order that gets used. Fwiw I grabbed Varun for a few minutes and we stepped through the decoding in tangram-es, and it seems like what's in the tile is at least what I was expecting.

To me it seems like the decoder is just not detecting the new polygon, and thinks it's an inner ring from the previous geometry. Is the mapbox decoding library in use the latest that supports this behavior?

Can we set aside some time to debug this together? I can set up a dev server to always return back a fake tile that has a single simple MultiPolygon to expose this.

**Comment by bcamper** [comment]
Aha, I think I may have to add a decoding step for this in Tangram! It
looks like the current version of Mapbox's decoder may not support this --
but I have code I can reuse to add that. Will try it and get back to you.

**Comment by bcamper** [comment]
Fixed in this branch, when we are ready to merge: https://github.com/tangrams/tangram/compare/decode-multipolygon

**Comment by nvkelso** [comment]
Nathaniel to make sure Tangram release version has this support now, and to update whatever demos on the site use those.

**Comment by nvkelso** [comment]
Reference: https://github.com/mapzen/mapbox-vector-tile/issues/20

**Comment by nvkelso** [comment]
@nvkelso also to followup with John about communicating this change.

**Comment by nvkelso** [comment]
TilesBRB: We need another PR in the MBVT repo that allows us to configure if the multi polygon is enabled, and disable that by default (but keep the winding switch already accomplished). This should allow to fix the splotchiness in old Tangrams, and still work with new Tangrams.

**Comment by nvkelso** [comment]
@rmarianski anything more to do here?

**Comment by rmarianski** [comment]
This had to do with multipolygon encodings, which should be all good now on all fronts. Closing.
