### ISSUE TITLE
What is in the source code?

### ISSUE THREAD

**Issue by musicformellons** [mapzen/vector-datasource#411]
@nvkelso Could you maybe specify what is in the source code? Is this 'all you need' datawise to get your own server up and running? As until now I was under the impression you would have to download OSM world first and then process it with 'Mapzen tools', but after downloading this:
https://github.com/mapzen/vector-datasource/releases/tag/v0.5.1

I see also data (shapefiles etc), so is this already preprocessed data from OSM & NE...?

Thanks!

**Comment by nvkelso** [comment]
Please see: https://github.com/mapzen/vector-datasource/wiki/Mapzen-Vector-Tile-Service
