### ISSUE TITLE
Missing service roads that are parking_aisles

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#412]
At the San Francisco Zoo and other landuse AOIs with parking lots, we're missing the service roads that are tagged `service=parking_aisles`. These were in v0.4 tiles, maybe this regressed as part of the zoom range refactor?

http://www.openstreetmap.org/#map=18/37.73372/-122.50607

For example, this way is missing: http://www.openstreetmap.org/way/344535940

<img width="1163" alt="screen shot 2015-11-26 at 00 28 53" src="https://cloud.githubusercontent.com/assets/853051/11418465/d2026224-93d4-11e5-8e71-16832708dbf3.png">

**Comment by zerebubuth** [comment]
D'oh, there was a typo. This should be fixed when #413 is rolled out.

**Comment by nvkelso** [comment]
Verified in prod.
