### ISSUE TITLE
Buildings missing

### ISSUE THREAD

**Issue by logeeka** [mapzen/vector-datasource#415]
Hello, when i found this article http://barankahyaoglu.com/dev/OpenStreetMap-in-Unity3D/ i was really happy and start using it in my project immediately. This example saves loaded data to a local file. 
The first time when i started using this code i loaded this url http://vector.mapzen.com/osm/water,earth,buildings,roads,landuse/14/9569/4769.json and get 291 buildings on tile. Later, when some time passed on experimenting, i finally done my script which wants to load same data by same url, but now there is only 81 building. How i can receive full data like it was a couple weeks ago? And why is it happens.

**Comment by zerebubuth** [comment]
Hi,

We've made the filtering of buildings at lower zoom levels (called "detail levels" in the article you linked to) by area and volume more strict to try to make the large or important buildings stand out better. Previous versions of the tiles were only filtering by area, so in an area where all buildings have a large footprint, as the example you gave seems to be, that might not have been noticeable.

The zoom 14 tiles are designed to be a lower level of detail, suitable for a smaller scale map ("zoomed out"), and aren't suitable for getting all of the data. For buildings, we start filtering at zoom 16, so you can get the unfiltered data for all buildings at zoom 17. This does mean downloading more tiles for the equivalent area, but that will be slightly mitigated by each tile being smaller. And it means that you will get all of the building detail.

Hope that helps!

**Comment by logeeka** [comment]
Thank you very much for replying... Its gonna take for me a while to make sure it helped, but i really hope so.
