### ISSUE TITLE
Missing school POIs

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#417]
Sometimes we have landuse AOIs for them but we are dropping the label. Sometimes there is no landuse and it's just a POI in OSM, and we're dropping them. This feels like a regression.

Might be more widespread to other POI types? 

This is a blocker for @IndyHurt next targeted editing post, we might want to consider another v0.5.x patch?

http://tangrams.github.io/cinnabar-style-more-labels/#15/40.8765/-124.0834

<img width="887" alt="screen shot 2015-12-03 at 13 52 39" src="https://cloud.githubusercontent.com/assets/853051/11575383/8b4fae6c-99c5-11e5-88a0-18105946c4f1.png">
<img width="914" alt="screen shot 2015-12-03 at 13 53 11" src="https://cloud.githubusercontent.com/assets/853051/11575384/8b770a52-99c5-11e5-92f7-acf47cd83440.png">

**Comment by zerebubuth** [comment]
Well spotted! Looks like this isn't a regression, as these are mapped in a slightly unusual (but not wrong) way. For example, Arcata High is mapped as [a named node](http://www.openstreetmap.org/node/358817997) imported from GNIS and an enclosing [unnamed polygon](http://www.openstreetmap.org/relation/1423658) added (slightly) later. Our bug was that we weren't using school POIs from points at all, and would only label them as landuse areas. Unfortunately, these landuse polygons are unnamed and don't generate labels.

#419 adds the line required to include schools as POIs from points, after which I get:

## Arcata / Bloomfield

### Zoom 15

Before:
![arcata-bloomfield-z15-before](https://cloud.githubusercontent.com/assets/271360/11592857/f5d6ac3a-9a98-11e5-8597-7bd87e87ec1e.jpg)

After:
![arcata-bloomfield-z15-after](https://cloud.githubusercontent.com/assets/271360/11592863/fcd1563e-9a98-11e5-8290-7e3f5695e059.jpg)

### Zoom 16

Before:
![arcata-bloomfield-z16-before](https://cloud.githubusercontent.com/assets/271360/11592870/034d2eca-9a99-11e5-84ef-3bfb8bd8fce0.jpg)

After:
![arcata-bloomfield-z16-after](https://cloud.githubusercontent.com/assets/271360/11592881/0835011a-9a99-11e5-9cec-88a6eff3b331.jpg)

## Sunnydale^H^H^H^H Brea

### Zoom 15

Before:
![sunnybrea-z16-before](https://cloud.githubusercontent.com/assets/271360/11592885/0e28546e-9a99-11e5-8760-fe82c7052628.jpg)

After:
![sunnybrea-z16-after](https://cloud.githubusercontent.com/assets/271360/11592891/12e681e2-9a99-11e5-85a9-7b0ddd21db13.jpg)

**Comment by zerebubuth** [comment]
I should add: because these are just points, we're missing important stuff for "importance", such as area. We should make a note to include this as a use-case for #348, as it's the same pattern.

**Comment by nvkelso** [comment]
There were to have gone out in v0.5.2 release, but we missed a migration step so they're going out in v0.5.3 instead.

**Comment by nvkelso** [comment]
Verified in prod.
