### ISSUE TITLE
Show generic zoo POIs at zoom 13 (from 15)

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#421]
Right now if a zoo doesn't have an area we default it's zoom to 15, but that's too late. These are important POIs and often don't have area, and they are not very common / landmarks. We should introduce them two zooms earlier than everything else (at z13 instead).

Related: #420

**Comment by zerebubuth** [comment]
After #442, can now see zoos at z13:

![zoo-montana-billings-z13](https://cloud.githubusercontent.com/assets/271360/11751144/87caa312-a02f-11e5-9ac9-bf0965bc2100.jpg)

**Comment by nvkelso** [comment]
I'm not seeing this in zoom 13 tiles:
http://vector.dev.mapzen.com/osm/all/13/1624/2923.topojson?api_key=vector-tiles-HqUVidw

**Comment by nvkelso** [comment]
Still not working for me? #13/45.7347/-108.6190

**Comment by zerebubuth** [comment]
**ARGH** another missing item from the migration. Running again. This time i'll probably target the updates.

**Comment by zerebubuth** [comment]
Migration and re-render complete, I'm seeing that example at 13 now.

**Comment by nvkelso** [comment]
I see these in the raw tiles now! 

Something seems to prevent them from displaying in the stylesheet, I'll dig into that (it's probably an overly aggressive style filter).

**Comment by nvkelso** [comment]
Verified.
