### ISSUE TITLE
aerialways should sort above roads

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#444]
In TileStache transform, the aerialway features all sort below roads, leading to strange looking maps. The max highway sort is 25, so these should probably start at 26 as default, then chair_lift at 27, and (gondola,cable_car) at 28.

```
elif aerialway in ('gondola', 'cable_car'):
        sort_val += 19
    elif aerialway in ('chair_lift'):
        sort_val += 18
    elif aerialway is not None:
        sort_val += 16
```

<img width="848" alt="screen shot 2015-12-13 at 23 39 14" src="https://cloud.githubusercontent.com/assets/853051/11775325/be8be14e-a1f2-11e5-9670-70dd461fc04e.png">

**Comment by nvkelso** [comment]
Related: https://github.com/mapzen/vector-datasource/issues/342

**Comment by nvkelso** [comment]
Related: https://github.com/mapzen/vector-datasource/issues/189

**Comment by nvkelso** [comment]
Might want to consider testing for aerialway value and if so, adding X amount to accommodate these still being above bridges, and still above layer offsets?

**Comment by zerebubuth** [comment]
After mapzen/TileStache#106, I see:

![tahoe-gondola-z16-after](https://cloud.githubusercontent.com/assets/271360/11783742/ad905914-a270-11e5-9337-53446e6b88d6.jpg)

**Comment by nvkelso** [comment]
Working for me.
