### ISSUE TITLE
Include ice cream shops

### ISSUE THREAD

**Issue by bcamper** [mapzen/vector-datasource#447]
https://github.com/mapzen/vector-datasource/search?utf8=%E2%9C%93&q=ice_cream :(

`amenity=ice_cream` ("for places that sell ice cream to be eaten on the spot")
`shop=ice_cream` ("for places selling ice cream to take home")

**Comment by nvkelso** [comment]
Spun in with the other default 15 POIs.

**Comment by nvkelso** [comment]
Working in SF.

**Comment by nvkelso** [comment]
@sensescape We'll need new icons for these.
