### ISSUE TITLE
Include wine (and alcohol) shops

### ISSUE THREAD

**Issue by bcamper** [mapzen/vector-datasource#448]
No wine! https://github.com/mapzen/vector-datasource/search?utf8=%E2%9C%93&q=wine&type=Code

`shop=wine`: https://wiki.openstreetmap.org/wiki/Tag:shop%3Dwine

**Comment by nvkelso** [comment]
Spun in with the other zoom 15 default POIs.

**Comment by nvkelso** [comment]
Wine (NYC): /#20/40.74555/-73.99101
Alcohol (SF): /#19/37.75156/-122.42826
