### ISSUE TITLE
Add Gym / Fitness POIs

### ISSUE THREAD

**Issue by zerebubuth** [mapzen/vector-datasource#465]
There are [many ways](http://wiki.openstreetmap.org/wiki/Gym_/_Fitness_centre) of tagging gyms and fitness-related POIs, although a short-list would be (thanks @IndyHurt!):

* Most commonly-used tags:
  * `leisure=sports_centre` + (`sport=fitness` or `sport=gym`) (about 1,827 uses)
  * `leisure=fitness_centre` (about 1,890 uses)
  * `leisure=fitness_station` (about 2,932 uses)
  * `amenity=gym` (about 1,034 uses - although apparently considered "deprecated" due to different meanings of "gym" in different languages).
* Other tags, less used (all < 10 uses)
  * `amenity=fitness_center`
  * `amenity=fitness_centre`
  * `amenity=fitness`
  * `leisure=fitness_center`
  * `leisure=fitness`
  * `leisure=gym`

We should certainly support all the commonly-used tags, although it's debatable whether it's worth supporting the the less-used ones and it may help drive convergence if we don't support them.

**Comment by zerebubuth** [comment]
After the above two commits, fitness related POIs are now visible (e.g: near #19/37.76508/-122.46659):

Before:

![sunset-gym-sf-z19-before](https://cloud.githubusercontent.com/assets/271360/12118331/c3f0a868-b3bd-11e5-8fbf-4cc442d66e8a.jpg)

After:

![sunset-gym-sf-z19-after](https://cloud.githubusercontent.com/assets/271360/12118334/c709f752-b3bd-11e5-8543-e7f487c9f5c6.jpg)

**Comment by nvkelso** [comment]
I see these appearing in the `pois` layer, good! I'm not sure why I can't get them to render in Eraser Map or Skin & Bones, though. Can you include the scene file snippet you're using, please?

But reviewing this issue with @IndyHurt for her Fitness post, it looks like there's a significant number of buildings that are tagged with these properties that we should also pull in for this issue, too. For instance:

* https://www.openstreetmap.org/way/264528016

**Comment by zerebubuth** [comment]
Ah, for this one, I don't think I changed the scene file. There is already an entry for fitness:

```yaml
                fitness:
                    filter: { kind: [gym, fitness, fitness_center] }
                    draw:   { icons: { sprite: fitness } }
```

Which is why I normalised to `kind: fitness` rather than any other value. I don't think that style file changes should be necessary.

However, it looks like I forgot to [update fastly](https://github.com/mapzen/fastly-deployer/pull/9) to use the new date prefix after the dev release, so it was using the previous release tiles for zoom < 19. As it turns out, we're overzooming zoom 18 in Tangram, so even though the z19 tile includes the fitness POI, it wasn't visible in the map because the map was fetching z18 tiles.

**Comment by nvkelso** [comment]
I see these now :)

Usually when we transform to a "mapzen" kind, we retain the original OSM sources tags as well?

* `leisure=sports_centre` + (`sport=fitness` or `sport=gym`)
* `leisure=fitness_centre`
* `leisure=fitness_station`
* `amenity=gym`

**Comment by nvkelso** [comment]
To clarify, this behaves as expected as-is in dev:

* leisure=sports_centre --> `kind=sports_centre`
* leisure=sports_centre + (sport=fitness or sport=gym) --> `kind=fitness`
* leisure=fitness_centre --> `kind=fitness`
* leisure=fitness_station --> `kind=fitness_station`
* amenity=gym --> `kind=fitness`
