### ISSUE TITLE
Add new transit layer features

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#469]
To support more advanced transit applications, we need to augment the existing set of transit attributes in the `transit` layer.

Add additional line attributes (zoom 11+ only):

* from
* to
* forward
* backward
* alternate

Add nodes for:

* railway=halt (zoom 11)
* railway=tram_stop (zoom 11)
* highway=platform* (zoom 15)
* public_transport=platform* (zoom 15)
* railway=platform* (zoom 15)
* railway=stop* (zoom 11)

`*` The last 4 stop types depend on additional tags such as rail=yes (and should exclude bus=yes, trolleybus=yes).

Stations: 

* public_transport=stop_area (zoom 15)
* site=stop_area (zoom 15)

**Add node attributes:**

This should be in the `transit` layer and the `pois` layer for existing stations there.

* [uic_ref](http://wiki.openstreetmap.org/wiki/Key:uic_ref) - like IATA codes for airports.

References:

* http://wiki.openstreetmap.org/wiki/Relation:route#Public_transport_routes
* http://wiki.openstreetmap.org/wiki/WikiProject_Metro_systems
* http://wiki.openstreetmap.org/wiki/Public_transport

Example applications:

* http://www.openbusmap.org/?zoom=10&lat=37.85457&lon=-121.97473&layers=BT
* http://wiki.openstreetmap.org/wiki/%C3%96pnvkarte
* http://demo.3liz.com/osmtransport/
* http://openptmap.org/
* http://wiki.openstreetmap.org/wiki/Openptmap

**Comment by nvkelso** [comment]
Some or most of the nodes listed above should end up in the `pois` layer (not the `transit` layer).

**Comment by nvkelso** [comment]
In the nodes list above, the following two are already covered in https://github.com/mapzen/vector-datasource/issues/587:

* railway=halt (zoom 11)
* railway=tram_stop (zoom 11)

**Comment by nvkelso** [comment]
Over to Matt to list what's been done, what's outstanding. Then remove assignment.

**Comment by zerebubuth** [comment]
## Add additional line attributes (zoom 11+ only):

* from
* to
* forward
* backward
* alternate

## Add nodes for:

* `highway=platform` (zoom 15)
* `public_transport=platform` (zoom 15)
* `railway=platform` (zoom 15) **These are already included for lines and polygons**
* `railway=stop` (zoom 11)

These types depend on additional tags such as `rail=yes` (and should exclude `bus=yes`, `trolleybus=yes`).

**Note that these are a mixture of polygons, lines and points (11,864 points, 3,657 lines, 3,067 polygons in my North America extract), so all types will need to be queried and extracted.**

## Stations:

Stop areas and sites were taken care of as part of #506 - we should wait and see how that settles out before putting any other features in the tiles.

## Add node attributes:

This should be in the transit layer and the pois layer for existing stations there.

* `uic_ref` - like IATA codes for airports. (Should be simple enough to query from the tags just like the IATA code).

**Comment by zerebubuth** [comment]
Re: additional tags. Hopefully this makes it clearer:

```
# select highway, railway, public_transport, tags->'rail' as rail,
    tags->'bus' as bus, count(*) as num
  from planet_osm_point
  where highway='platform' or public_transport='platform' or
    railway='platform' or railway='stop'
  group by highway, railway, public_transport, rail, bus
  order by highway, railway, public_transport;

   highway   |  railway  | public_transport | rail | bus | num  
-------------+-----------+------------------+------+-----+------
 bus_stop    | platform  |                  |      |     |    1
 bus_stop    |           | platform         |      | yes | 4781
 bus_stop    |           | platform         |      | no  |    1
 bus_stop    |           | platform         |      |     | 3984
 crossing    |           | platform         |      |     |    1
 no          |           | platform         |      | yes |    6
 platform    |           | platform         |      | yes |   16
 platform    |           | platform         |      |     |   29
 platform    |           |                  |      | yes |    3
 platform    |           |                  |      |     |    1
 street_lamp |           | platform         |      |     |    3
             | no        | platform         |      | yes |    1
             | platform  | platform         |      |     |    1
             | platform  |                  |      |     |   19
             | station   | platform         |      |     |    2
             | stop      | station          |      |     |    1
             | stop      | stop             |      |     |   16
             | stop      | stop_position    |      |     |  291
             | stop      | stop_position    | yes  |     |   69
             | stop      |                  |      |     |  217
             | tram_stop | platform         |      |     |    1
             |           | platform         |      | yes |  856
             |           | platform         | yes  |     |    2
             |           | platform         |      |     | 1562
```

Ignoring some of the corner cases, such as the node tagged `highway=bus_stop, bus=no` or the `highway=street_lamp, public_transport=platform`, it looks like there's 4 different categories:

1. `highway IN ('bus_stop', 'platform')` is a bus stop or bus platform.
2. `railway IN ('platform', 'station', 'stop')` is a train stop, train station or train platform.
3. `public_transport=platform` can be either, depending on the `rail=yes` or `bus=yes` tags.
4. `public_transport=platform` without any other `highway`, `railway`, `rail` or `bus` tags seems to be mostly bus platforms from a limited sample I looked at.

**Comment by rmarianski** [comment]
Thanks @zerebubuth! That's really helpful.

@nvkelso about the `public_transport` tags, do we need to have different `min_zoom` values if the `rail` or `bus` tags are set to yes? Maybe if `rail=yes` it's 15 (or 11?), but otherwise it's 17?

**Comment by nvkelso** [comment]
Different `min_zoom` values sounds good. Let's try what you suggest:

* When `public_transport` and `rail=yes`, then `min_zoom=15`, but otherwise it's `17`.

**Comment by nvkelso** [comment]
Last week we talked about _not_ including the following new line attributes, because they are only available on special types of relations we don't plan on adding (they'd additionally duplicate existing features, and aren't generally available says TagInfo, take that wiki):

* from
* to
* forward
* backward
* alternate

The PRs above don't include them, so we're all good.

**Comment by nvkelso** [comment]
The good:

* `uic_ref` QA confirmed, here near Zurich:

<img width="430" alt="screen shot 2016-03-24 at 00 55 23" src="https://cloud.githubusercontent.com/assets/853051/14011373/3800ba9c-f15b-11e5-88df-a6d72d32a207.png">

____

* highway=platform (zoom 15) in POIs layer in #15/38.0965/-122.2468 near SF:

<img width="398" alt="screen shot 2016-03-24 at 01 03 05" src="https://cloud.githubusercontent.com/assets/853051/14011476/36487b4e-f15c-11e5-81d0-c493c111a80e.png">

____

* highway=platform (zoom 15) in TRANSIT layer (lines, polygons) at #19/37.83906/-122.48538 near SF:

<img width="540" alt="screen shot 2016-03-24 at 01 05 37" src="https://cloud.githubusercontent.com/assets/853051/14011515/8be53574-f15c-11e5-94f0-b6d569655d3d.png">

____

* railway=platform (zoom 15) POIs layer at #18/41.28481/-73.93015 some Metro North station north of NYC:

<img width="624" alt="screen shot 2016-03-24 at 01 31 53" src="https://cloud.githubusercontent.com/assets/853051/14012034/414a67ec-f160-11e5-95ce-c036ea627e24.png">

<img width="626" alt="screen shot 2016-03-24 at 01 31 46" src="https://cloud.githubusercontent.com/assets/853051/14012035/41626482-f160-11e5-977e-6a9e7f810732.png">

____

* public_transport=platform (zoom 15) in TRANSIT layer (lines, polygons)

Hmm, we're missing features I expect to see. If it's already in the `public_transport` key, we don't need to enforce `rail=yes`, especially when it's sometimes `light_rail=yes` or the target key,value pair alone. The OSM wiki was wrong, Matt's table shows the data truth. 

  * 18/37.76908/-122.42914
  * http://vector.dev.mapzen.com/osm/all/16/10480/25332.topojson?api_key=vector-tiles-HqUVidw

<img width="492" alt="screen shot 2016-03-24 at 01 15 27" src="https://cloud.githubusercontent.com/assets/853051/14011711/fa9db3a0-f15d-11e5-9a19-478c9d1a5beb.png">

<img width="398" alt="screen shot 2016-03-24 at 01 15 22" src="https://cloud.githubusercontent.com/assets/853051/14011712/fad2b7bc-f15d-11e5-8707-854438f77c60.png">

**Comment by nvkelso** [comment]
**The funky:**

* `public_transport=platform` (zoom 15) in TRANSIT layer (lines, polygons)

Hmm, we're missing features I expect to see. If it's already in the `public_transport` key, we don't need to enforce `rail=yes`, especially when it's sometimes `light_rail=yes` or the target key,value pair alone. _The OSM wiki was wrong, Matt's table shows the data truth._

  * 18/37.76908/-122.42914
  * http://vector.dev.mapzen.com/osm/all/16/10480/25332.topojson?api_key=vector-tiles-HqUVidw

<img width="492" alt="screen shot 2016-03-24 at 01 15 27" src="https://cloud.githubusercontent.com/assets/853051/14011711/fa9db3a0-f15d-11e5-9a19-478c9d1a5beb.png">

<img width="398" alt="screen shot 2016-03-24 at 01 15 22" src="https://cloud.githubusercontent.com/assets/853051/14011712/fad2b7bc-f15d-11e5-8707-854438f77c60.png">

____

* `public_transport=platform` (zoom 15) in POIs layer at #18/37.76963/-122.42990 in SF:

While this is technically working, it creates ambiguity with railway platforms and bus stops (where `public_transport=platform` and `bus=yes`). In the bus=yes combo case, we should set the `kind:bus_stop` (and keep `min_zoom:17`).

  * http://vector.dev.mapzen.com/osm/all/16/10480/25332.topojson?api_key=vector-tiles-HqUVidw

<img width="386" alt="screen shot 2016-03-24 at 01 27 02" src="https://cloud.githubusercontent.com/assets/853051/14011932/9d09c3bc-f15f-11e5-8494-74e7ec0f2b21.png">

https://overpass-turbo.eu/

```
/*
This is an example Overpass query.
Try it out by pressing the Run button above!
You can find more examples with the Load tool.
*/
node
  [public_transport=platform]
  [bus=yes]
  ({{bbox}});
/*added by auto repair*/
(._;>;);
/*end of auto repair*/
out;
```

<img width="476" alt="screen shot 2016-03-24 at 01 38 44" src="https://cloud.githubusercontent.com/assets/853051/14012169/2faca648-f161-11e5-8719-210416a0ca61.png">

**Comment by rmarianski** [comment]
@nvkelso should the changes be:

* `public_transport=platform` && `bus=yes` -> `kind=bus_stop` `min_zoom=17`
* `public_transport=platform` -> `kind=platform` `min_zoom=15`

**Comment by rmarianski** [comment]
I implemented the changes I mentioned in https://github.com/mapzen/vector-datasource/pull/634

**Comment by nvkelso** [comment]
I'm digging it.
