### ISSUE TITLE
Suppress "closed" feature label_position until zoom 17+

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#483]
#18/37.87298/-122.51169

The Best Buy in this mall has closed, so someone noted that by adding " (Closed)" to the name. Kinda makes sense for recently closed stores, but less so for stores that have been closed more than 1 year?

So zoom 15 is too earlier to see these closed features:
![screen shot 2016-01-13 at 09 41 33](https://cloud.githubusercontent.com/assets/853051/12302419/e3cf0acc-b9d9-11e5-92fa-4cd982228a55.png)

Does make some sense to show them at zoom 17+ (here at zoom 18):
![screen shot 2016-01-13 at 09 41 12](https://cloud.githubusercontent.com/assets/853051/12302420/e3dcd1c0-b9d9-11e5-8c91-c2c9ba4962e0.png)

**Comment by nvkelso** [comment]
Related: #291

**Comment by rmarianski** [comment]
I started on the implementation of this in sql, but it seems that the discussion in https://github.com/mapzen/vector-datasource/issues/291 suggests that we might want to do it in a transform due to tag rewriting.

I also noticed some buildings that have the suffix `(closed)` as well, eg http://www.openstreetmap.org/way/395475802.

**Comment by rmarianski** [comment]
@nvkelso sounds like we would want to just update the zooms here too then, and not alter any of the tags. Do we want to do the same for the `buildings` layer?

**Comment by nvkelso** [comment]
> sounds like we would want to just update the zooms here too then, and not alter any of the tags. 

Three options:

1. Don't alter the tags.
2. Do the same as the ` (historical)` features in the other issue where we'd sub out so `kind:closed`.
3. Same as 2, but throttled by time. Do we know when it was marked closed? If it's recently closed, keep the original `kind=*`, but if it's a year+ closed then transform to `kind:closed`?

> Do we want to do the same for the buildings layer?

Yes

**Comment by rmarianski** [comment]
How can we tell if it was closed recently? Is there a way of encoding that in a separate tag? I searched the osm wiki quickly but the closest thing I found was for [opening hours](http://wiki.openstreetmap.org/wiki/Key:opening_hours).

My vote would be for option 2 to be consistent with the `(historical)` features, and do the exact same thing for the `buildings` layer.

**Comment by nvkelso** [comment]
:+1:

**Comment by nvkelso** [comment]
Verified:

<img width="447" alt="screen shot 2016-03-17 at 17 10 56" src="https://cloud.githubusercontent.com/assets/853051/13864951/477ecaec-ec63-11e5-8f5b-0e0393fbd427.png">
