### ISSUE TITLE
Getting wof_neighbourhoods.sql throws 403: Forbidden

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#496]
In the wiki we say to get some SQL dump data, but that's not accessable:

https://github.com/mapzen/vector-datasource/wiki/Mapzen-Vector-Tile-Service#load-whos-on-first-neighbourhood-data

```
$ wget http://s3.amazonaws.com/mapzen-tiles-prod-us-east-20151113/data/wof/wof_neighbourhoods.sql
--2016-01-15 17:45:47--  http://s3.amazonaws.com/mapzen-tiles-prod-us-east-20151113/data/wof/wof_neighbourhoods.sql
Resolving s3.amazonaws.com... 54.231.1.128
Connecting to s3.amazonaws.com|54.231.1.128|:80... connected.
HTTP request sent, awaiting response... 403 Forbidden
2016-01-15 17:45:48 ERROR 403: Forbidden.
```

**Comment by zerebubuth** [comment]
Fixed - it was a casualty of bucket cleanup. It was also horribly out of date, so I've generated a new one (we should [automate this](https://github.com/mapzen/vector-datasource/issues/498)), and found a bug (#497) in the process. The [documentation](https://github.com/mapzen/vector-datasource/wiki/Mapzen-Vector-Tile-Service#user-content-load-whos-on-first-neighbourhood-data) has been updated - it's slightly different now.
