### ISSUE TITLE
Automate dump of WOF neighbourhoods.

### ISSUE THREAD

**Issue by zerebubuth** [mapzen/vector-datasource#498]
At the moment, the [docs](https://github.com/mapzen/vector-datasource/wiki/Mapzen-Vector-Tile-Service#user-content-load-whos-on-first-neighbourhood-data) refer to a static dump of the `wof_neighbourhood` table. This tends to get out of date, so we might want to consider automating a regular (weekly?) dump of that table.

**Comment by rmarianski** [comment]
We tracked this work in a duplicate ticket: #518
