### ISSUE TITLE
Documentation on use

### ISSUE THREAD

**Issue by beechnut** [mapzen/vector-datasource#50]
I've been recommended this project, but there's no instructions for use / basic walkthrough.

It's pretty easy to figure out the higher level-stuff (where you store queries, etc.) but the lack of tutorial has me hesitant to spend the time forking it and figuring out all the pieces.

**Comment by d3netxer** [comment]
@beechnut @bcamper This seems like an interesting project. Could you provide example on how to use these vector tiles in applications such as QGIS, ArcGIS, or in an online web map?

**Comment by d3netxer** [comment]
oh cool, I figured out how to get them into QGIS! from this link: http://gis.stackexchange.com/questions/17035/how-to-display-geojson-from-an-url-in-a-layer

I clicked on add vector layer, Protocol, then used the example buildings uri: http://vector.mapzen.com/osm/buildings/16/19293/24641.json

**Comment by rmarianski** [comment]
@d3netxer Have a look at tangram for how the data can be rendered:

* https://mapzen.com/tangram
* https://github.com/tangrams/tangram
