### ISSUE TITLE
Surprising number of rail features at low zooms

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#501]
I'd expect to see one or two here, but not this many! 
http://vector.mapzen.com/osm/all/7/20/48.topojson

**Comment by nvkelso** [comment]
```
transit: {
type: "GeometryCollection",
geometries: [
{
type: "LineString",
properties: {
kind: "train",
route_name: "Skunk Train",
osm_relation: true,
id: -4710759
},
arcs: [
8
]
},
{
type: "LineString",
properties: {
kind: "railway",
route_name: "California Western Railroad",
osm_relation: true,
id: -4710758
},
arcs: [
9
]
},
{
type: "LineString",
properties: {
operator: "Northwestern Pacific Railroad",
kind: "railway",
route_name: "NWP Mainline",
osm_relation: true,
id: -4520158
},
arcs: [
10
]
},
{
type: "LineString",
properties: {
operator: "Northwestern Pacific Railroad",
kind: "railway",
route_name: "NWP Mainline",
osm_relation: true,
id: -4520158
},
arcs: [
11
]
},
{
type: "LineString",
properties: {
operator: "Northwestern Pacific Railroad",
kind: "railway",
route_name: "NWP Mainline",
osm_relation: true,
id: -4520158
},
arcs: [
12
]
},
{
type: "LineString",
properties: {
operator: "Northwestern Pacific Railroad",
kind: "railway",
route_name: "NWP Mainline",
osm_relation: true,
id: -4520158
},
arcs: [
13
]
},
{
type: "LineString",
properties: {
kind: "railway",
route_name: "West Line",
osm_relation: true,
id: -4508022
},
arcs: [
14
]
},
{
type: "LineString",
properties: {
operator: "Union Pacific Railroad",
kind: "railway",
route_name: "West Valley",
osm_relation: true,
id: -4498171
},
arcs: [
15
]
},
{
type: "LineString",
properties: {
operator: "Union Pacific Railroad",
kind: "railway",
route_name: "West Valley",
osm_relation: true,
id: -4498171
},
arcs: [
16
]
},
{
type: "LineString",
properties: {
kind: "railway",
route_name: "Roseville Subdivision",
osm_relation: true,
id: -4489569
},
arcs: [
17
]
},
{
type: "LineString",
properties: {
kind: "railway",
route_name: "Roseville Subdivision",
osm_relation: true,
id: -4489569
},
arcs: [
18
]
},
{
type: "LineString",
properties: {
operator: "Union Pacific Railroad",
kind: "railway",
route_name: "Valley Subdivision",
osm_relation: true,
id: -4487778
},
arcs: [
19
]
},
{
type: "LineString",
properties: {
operator: "Union Pacific Railroad",
kind: "railway",
route_name: "Valley Subdivision",
osm_relation: true,
id: -4487778
},
arcs: [
20
]
},
{
type: "LineString",
properties: {
operator: "Union Pacific Railroad",
kind: "railway",
route_name: "Valley Subdivision",
osm_relation: true,
id: -4487778
},
arcs: [
21
]
},
{
type: "LineString",
properties: {
operator: "Union Pacific Railroad",
kind: "railway",
route_name: "Valley Subdivision",
osm_relation: true,
id: -4487778
},
arcs: [
22
]
},
{
type: "LineString",
properties: {
kind: "railway",
route_name: "Gateway Subdivision",
osm_relation: true,
id: -4484473
},
arcs: [
23
]
},
{
type: "LineString",
properties: {
kind: "railway",
route_name: "Gateway Subdivision",
osm_relation: true,
id: -4484473
},
arcs: [
24
]
},
{
type: "MultiLineString",
properties: {
kind: "railway",
route_name: "Gateway Subdivision",
osm_relation: true,
id: -4484473
},
arcs: [
[
25
],
[
26
]
]
},
{
type: "LineString",
properties: {
kind: "railway",
route_name: "Canyon Subdivision",
osm_relation: true,
id: -4483009
},
arcs: [
27
]
},
{
type: "LineString",
properties: {
kind: "railway",
route_name: "Canyon Subdivision",
osm_relation: true,
id: -4483009
},
arcs: [
28
]
},
{
type: "LineString",
properties: {
kind: "train",
route_name: "Capitol Corridor",
operator: "Amtrak",
ref: "518-533; 720-751",
id: -2845553,
osm_relation: true
},
arcs: [
29
]
},
{
type: "LineString",
properties: {
kind: "train",
network: "Amtrak",
route_name: "Coast Starlight",
operator: "Amtrak",
ref: "11-14",
id: -2812900,
osm_relation: true
},
arcs: [
30
]
},
{
type: "LineString",
properties: {
kind: "train",
network: "Amtrak",
route_name: "Coast Starlight",
operator: "Amtrak",
ref: "11-14",
id: -2812900,
osm_relation: true
},
arcs: [
31
]
},
{
type: "LineString",
properties: {
kind: "train",
network: "Amtrak",
route_name: "Coast Starlight",
operator: "Amtrak",
ref: "11-14",
id: -2812900,
osm_relation: true
},
arcs: [
32
]
},
{
type: "LineString",
properties: {
kind: "train",
network: "Amtrak",
route_name: "Coast Starlight",
operator: "Amtrak",
ref: "11-14",
id: -2812900,
osm_relation: true
},
arcs: [
33
]
},
{
type: "LineString",
properties: {
kind: "railway",
route_name: "Keddie Wye",
osm_relation: true,
id: -2350199
},
arcs: [
34
]
},
{
type: "LineString",
properties: {
kind: "railway",
route_name: "Keddie Wye",
osm_relation: true,
id: -2350199
},
arcs: [
35
]
},
{
type: "LineString",
properties: {
kind: "railway",
route_name: "Keddie Wye",
osm_relation: true,
id: -2350199
},
arcs: [
36
]
},
{
type: "LineString",
properties: {
kind: "railway",
route_name: "Keddie Wye",
osm_relation: true,
id: -2350199
},
arcs: [
37
]
},
{
type: "LineString",
properties: {
operator: "Union Pacific",
kind: "railway",
id: -1957749,
osm_relation: true
},
arcs: [
38
]
},
{
type: "LineString",
properties: {
operator: "Union Pacific",
kind: "railway",
route_name: "Sacramento Subdivision",
osm_relation: true,
id: -1954847
},
arcs: [
39
]
},
{
type: "LineString",
properties: {
operator: "Union Pacific",
kind: "railway",
route_name: "Sacramento Subdivision",
osm_relation: true,
id: -1954847
},
arcs: [
40
]
},
{
type: "LineString",
properties: {
kind: "train",
network: "Amtrak",
colour: "#005480",
route_name: "California Zephyr",
operator: "Amtrak",
ref: "5-6",
id: -905830,
osm_relation: true
},
arcs: [
41
]
},
{
type: "LineString",
properties: {
kind: "train",
network: "Amtrak",
colour: "#005480",
route_name: "California Zephyr",
operator: "Amtrak",
ref: "5-6",
id: -905830,
osm_relation: true
},
arcs: [
42
]
},
{
type: "LineString",
properties: {
kind: "train",
network: "Amtrak",
colour: "#005480",
route_name: "California Zephyr",
operator: "Amtrak",
ref: "5-6",
id: -905830,
osm_relation: true
},
arcs: [
43
]
},
{
type: "LineString",
properties: {
kind: "train",
network: "Amtrak",
colour: "#005480",
route_name: "California Zephyr",
operator: "Amtrak",
ref: "5-6",
id: -905830,
osm_relation: true
},
arcs: [
44
]
}
]
},
```

**Comment by zerebubuth** [comment]
Do we want to keep all the geometries (i.e: start dropping `ref` and `route_name` and trying to merge), or should we just not be displaying some of them (perhaps dropping based on length?).

**Comment by nvkelso** [comment]
Here's the tile extent in question:

<img width="517" alt="screen shot 2016-03-08 at 14 49 52" src="https://cloud.githubusercontent.com/assets/853051/13619303/23b2c96a-e53d-11e5-862f-aee989a30def.png">

The tile covers not just the Pacific coast, but also the Central Valley of California, which partly explains why there are so many features here.

1. **Duplicate features** (same properties, even), candidates for same merge we started applying to the `roads` layer. Examples:
    * kind	route_name	id
    * train	California Zephyr	-905830
    * train	California Zephyr	-905830
    * train	California Zephyr	-905830
    * train	California Zephyr	-905830
    * train	Coast Starlight	-2812900
    * train	Coast Starlight	-2812900
    * train	Coast Starlight	-2812900
    * train	Coast Starlight	-2812900
2. **Non-transit features.** Examples:
    * railway	California Western Railroad	-4710758 is the generic trail tracks, and is a dup of Skunk Train	-4710759 tourism excursion train that runs on the same tracks. We should show the Skunk Train, but not California Western Railroad in the transit layer.
    * railway	Canyon Subdivision	-4483009
    * railway	Gateway Subdivision	-4484473
    * railway	Keddie Wye	-2350199
    * railway	NWP Mainline	-4520158
    * railway	Roseville Subdivision	-4489569
    * railway	Sacramento Subdivision	-1954847
    * railway	Valley Subdivision	-4487778
    * railway	West Line	-4508022
    * railway	West Valley	-4498171
    * some of these last examples may be used for the California Zephyr and Coast Starlight routes, but they're already in the `roads` layer as rail, don't need to see them here, too.

Should we limit the `transit` layer to not include general `kind:railway` features? Or leverage the route `service` stuff in https://github.com/mapzen/vector-datasource/issues/471 and https://github.com/mapzen/vector-datasource/issues/548 to tune it?

**Comment by nvkelso** [comment]
Only 10 of the 36 features in that tile look transit related:

[tile_contents.csv.zip](https://github.com/mapzen/vector-datasource/files/164145/tile_contents.csv.zip)

**Comment by nvkelso** [comment]
See also:

**Skunk Train:**

* http://www.openstreetmap.org/way/154253632
* http://www.openstreetmap.org/relation/4710759
* http://www.openstreetmap.org/relation/4710758

**Near Davis:**

* http://www.openstreetmap.org/way/207548332
* http://www.openstreetmap.org/relation/905830

**Comment by nvkelso** [comment]
See also:

* http://indyhurt.github.io/te-transit/map/#6/48.349/7.163
* https://github.com/IndyHurt/te-transit/blob/gh-pages/map/transit.yaml#L715

Remove `railway` exclusion from line 715 and you can see where all the bogus railway features are. Removing them cleans up North America the expected level. Don't know enough about Europe to say, but still a bunch there. Was expecting to see more in Japan.

**Comment by nvkelso** [comment]
Verified the tile in question no longer includes the railway features, and merging of features has been accomplished. Tile file size v0.9 dev over v0.8 prod is 7% smaller, too!

Looking visually in Tangram using a hacked TE-Transit scene file:

**after (good no red lines):**
<img width="509" alt="screen shot 2016-03-17 at 16 53 49" src="https://cloud.githubusercontent.com/assets/853051/13864672/d9a6b89c-ec60-11e5-84da-71d3e008e6ce.png">

**before (bad red lines):**
<img width="525" alt="screen shot 2016-03-17 at 16 52 25" src="https://cloud.githubusercontent.com/assets/853051/13864666/c9048abe-ec60-11e5-9b5c-94fd2579109e.png">
