### ISSUE TITLE
Water boundaries can be very slow

### ISSUE THREAD

**Issue by zerebubuth** [mapzen/vector-datasource#502]
For example, a tile like `10/280/364` can spend >15 minutes computing the `exterior_boundaries` post-processing filter. This is generally because these polygons are incredibly complex - many fractal lakes with islands in them - and large.

The "real fix" is probably to split these polygons up using a grid. The exterior boundaries code should erase this seam. However, this would require upstream code changes, or something pretty horrible in a trigger.

An easier fix, but slightly less efficient, might be to clip the water polygons to a buffered tile before performing `exterior_boundaries`. This should, at least, reduce the zoom level at which we have these problems.

**Comment by nvkelso** [comment]
Testing water areas around here /#11/46.3931/-84.1985, I do see these generate slowly but surely.

**Comment by nvkelso** [comment]
Hmm, I am getting some gateway timeout errors, though:

* Tangram v0.5.1: worker 1: tile load error(s) for osm/11/583/741/11: Error: Request error with a status of Gateway Time-out
* Tangram v0.5.1: worker 0: tile load error(s) for osm/11/585/741/11: Error: Request error with a status of Gateway Time-out

**Comment by nvkelso** [comment]
Also:

* Tangram v0.5.1: worker 0: tile load error(s) for osm/17/10498/22491/16: Error: Request error with a status of Service Unavailable
* http://vector.dev.mapzen.com/osm/all/16/10498/22492.topojson Failed to load resource: the server responded with a status of 429 (Too Many Requests)

**Comment by nvkelso** [comment]
If I let the dev server _breath_ a few minutes, everything resolves itself. 

Here's another test area: 

* 12/46.1704/-83.9585

**Comment by nvkelso** [comment]
@zerebubuth Can you look at the logs on dev to see how long those tiles took or if there are any red flags associated with this change? I think this everything above was "expected" and "better than before", but let's do one more cross check, please.

**Comment by zerebubuth** [comment]
I've had a look, but I can't tell.

As far as I can see, we're not logging the time to generate each tile from tileserver. I definitely see the period where the tiles were timing out (nginx logs a "499" code for those when your browser closes the connection), and there are warnings like this from GEOS:

```
2016-02-26_00:51:25.71079 Hole lies outside shell at or near point -9333810.4199999999 5788928.2400000002
2016-02-26_00:51:34.36113 Hole lies outside shell at or near point -9326563.1600000001 5796103.4100000001
2016-02-26_00:52:17.99093 Hole lies outside shell at or near point -9333810.4199999999 5788928.2400000002
2016-02-26_00:52:27.72830 Hole lies outside shell at or near point -9301024.7300000004 5823574.7199999997
2016-02-26_00:52:37.33352 Hole lies outside shell at or near point -9290007.1500000004 5841036.5099999998
2016-02-26_00:52:41.98062 Hole lies outside shell at or near point -9266728.0399999991 5849561.4699999997
2016-02-26_00:52:45.10159 Hole lies outside shell at or near point -9351066.6004457623 5829271.8710068576
2016-02-26_00:52:45.14821 Hole lies outside shell at or near point -9351066.5899999999 5829271.8700000001
2016-02-26_00:52:46.95355 Hole lies outside shell at or near point -9301024.7300000004 5823574.7199999997
```

I've seen similar things before, and I suspect that clipping the water polygons to the 3x tile boundary has introduced some numerical precision issues. As far as I can tell, these are only warnings and haven't resulted in any bad tiles.

From my previous benchmarking, the z11 tiles were "only" 2-5x faster as they genuinely do need to pull in a huge water polygon, against which intersection testing is quite slow.

**Comment by rmarianski** [comment]
We should be able to check the dev kibana instance for slow tiles during offline processing.

**Comment by nvkelso** [comment]
Browsing around zoom 14 near Toronto along the shoreline (14/43.5874/-79.5326), land tiles and water tiles generate at about the same speed now which confirms Matt's numbers :) 

Zooms 12 and 13 there are still slow-ish, but they do generate.

**Comment by zerebubuth** [comment]
Sounds like we still need to do the "grid" part of this as suggested in the original issue description. That's going to be harder - we might need to make some changes to osm2pgsql. I've added mapzen/tile-tasks#57 to track that.

**Comment by nvkelso** [comment]
@zerebubuth Is this still worth taking to prod or do we hold back until https://github.com/mapzen/tile-tasks/issues/57 lands?

**Comment by zerebubuth** [comment]
I think it's worth taking to prod - if only because it doesn't (as far as we can tell) make anything worse, and it's likely to make a good many things better. It's just not the end of the story; sadly there's more work to be done.

**Comment by rmarianski** [comment]
I vote for taking to prod too. It's a nice improvement over what we currently have.
