### ISSUE TITLE
Add sort_keys to zoos & related tourism, attractions

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#504]
Following up from #440, the new landuse features covered there need to have sort_key values defined explicitly on the server.

For example:

*  http://vector.dev.mapzen.com/osm/all/15/5650/13111.topojson

The new `resort` and `theme_park` features lack this key.

**Comment by zerebubuth** [comment]
Should they sort like universities / hospitals / golf courses and have value 4? I suppose some resorts might have golf courses inside... what's the best value for each of these kinds?

**Comment by nvkelso** [comment]
Zoo has 4 now, and seems the tier 1 are same level of importance & stacking. Proposal below (and looks good in Skin & Bones with a quick test), but probably needs editing?

**Tier 1**

_At the "bottom", proposed 4._

* theme_park
* resort
* aquarium
* winery
* maze
* wildlife_park

**Tier 2**

_On top of bottom (higher sort_key value), proposed 5._

* enclosure
* petting_zoo
* aviary
* roller_coaster
* amusement_ride
* summer_toboggan
* trail_riding_station
* water_slide

**Tier 3**

_On top (highest sort_key value), proposed 6._

* attraction
* artwork
* wilderness_hut
* hanami
* animal
* carousel

**Comment by nvkelso** [comment]
Closing in favor of #364.
