### ISSUE TITLE
Calculate POI kind

### ISSUE THREAD

**Issue by zerebubuth** [mapzen/vector-datasource#505]
Currently we use `COALESCE` to calculate POI kinds, but this means we can calculate a kind which is unexpected. For example, something tagged `barrier=fence` and `tourism=attraction` would get `kind: fence` from the `COALESCE` despite `barrier=fence` not being a tag that we select POIs on.

We hit this problem before with landuse, and have an `mz_calculate_landuse_kind` function which only returns whitelisted kinds. We should do the same for POIs (although it'll be a much longer list...).

**Comment by zerebubuth** [comment]
Note for writing the test; the example is http://www.openstreetmap.org/way/134963213

**Comment by nvkelso** [comment]
Close this in favor of #580.
