### ISSUE TITLE
Use points and nodes when exploring transit relations

### ISSUE THREAD

**Issue by zerebubuth** [mapzen/vector-datasource#507]
The existing code joins to the `planet_osm_nodes` table, which by default is where `osm2pgsql` stores "raw" nodes before they've been transformed into points or used to build lines or polygons. However, there's another option, called "flat nodes", where these are stored on a file on disk instead.

In production, we use flat nodes. On my local machine, I don't.

All the queries which join to `planet_osm_nodes` need to join to `planet_osm_point` instead. I think all the relevant information is there, so we shouldn't lose any functionality.

**Comment by zerebubuth** [comment]
With #508, I'm now seeing stuff like this:

## Camden Station, Baltimore

Camden station links via nodes only to the route relations, same as Euston station in London, UK. This has been fixed by using the `planet_osm_point` table instead of `planet_osm_nodes`. (Near 17/39.28238/-76.61943)

Before:

![camden-baltimore-z17](https://cloud.githubusercontent.com/assets/271360/12515140/cc23cfe2-c11e-11e5-8c33-e47cdb4c0f02.jpg)

After:

![camden-baltimore-after-z17](https://cloud.githubusercontent.com/assets/271360/12515144/cf661796-c11e-11e5-9c22-de7ac210d90a.jpg)

**Note**: The weirdness in the routes array seems to be down to there being a '>' character in the route ref / name for [the relation](http://www.openstreetmap.org/relation/1403277).

## 30th Street, Philadelphia

30th Street station is a building, and so doesn't have a node ID. The function has been extended to handle that case too. (Near 17/39.95561/-75.18177)

Before:

![30th-street-z16](https://cloud.githubusercontent.com/assets/271360/12515168/eeb23b3e-c11e-11e5-9444-c410613dd982.jpg)

After:

![30th-street-after-z16](https://cloud.githubusercontent.com/assets/271360/12515172/f3fd9dd6-c11e-11e5-802e-9351ecc954b6.jpg)

**Comment by nvkelso** [comment]
LGTM
