### ISSUE TITLE
Add railway=funicular to roads layer

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#510]
Example:

* http://www.openstreetmap.org/way/393550019

/cc @burritojustice

**Comment by rmarianski** [comment]
In the prs, I just piggybacked on top of the other railway rules for the `kind` and `sort_key` calculations. Here are the properties that came back for the example feature:

```
{
"sort_key": ​380,
"source": "openstreetmap",
"kind": "rail",
"railway": "funicular",
"id": ​393550019
}
```

**Comment by nvkelso** [comment]
WFM

**Comment by nvkelso** [comment]
Verified:

<img width="587" alt="screen shot 2016-03-17 at 16 56 15" src="https://cloud.githubusercontent.com/assets/853051/13864714/3381df2c-ec61-11e5-8b21-540aa18f98f8.png">
