### ISSUE TITLE
Update WOF dump

### ISSUE THREAD

**Issue by zerebubuth** [mapzen/vector-datasource#518]
The WOF dump mentioned [in the install instructions](https://github.com/mapzen/vector-datasource/wiki/Mapzen-Vector-Tile-Service#user-content-load-whos-on-first-neighbourhood-data) hasn't been updated since we updated the schema in #481 (refs mapzen/tilequeue#59).

We could do a one-off update, or script it to dump regularly (weekly) to avoid this problem in future. Is there a (good) way to synchronize this with any releases / schema changes? If not, it's a choice between having to remember to update the dump when we change the schema and occasionally having the automatic dump out of sync with the schema.

**Comment by nvkelso** [comment]
Let's try a weekly chron job to keep the dump up-to-date (from prod). 

One thing to note: users will need to install all data, and then run migrations of master. Which isn't a change, and is documented, but people don't read docs.

**Comment by nvkelso** [comment]
Currently this goes to the following S3 location (no change needed):

* https://s3.amazonaws.com/mapzen-tiles-prod-us-east/data/wof/wof_neighbourhoods.pgdump
