### ISSUE TITLE
TileStache custom transforms

### ISSUE THREAD

**Issue by divya1c** [mapzen/vector-datasource#533]
Hi!

I was looking through queries.yaml file, and I wasn't able to find where the TileStache custom transforms are defined. 

Where can I look through the transform functions ? Which file contains them?

Thanks!

**Comment by divya1c** [comment]
found it in a fork. :)

**Comment by nvkelso** [comment]
Thanks for your feedback. Our longer term plan is to pull those out of TileStache (and it's weird branch) so it's less confusing.
