### ISSUE TITLE
What is simplify_start? 

### ISSUE THREAD

**Issue by divya1c** [mapzen/vector-datasource#534]
Hi!

What does simplify_start mean in queries.yaml?
Also, is there documentation describing what the tags in the yaml file are? 
Thanks! :)

**Comment by nvkelso** [comment]
Most our map data is digitized at zoom 15 resolution, but by the time we zoom out to say zoom 10 that's far too much detail (customer pixel detail and over the wire file size), we we simplify the line geometry starting at some zooms. There is a `simplify_start` as some data, like Natural Earth is pre-simplified, so we don't want to do this step all the time.
