### ISSUE TITLE
How do I have no transforms in my queries.yaml

### ISSUE THREAD

**Issue by divya1c** [mapzen/vector-datasource#537]
Hi! 

I see that there are a lot of transforms in the queries.yaml file. I am trying to use mapzen with my own dataset. Will it be okay if I use no tranforms? 

When I do not include transforms, I get an error. How can I write a queries.yaml without transforms? 

Thanks!

**Comment by nvkelso** [comment]
Can you paste the error you're seeing here, please? The (TileStache related) transforms are mostly related to dealing with OpenStreetMap data so you could in theory operate without them on your own data.

**Comment by divya1c** [comment]
If I do not include transform, I get this error : 
Traceback (most recent call last):
  File "tileserver/__init__.py", line 512, in <module>
    tile_server = create_tileserver_from_config(config)
  File "tileserver/__init__.py", line 444, in create_tileserver_from_config
    queries_config, template_path, reload_templates)
  File "/usr/local/lib/python2.7/site-packages/tilequeue-0.7.1-py2.7.egg/tilequeue/command.py", line 346, in parse_layer_data
    transform_fn_names=layer_config['transform'],
KeyError: 'transform'

**Comment by nvkelso** [comment]
Looks like we're expecting there to be at least 1 transform when the query
file is parsed. Either send a PR with the change or we can look at it
Monday.

**Comment by zerebubuth** [comment]
The PR in mapzen/tilequeue#71 will allow missing `transform` config items when merged. Until then, a work-around is to add an empty list as the value. For example:

```yaml
layers:
  water:
    transform: []
    template: water.jinja2
```
