### ISSUE TITLE
What units is are the area attributes in?

### ISSUE THREAD

**Issue by robhawkes** [mapzen/vector-datasource#538]
I've been playing around with the area attribute in the building layer and I noticed that the values seemed incredibly large for London – far too many buildings over 10000 meters squared(?) than I would expect.

Some clarification questions…

* Are the units in meters squared?
* If so, are these projected metres squared (Spherical Mercator?) or local / real metres squared?

I'm not asking for anything to be changed, I just need clarification so I can build the right logic into ViziCities to interpret the area correctly.

**Comment by zerebubuth** [comment]
Yes, the area is in "square metres", but spherical Mercator projected "metres" rather than real-world physical metres.

**Comment by robhawkes** [comment]
Perfect, thanks for clarifying!

**Comment by nvkelso** [comment]
Updated these docs in my WIP docs branch.

**Comment by robhawkes** [comment]
Nice one, that'll help anyone else with the same question 🙂

**Comment by nvkelso** [comment]
Preview of the docs are here:
https://github.com/mapzen/vector-datasource/blob/nvkelso/update-docs/docs/layers.md
