### ISSUE TITLE
Include subway in the roads layer

### ISSUE THREAD

**Issue by zerebubuth** [mapzen/vector-datasource#549]
Subway lines, e.g: [way 101647480](http://www.openstreetmap.org/way/101647480), are not currently included in the roads layer, as the [railway level function](https://github.com/mapzen/vector-datasource/blob/086ff64a93a6632d8c2d20f559ac24f3c347e95d/data/functions.sql#L304-L319) doesn't include `railway=subway`.

**Comment by nvkelso** [comment]
Aha! That explains some behavior @sensescape and I saw yesterday in London!

**Comment by nvkelso** [comment]
I now see subway features at zoom 15+ in SF and London. :+1:
