### ISSUE TITLE
Do we need default tunnel, default bridge sort_key values? Pistes?

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#558]
Double checking the new roads.cvs spreadsheet, it looks like we're missing rows for bridge and tunnel fallbacks (for when there is not a more specific match). Is that deliberate?

```
layer::int,kind,highway,type,railway,aeroway,service,aerialway,is_bridge,is_tunnel,sort_key
-,*,*,*,*,*,*,*,-,yes,305
-,*,*,*,*,*,*,*,yes,-,405
```

Are there any roads appearing in 355 (the default catch all)? If so, we should probably put pistes and paths below them? 
```
-,piste;path,*,*,*,*,*,*,*,*,354
```

Moving the gondolas up above everything besides layers is good optimization :)

**Comment by rmarianski** [comment]
Whoops, didn't mean to change assignment here, sorry.

**Comment by zerebubuth** [comment]
Please, take it :smile:
