### ISSUE TITLE
[docs] Update docs for v0.8 tiles

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#561]
- New `pois` for Int'l Womens Day: https://github.com/mapzen/vector-datasource/issues/526
    * `childcare`, `clinic`, `dentist`, `doctors`, `kindergarten`, `midwife`, `phone`, `social_facility`, `toilets`
    * But `social_facility` is special, because we end up replacing that with the the value it's set to in https://github.com/mapzen/TileStache/pull/115/files, which results in:
    * Common tags: `ambulatory_care`, `assisted_living`, `food_bank`, `group_home`, `outreach`, `shelter`, `workshop`
    * Less common tags, some of which are almost the same as some of the basic ones listed above: `care_home`, `childrens_centre`, `club`, `dairy_kitchen`, `day_care`, `healthcare`, `nursing_home`, `refugee_camp`, `residential_home`, `soup_kitchen`
    * There are some extremely rare tags from [taginfo](https://taginfo.openstreetmap.org/keys/social_facility#values) that we should skip because they are confusing.
- New `pois` for Big Box stores: https://github.com/mapzen/vector-datasource/pull/544/files
    * `hardware`, `trade`
- New `water` layer labels: https://github.com/mapzen/vector-datasource/issues/400
    * `bay`, `strait`, `fjord`
    * We need to note there is no polygon geometry for these, only label placement points.
- More layers include `sort_key` values (`boundaries`, `buildings`, `earth`, `transit`, and `water`).
    - * `sort_key`: a suggestion for which order to draw features. The value is an integer where smaller numbers suggest that features should be "behind" features with larger numbers.
    - Make this new description consistent with existing `roads` and `landuse` sort_key descriptions.
- Correct kind list in `boundaries` layer to read: 
    * `1st Order Admin Line`, `Admin-0 country`, `Admin-1 boundary`, `Admin-1 region boundary`, `city_wall`, `country`, `county`, `Disputed (please verify)`, `fence`, `Indefinite (please verify)`, `Indeterminant frontier`, `International boundary (verify)`, `Lease limit`, `Line of control (please verify)`, `municipality`, `Overlay limit`, `retaining_wall`, `snow_fence`, `state`
    * Thanks for this catch, Rob!

**Comment by nvkelso** [comment]
@rmarianski @zerebubuth Is there any more documentation needed for this release?

**Comment by rmarianski** [comment]
We're adding `min_zoom` for buildings: https://github.com/mapzen/vector-datasource/pull/562

**Comment by rmarianski** [comment]
There's also some language in the docs about objects appearing at z17. We'll want to update those to say z16.
