### ISSUE TITLE
Add property for generalization level

### ISSUE THREAD

**Issue by tillnagel** [mapzen/vector-datasource#57]
Currently, there is no information in the GeoJSON response if or how simplified the geometries are.

It seems different zoom levels may have the exact same geometries, so with such a field one could check whether to replace the geometry for the same object (having same ID) for a new zoom level, or not.

**Comment by bcamper** [comment]
Sorry for the long delay. I could see this meta info being useful. Perhaps @rmarianski has some thoughts or could look into it?

**Comment by rmarianski** [comment]
Apologies for the late response too. I don't think this is a safe assumption to make, if I understand you correctly. For this approach to work, there would need to exist a zoom level x for a particular layer, such that all geometries at zoom level x + 1 are the same as x. Are you actually seeing that hold true for any zooms?

At the higher zoom levels, I'd imagine that more examples can be found where this can be true for a particular tile, or maybe even viewport. But the geometries do end up being simplified to some degree at all levels, less so the higher the zoom. Here is the relevant python snippet that defines the level of simplification that gets used by the ST_SimplifyPreserveTopology postgis call:

    tolerances = [6378137 * 2 * pi / (2 ** (zoom + 8)) for zoom in range(22)]

**Comment by tillnagel** [comment]
Thanks for the explanation.

I did not want to cache a full tile, but single geometries. At the moment, I am checking whether the geometry with a unique ID has been loaded already for the current zoom level. As the simplification seem to result occasionally in the same geometry (i.e. for different zooms) it would have been nice to have some kind of value for this, so I could use the same object. 

But if I understood correctly you don't actually know this, but use the resulting geometry from PostGIS. So, not possible. Guess, I will stick with my current caching mechanism.

**Comment by rmarianski** [comment]
Ah, I see, gotcha. Yes, we don't actually know if the following zoom level will contain the exact same geometry or not.
