### ISSUE TITLE
"ImportError: No module named dateutil.relativedelta" during pip install

### ISSUE THREAD

**Issue by batje** [mapzen/vector-datasource#574]
* **What did you see?**

During the install when running the command 

`pip install -U -r ../tileserver/requirements.txt`

I see
`
"ImportError: No module named dateutil.relativedelta"`

* **What did you expect to see?**

Success!

* **How did you fix it?

I did 

`pip install python-dateutil`

and reran the setup. That worked. 

Before that I had done

`sudo apt-get install  python-dateutil`

Which did not work. Also when I create a new env from scratch the 'ubuntu' solution didnt work and the setup broke.

**Comment by zerebubuth** [comment]
Hi! Thanks for reporting this!

I'm glad that you found a solution. We've had this problem [too](https://github.com/mapzen/chef-tilequeue/pull/17) so apologies for not documenting that work-around. I've just [reported this](https://github.com/ixc/python-edtf/issues/2) to the upstream project, and hopefully they can make a new version of the EDTF package which won't have this issue.

**Comment by zerebubuth** [comment]
@rmarianski updated `requirements.txt` in 5f203591d7a7ae241026cec065f348c98c4142fb to point to the fixed version from git directly. I think that should fix the problem with requiring `dateutil` before it's installed. Please do let us know if we're wrong and this problem persists!
