### ISSUE TITLE
Finer grained API to query specific 'kind' geometries

### ISSUE THREAD

**Issue by tillnagel** [mapzen/vector-datasource#58]
Currently, one can query `http://vector.mapzen.com/osm/buildings/15/17603/10750.json` but not `http://vector.mapzen.com/osm/buildings:residential/15/17603/10750.json` or such. Would be a great feature.

**Comment by bcamper** [comment]
I agree that a tiled service that flexible would be awesome :)  Unfortunately, I'm not convinced that we can currently support such flexible queries for a dataset as large as the OSM planet. For performance, we're moving more and more towards a caching/CDN approach, so a feature like you request would probably need a fundamentally different architecture. We'll keep it in mind though for future projects, as it has obvious uses.

**Comment by tillnagel** [comment]
Sure, makes sense.

And yes, keep it in mind :)
