### ISSUE TITLE
Fix characters in bundled shapefiles.

### ISSUE THREAD

**Issue by zerebubuth** [mapzen/vector-datasource#582]
* **What did you see?** Our import script assumes shapefiles are in Windows-1252 encoding, but some of the text in some of the shapefiles appears to have re-encoding artefacts. For example, in #577.
* **What did you expect to see?** Our bundled shapefiles should contain only Windows-1252 characters, as close as possible to the original Natural Earth data, without re-encoding artefacts and without overrunning any `VARCHAR()` limits.
* **What map location are you having problems with?** The example from #577 is the [Amundsen–Scott South Pole Station](https://en.wikipedia.org/wiki/Amundsen%E2%80%93Scott_South_Pole_Station) - and perhaps it's that long dash which is causing the problem?

**Comment by nvkelso** [comment]
Natural Earth is mostly UTF-8 now (yes for populated places file, probably for the others). I wonder if these `-merc` files are from the 2.x series which was still Windows-1252? Else there could be some encoding conversion funk in the upstream 3.x series Natural Earth files.

**Comment by zerebubuth** [comment]
Should this be closed in favour of a task to update to Natural Earth 3.x? (With a note to check the encoding was right?)

**Comment by rmarianski** [comment]
:+1:

**Comment by zerebubuth** [comment]
Tracking in #584.
