### ISSUE TITLE
Document reserved sort_key ranges for overlays, underlays

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#586]
Now that the server sends sort_keys for all features, we should document recommended ranges for overlays and underlays.

**Comment by nvkelso** [comment]
This should be 2x checked, and we should think about which of these ranges we want to broadcast publicly and commit to reserving longer term. Just because there are ranges, do we want to reserve in perpetuity 10 slots instead of 1 or 2 in each range? 

* Below everything: 0-9
* Above landuse, below water: 190-199
* Above water, below landuse overlays: 215-219
* Above landuse overlays, below borders: 249
* Above borders, below roads: 290-299
* Above deep minor road layer tunnels, below major road layer tunnels: 321-324
* Above any tunnel, below any surface road, below building footprints: 322-324
* Above any tunnel, below any surface road, above building footprints: 340-344
* Above minor surface roads, below buildings footprints (alt): 362-364
* Above minor surface roads, above buildings footprints (alt): 371-374
* Above major surface roads, below building footprints (alt 2): 383-384
* Above major surface roads, above building footprints (alt 2): 390-394
* Above surface roads, below bridges: 400-403
* Above minor bridges, below major bridges: 412-414
* Above major bridges, below gondolas: 432-434
* Above gondolas and layered bridges: 453-459
* Above everything, below UI elements: 490-499

**Comment by louh** [comment]
These ranges are meant for public use, right?

First comment: these ranges overlap.

- Above deep minor road layer tunnels, below major road layer tunnels: 321-324
- Above any tunnel, below any surface road, below building footprints: 322-324

Second comment: I'm trying to gauge where is my appropriate range to use for my own external data layer, and found the list hard to read. I was also expecting to see a list of reserved "z-indexes" like this:

- Tunnels are 300-320
- Buildings are 325-340

(for example. I don't know if these are the correct numbers)

Extending from that, would it be beneficial to put this in tabular form?

| Data layer | Key range |
| --- | --- |
| **Tunnels** | 300 - 320 |
| (open) | 321 - 339 |
| **Building footprints** | 340 - 345 |

etc.

I feel like this might be easier for me to understand where to insert my own data layer in the hierarchy.

**Comment by nvkelso** [comment]
The goal of the v0.8 `sort_key` changes was to discourage client-side setting of the order values. I'd like to keep this mostly a black box, but offer some basic guidance in the documentation for overlays and underlays. 

Let's add a section in the documentation, calling out the following ranges:

* UNDERLAY: Below everything: 0-9
* UNDERLAY: Above landuse, below water: 190-199
* UNDERLAY: Above borders, below roads: 290-299
* OVERLAY: Above everything, below UI elements: 490-499

**Comment by louh** [comment]
What are UI elements? Labels?

:+1: for this simplification, as it's easy to parse and probably accounts for the majority of uses, but I can't help but :frowning: at the notion of a black box.

**Comment by nvkelso** [comment]
Updated the text to read: "Under UI elements, like routeline and current location gem." See full text in: https://github.com/mapzen/vector-datasource/commit/c786b07b8293f7b315ce9fb1e70795b881151b26.

**Comment by nvkelso** [comment]
@bcamper gave a review in person.
