### ISSUE TITLE
Promote aerialway stations & railway tram_stops and halts

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#587]
* **What did you see?** I only see the station for aerialway and for tram_stops at zoom 15. 
* **What did you expect to see?** I expect to see them earlier at **zoom 13** in tiles. I might only show them with a symbol (no text part of the label) at zoom 13, but including them there shows the shape of the network. Similarly we're missing the calculated `kind_tile_rank` attribute on these.
* **What map location are you having problems with?** London, San Francisco, Berlin
* **Screenshot?** See below.

In functions.sql we're hard coding the zoom of these features to zoom 15:

```
            OR aerialway_val IN ('station')
            OR railway_val IN ('halt', 'tram_stop')
        THEN 15
```

There usually isn't an area associated with these (preventing the area scaling like with railway stations), so try adding them at zoom 13.

More complex, and probably a different ticket? If one of these is a "transfer" station where two lines come intersect (but not in a sequence running parallel), I could see zoom 12. And if it's the terminal station on the line then zoom 11. 

<img width="987" alt="screen shot 2016-03-10 at 11 00 15" src="https://cloud.githubusercontent.com/assets/853051/13680886/7bb2cc00-e6af-11e5-825e-081abdf3bfdf.png">
<img width="699" alt="screen shot 2016-03-10 at 10 59 55" src="https://cloud.githubusercontent.com/assets/853051/13680890/7c1cba7a-e6af-11e5-90d9-ceca906f864d.png">
<img width="1081" alt="screen shot 2016-03-10 at 10 50 11" src="https://cloud.githubusercontent.com/assets/853051/13680888/7bcf0d16-e6af-11e5-8f0e-0d05c097cc9a.png">
<img width="1193" alt="screen shot 2016-03-10 at 10 49 55" src="https://cloud.githubusercontent.com/assets/853051/13680889/7bcf12b6-e6af-11e5-9e1c-b6d0aa7c4b34.png">
<img width="509" alt="screen shot 2016-03-10 at 10 49 39" src="https://cloud.githubusercontent.com/assets/853051/13680887/7bcee6a6-e6af-11e5-9d9d-461c22eae9e9.png">
<img width="717" alt="screen shot 2016-03-10 at 10 49 33" src="https://cloud.githubusercontent.com/assets/853051/13680891/7c20725a-e6af-11e5-923f-b768dfed341c.png">

**Comment by nvkelso** [comment]
Tile sync: Let's just do zoom 13 change now. 

Depending on how these feels in tiles, we can revisit adding a `tile_kind_rank` to them later.

**Comment by nvkelso** [comment]
Overall good, but I see `tram_stop` features marked as `min_zoom:11` in tiles which is too early. **They should be zoom 13 instead.**

In the PR I see this [was zoom 13](https://github.com/mapzen/vector-datasource/pull/618/files#diff-a64c581f59cf68911e4b29efcaff1a14R66), but it was later set to 11 in https://github.com/mapzen/vector-datasource/commit/31d2c0ec282e144b22d4b8ca171384a10e13d0aa. I'm pretty sure 13 is what we want and looks best, but was there a reason for the zoom 11 change?

<img width="323" alt="screen shot 2016-03-24 at 00 27 23" src="https://cloud.githubusercontent.com/assets/853051/14010947/3834c480-f157-11e5-9d8d-1cff41345eba.png">

<img width="988" alt="screen shot 2016-03-24 at 00 23 17" src="https://cloud.githubusercontent.com/assets/853051/14010925/1170d906-f157-11e5-9a4d-39dec9d3819a.png">

**Comment by nvkelso** [comment]
It's probably because `halt` needed to be at zoom 11, but `tram_stop` at zoom 13? Split those two into different lines in the CSV?

**Comment by nvkelso** [comment]
`aerialway=station` is showing up at zoom 13 now, good:

<img width="448" alt="screen shot 2016-03-24 at 00 35 57" src="https://cloud.githubusercontent.com/assets/853051/14011079/b3ba4bba-f158-11e5-9735-de5971ac39b5.png">

**Comment by nvkelso** [comment]
`railway=halt` are showing up near Zug Switzerland now #12/47.1769/8.4923, QA pass:

<img width="395" alt="screen shot 2016-03-24 at 00 46 53" src="https://cloud.githubusercontent.com/assets/853051/14011274/961e3cfe-f15a-11e5-9ab3-c7ea434febe8.png">

**Comment by rmarianski** [comment]
@nvkelso yea, I saw in the description for #469 that `tram_stop`s should be at z11. The [pr above](https://github.com/mapzen/vector-datasource/pull/631) will move them to z13.

**Comment by nvkelso** [comment]
Verified.
