### ISSUE TITLE
Add whitewater putin, egress, and hazard to POIs layer

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#599]
**pois layer:**

- [ ] `whitewater=putin`, zoom 14
- [ ] `whitewater=egress`, zoom 14
- [ ] `whitewater=hazard`, zoom 15
- [ ] `whitewater=put_in;egress`, zoom 14, but with kind of `put_in_egress`
- [ ] `whitewater=rapid`, at zoom 15.

**roads layer:**

- [ ] `whitewater=portage_way` is primarily ways (not nodes). Let's try adding those to the roads layer under the general path High Road moniker, but with whitewater:portage_way details. Show them when paths show.

**See also:**

* http://wiki.openstreetmap.org/wiki/Key:whitewater/Proposal
* https://www.openstreetmap.org/node/2356117215

**Comment by rmarianski** [comment]
There are some other tag combinations, with the most popular being `whitewater=rapid`. Should those be included too? See [taginfo](http://taginfo.openstreetmap.org/keys/whitewater#values).

**Comment by nvkelso** [comment]
I'm down for also adding `rapid`, at zoom 15.

`portage_way` is primarily ways. Let's try adding those to the `roads` layer under the general `path` High Road moniker, but with `whitewater:portage_way` details.

The others seem long tail that we can ignore for now.

I've updated the zoom range recommendation in the primary issue description, too.

**Comment by nvkelso** [comment]
Not seeing example whitewater POIs in Europe :\
