### ISSUE TITLE
Add cliffs, ridges, valleys to earth layer

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#601]
**As a line geom:**

- [cliff](http://wiki.openstreetmap.org/wiki/Tag:natural%3Dcliff)
    * around 213 ,643 features
    * http://taginfo.openstreetmap.org/tags/natural=cliff#overview
    * https://www.openstreetmap.org/way/291687928
* http://taginfo.openstreetmap.org/tags/natural=arete 
    * around 1194 features
    * special type of ridge usually symbolized

**As label positions only (line or point geoms), only when `name=*` is set:**

* http://taginfo.openstreetmap.org/tags/natural=ridge around 34 ,087 features.
* http://taginfo.openstreetmap.org/tags/natural=valley around 3 ,988 features.

**Comment by nvkelso** [comment]
Partial dup with: 

* https://github.com/mapzen/vector-datasource/issues/566

**Comment by nvkelso** [comment]
Ridge and valley only when name is present, as label_placement only.

**Comment by zerebubuth** [comment]
Only ridge / valley features having a `name`. These should be lines, in the landuse layer.

**Comment by nvkelso** [comment]
For tests:

cliff in Yosemite
http://www.openstreetmap.org/way/291684864
13/1374/3166

arete in Yosemite
http://www.openstreetmap.org/way/375271242
13/1379/3164

ridge with name in Santa Cruz Mountains, California
"Castle Rock Ridge"
http://www.openstreetmap.org/way/115675159
13/1317/3182

valley with name in Yosemite
"Lyell Canyon"
http://www.openstreetmap.org/way/407467016
13/1381/3164

**Comment by nvkelso** [comment]
Working!
