### ISSUE TITLE
Calculate kind using YAML for remaining layers

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#646]
We're calculating kind via CSV for POIs, landuse, transit layers. Extend that to the other layers.

**Comment by nvkelso** [comment]
@zerebubuth Is there remaining work here? I think `earth.yaml` and `roads.yaml` are outstanding?

- * boundaries
    - [x] **kind** via `yaml`
    - [x] **sort_key** via `csv`
- * buildings.jinja2
    - [x] **kind** via `yaml`
    - [x] **sort_key** via `csv`
- * earth.jinja2
    - [ ] **kind** via `yaml` – There was a YAML as part of the cliffs PR, but it was [removed](https://github.com/mapzen/vector-datasource/pull/695/commits/3c0d934ae20b459c23a8551c130762c9509f3fb0) since it needed fixes (base > earth) and wasn't wired up to be used. Rescue from there?
    - [x] **sort_key** via `csv`
- * landuse.jinja2
    - [x] **kind** via `yaml`
    - [x] **sort_key** via `csv`
- * places.jinja2
    - [x] **kind** via `yaml`
    - * **sort_key** via `csv`. Not relevant since point features don't need sort_key.
- * pois.jinja2
    - [x] **kind** via `yaml`
    - * **sort_key** via `csv`. Not relevant since point features don't need sort_key.
- * roads.jinja2
    - [ ] **kind** via `yaml`. Outstanding?
    - [x] **sort_key** via `csv`
- * transit.jinja2
    - [x] **kind** via `yaml`
    - [x] **sort_key** via `csv`
- * water.jinja2
    - [x] **kind** via `yaml`
    - [x] **sort_key** via `csv`

**Comment by zerebubuth** [comment]
@nvkelso - hitting a corner case: http://www.openstreetmap.org/way/308154534 is tagged both `highway=service` _and_ `whitewater=portage_way`. Should it be output as a `kind: minor_road, highway: service` or `kind: portage_way`?

**Comment by nvkelso** [comment]
Let’s go with portage_way

**Comment by nvkelso** [comment]
Roads is done, still need `earth`?

**Comment by nvkelso** [comment]
Rescue earth YAML, update `create-sql-functions.py` and `sql.jinja2`.

**Comment by nvkelso** [comment]
Everything seems to be working now :)
