### ISSUE TITLE
Add natural and man_made features to pois layer

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#657]
- [ ] `man_made=beacon` - pois, zoom 15
- [ ] `man_made=cross` - pois, zoom 15
- [ ] `man_made=mineshaft` - pois, zoom 15
- [ ] `man_made=adit` - pois, zoom 16
- [ ] `man_made=water_well` - pois, zoom 17
- [ ] `natural=saddle` - pois, zoom 14, [osm wiki](http://wiki.openstreetmap.org/wiki/Tag:natural%3Dsaddle), see [example](http://www.openstreetmap.org/node/966585438)
- [ ] `natural=dune` - pois, zoom 15
- [ ] `natural=geyser` - pois, zoom 15
- [ ] `natural=sinkhole` - pois, zoom 15
- [ ] `natural=hot_spring` - pois, zoom 16
- [ ] `natural=rock` - pois, zoom 17
- [ ] `natural=stone` - pois, zoom 17

**Comment by nvkelso** [comment]
Word. For @rmglennon, screenshot below!

<img width="1294" alt="screen shot 2016-04-19 at 22 56 28" src="https://cloud.githubusercontent.com/assets/853051/14664695/fbea2020-0681-11e6-982c-ae127a9e1b60.png">

**Comment by rmglennon** [comment]
Cool @nvkelso. Looking good. Nice mix of built and natural.

Interesting (well, at least for geyser nerds!) about how the geyser POIs and labels were chosen. West Trail is unimportant and doesn't need a point. Beehive has a point and should be labeled, but the Plume label is blocking it. Let me know if you need any more geyser analysis to help set priorities. :)

**Comment by nvkelso** [comment]
The more of these type of priority tags you add upstream in OSM, the more we can take advantage of them in tiles :) Right now we're just throwing any old geyser on at the same zoom. Are the distinguished by height of plume, frequency, or?

(Some of the labeling funk is Tangram JS, it'll look better on Tangram ES on device.)

**Comment by rmglennon** [comment]
Yeah, it's all those things. Mostly, which ones are tall, active, and predictable, or also have large features like pools or cones, regardless of whether they erupt. I'll have a look at the OSM data!
