### ISSUE TITLE
Add outdoor related shops

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#674]
The following are features which probably get included as buildings now, but we're not including many nodes (should be added to `pois` layer). 

When it is in building layer, we should prefer the `shop=*` value for the kind (over `building=*`).

**Format is:**
_LINK to osm wiki, EXAMPLE to construct test, recommended MIN_ZOOM value, and COUNT of features._

- [ ] [shop=fishing](http://wiki.openstreetmap.org/wiki/Tag:shop%3Dfishing), [example](https://www.openstreetmap.org/node/3056897308) - pois, zoom 16. Around 660 pois, 150 buildings (make sure `shop` value is used over building value).
- [ ] [shop=hunting](http://wiki.openstreetmap.org/wiki/Tag:shop%3Dhunting), [example](https://www.openstreetmap.org/node/1467729495) - pois, zoom 16. Around 375 pois, 75 buildings (make sure `shop` value is used over building value).
- [ ] [shop=outdoor](http://wiki.openstreetmap.org/wiki/Tag:shop%3Doutdoor), [example](https://www.openstreetmap.org/node/766201791) and [2](https://www.openstreetmap.org/node/418847733) - pois, zoom 16. Around 4400 pois, 1100 buildings (make sure `shop` value is used over building value).
- [ ] [shop=scuba_diving](http://wiki.openstreetmap.org/wiki/Tag:shop%3Dscuba_diving), [example](https://www.openstreetmap.org/node/3931687122) - pois, zoom 17. Around 475 pois, 130 buildings (make sure `shop` value is used over building value).
- [ ] [shop=gas](https://taginfo.openstreetmap.org/tags/shop=gas), [example](https://www.openstreetmap.org/node/2135237099) - pois, zoom 17. Around 430 pois, 150 other (ignore, mostly buildings).
- [ ] [shop=motorcycle](http://wiki.openstreetmap.org/wiki/Tag:shop%3Dmotorcycle), [example](https://www.openstreetmap.org/node/3799971066) - pois, zoom 17. Around 7400 pois, 2100 other (ignore, mostly buildings).

**Comment by zerebubuth** [comment]
When there's a building polygon, we should put that in the `buildings` layer. If it also has POI tags, those get lifted off and added as a centroid in the `pois` layer. That logic should not change - this is just adding some new shop types. **Please do not change the existing POI / building logic.**

**Comment by nvkelso** [comment]
Sounds good, thanks for clarification.

**Comment by nvkelso** [comment]
Looking good.
