### ISSUE TITLE
Add man_made features

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#675]
The following are features which probably get included in `buildings` or `landuse` now, but we're not including many nodes (should be added to `pois` layer). 

When it is in building layer, we should prefer the `man_made=*` value for the kind (over `building=*`).

**Format is:**
_LINK to osm wiki, EXAMPLE to construct test, recommended MIN_ZOOM value, and COUNT of features._

- [ ] [man_made=communications_tower](http://wiki.openstreetmap.org/wiki/Tag:man_made%3Dcommunications_tower), [example](https://www.openstreetmap.org/node/1230069003) - pois, zoom 14. Around 3500 pois, 185 buildings (make sure `man_made` value is used over building value).
- [ ] [man_made=observatory](http://wiki.openstreetmap.org/wiki/Tag:man_made%3Dobservatory), [example](https://www.openstreetmap.org/node/747693102) - pois, zoom 13. Around 200 pois, 180 buildings (make sure `man_made` value is used over building value).
- [ ] [man_made=offshore_platform](http://wiki.openstreetmap.org/wiki/Tag:man_made%3Doffshore_platform), [example](https://www.openstreetmap.org/node/2622856034), and another in [Europe](https://www.openstreetmap.org/node/1042145936) where they are more common - pois, zoom 12. Around 290 pois, 40 [landuse](https://www.openstreetmap.org/way/350328482)/[building](https://www.openstreetmap.org/way/346405529) (man_made=offshore_platform), ignore.
- [ ] [man_made=silo](http://wiki.openstreetmap.org/wiki/Tag:man_made%3Dsilo), [example](https://www.openstreetmap.org/node/1412516737) - pois, zoom 16. Around 6800 pois, 40000 buildings.
- [ ] [man_made=telescope](http://wiki.openstreetmap.org/wiki/Tag:man_made%3Dtelescope), [example](https://www.openstreetmap.org/node/258205070) - pois, zoom 14. Around 700 pois, 400 buildings/landuse (ignore).
- [ ] [man_made=water_tower](http://wiki.openstreetmap.org/wiki/Tag:man_made%3Dwater_tower), [example](https://www.openstreetmap.org/node/1501843094) - pois, zoom 15. Around 40,000 pois, 15,000 buildings (ignore).

**Comment by zerebubuth** [comment]
When there's a building polygon, we should put that in the `buildings` layer. If it also has POI tags, those get lifted off and added as a centroid in the `pois` layer. That logic should not change - this is just adding some new `man_made` types. **Please do not change the existing POI / building logic.**

**Comment by nvkelso** [comment]
Sounds good, thanks for clarification.

**Comment by nvkelso** [comment]
Skip silos, those are almost all buildings, and the shape alone should suffice.

**Comment by nvkelso** [comment]
(Adjusted a few of the zooms after validating with more test data.)

**Comment by nvkelso** [comment]
Looking good.
