### ISSUE TITLE
Add waterfall features

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#677]
These are most often POIs, but sometimes as areas. If it's an area, let's only generate a label_placement.

- [x] [waterway=waterfall](http://wiki.openstreetmap.org/wiki/Tag:waterway%3Dwaterfall), [pois](https://www.openstreetmap.org/node/2389658224), zoom 14 – including the height=* property! Needs to win over `tourism=attraction` as it's often double tagged. Around 15000 pois, 2100 other, including large areas for Niagra Falls. Water [label_placement](https://www.openstreetmap.org/way/56539663) only? https://www.openstreetmap.org/way/56539663

**Comment by nvkelso** [comment]
Into the `water` layer.

**Comment by nvkelso** [comment]
Related: https://github.com/mapzen/vector-datasource/issues/715

**Comment by nvkelso** [comment]
Including these into the `pois` layer until #715 settles out. Added some logic for height and areas.

**Comment by zerebubuth** [comment]
Should be done once #720 lands?

**Comment by nvkelso** [comment]
Looking good!

<img width="1355" alt="screen shot 2016-04-30 at 09 41 04" src="https://cloud.githubusercontent.com/assets/853051/14934646/b8e18af0-0eb7-11e6-904d-cc6ea83b4ab4.png">

<img width="1071" alt="screen shot 2016-04-30 at 09 40 34" src="https://cloud.githubusercontent.com/assets/853051/14934645/b896817c-0eb7-11e6-963a-d3be37bc70ca.png">
