### ISSUE TITLE
Use YAML transform for boundaries

### ISSUE THREAD

**Issue by zerebubuth** [mapzen/vector-datasource#687]
We do a [complex transform](https://github.com/mapzen/TileStache/blob/integration-1/TileStache/Goodies/VecTiles/transform.py#L469-L494) to get the `kind` of an administrative boundary. But it seems that the YAML transform is powerful enough to eliminate this, so it should be rewritten as a YAML transform.

Also:
* `1st_order_admin_lines` -> `state`
* `admin-1_boundary` -> `state`
* `admin-1_region_boundary` -> `macroregion`
* `indeterminant_frontier` -> `indeterminate`
* `international_boundary` -> `country`

**Comment by nvkelso** [comment]
Working for me.
