### ISSUE TITLE
planet_osm_rels triggers hang osm2pgsql

### ISSUE THREAD

**Issue by rmarianski** [mapzen/vector-datasource#711]
The triggers that were added to the `planet_osm_rels` table are causing the osm2pgsql update process to hang. The sequence of events are:

1. osm2pgsql opens the input file, and a connection per-table to the database.
2. it reads the input file sequentially, and:
  - a. updates the middle table for the element (e.g: planet_osm_ways / planet_osm_rels)
  - b. updates the output table, if the element directly results in output (e.g: planet_osm_line)
  - c. leaves a "pending" flag on anything that needs to be revisited later (ways & relations)
3. at the end of input, osm2pgsql closes the per-table connections
4. then it goes over the "pending" flagged stuff

The problem is that a `COPY` command is issued initially, and is followed by a write to the `planet_osm_rels` table whose cause is the trigger. The `COPY` command holds a lock on the table, and `osm2pgsql` waits on the write to the rels table to terminate before proceeding with the `COPY`, but it never does due to the lock.

**Comment by rmarianski** [comment]
The solution that I'm trying out is to track the way ids that we need to update in a separate table, and after the osm2pgsql import completes, update all the way ids in that table.

**Comment by rmarianski** [comment]
One operational complication is that currently the tilequeue intersect process runs in a separate cron job and scans for the expired tiles files. This will no longer work because the expired tile file will get generated now before all the data has been updated. It seems best to run the tilequeue intersect in the same shellscript wrapper that runs osm2pgsql, after the ways have been updated, which will ensure that it would only get run after all the updates complete.

**Comment by rmarianski** [comment]
Another option might be to extend osm2pgsql to allow us to hook into the pending process.

**Comment by nvkelso** [comment]
@zerebubuth Please verify.

**Comment by zerebubuth** [comment]
I checked [way 253871009](http://www.openstreetmap.org/way/253871009), a track which would ordinarily be at zoom 13, but was recently added to [relation 6152226](http://www.openstreetmap.org/relation/6152226/history), which is tagged as a national walking network and should pull the way up to zoom 11. Unfortunately, it's still set to be at zoom 13 - something has gone wrong. The pending IDs table is empty, so it's something more complex than it just hasn't been updated yet.

**Comment by rmarianski** [comment]
Dev didn't have the latest functions installed. I'm running another migration now; let's check again once that's done.

**Comment by rmarianski** [comment]
It's looking good now:

```
gis=> select osm_id, mz_road_level as col, mz_calculate_min_zoom_roads(planet_osm_line.*) as calc, mz_calculate_path_major_route(osm_id) from planet_osm_line where osm_id in (253871009,253871054,378218787);
 osm_id   | col | calc | mz_calculate_path_major_route
-----------+-----+------+-------------------------------
253871009 |  11 |   11 |                            11
253871054 |  11 |   11 |                            11
378218787 |  11 |   11 |                            11
(3 rows)
```
