### ISSUE TITLE
tilejson ?

### ISSUE THREAD

**Issue by yohanboniface** [mapzen/vector-datasource#73]
Hi,

AFAIK, to integrate a non MapBox vectortiles service in MapBox Studio, this service needs to expose a tilejson URL.
I'm working on implementing vector tiles support in [Kosmtik](https://github.com/kosmtik/kosmtik/issues/8), and I'm thinking about supporting tilejson too (and raw TMS too btw), so I wonder if this is something that could be added to this repo somewhere in the future.

Thanks for you lights on this :)

Yohan

**Comment by bcamper** [comment]
Hi -- sorry for not following up on this issue earlier. TileJSON endpoints are now available for each of the supported formats, at:

Mapbox Vector Tiles: http://vector.mapzen.com/osm/tilejson/mapbox.json
GeoJSON tiles: http://vector.mapzen.com/osm/tilejson/geojson.json
TopoJSON tiles: http://vector.mapzen.com/osm/tilejson/topojson.json
OpenScienceMap tiles: http://vector.mapzen.com/osm/tilejson/vtm.json

(Documentation of fields should be added, but these should work.)

Please let us know if you have any questions or issues.

**Comment by aboutaaron** [comment]
Hey,
So I'm using Mapbox Studio on Ubuntu 14.04 and I can't seem to get any of these source URLs to work. Perhaps this is a Mapbox Studio issue, but I'm curious if you guys have any solutions. Here's what I'm seeing adding http://vector.mapzen.com/osm/tilejson/mapbox.json as a remote source: 
![screenshot from 2015-04-30 10 47 55](https://cloud.githubusercontent.com/assets/856628/7418941/822807ca-ef26-11e4-92e8-e442fbf3f6aa.png)

![screenshot from 2015-04-30 10 48 12](https://cloud.githubusercontent.com/assets/856628/7418933/77143642-ef26-11e4-8f16-4e284b1e65c7.png)

**Comment by souperneon** [comment]
@aboutaaron what version of Mapbox Studio are you using? It works for me on Version 0.2.2. On the latest version (Version 0.2.7) it gives me the same error as you.

**Comment by aboutaaron** [comment]
I was using the latest build so perhaps I need to downgrade to 0.27

-----
Aaron Williams
Journalist/Developer
@aboutaaron




On Thu, Apr 30, 2015 at 12:15 PM -0700, "Ekta Daryanani" <notifications@github.com> wrote:












@aboutaaron what version of Mapbox Studio are you using? It works for me on Version 0.2.2. On the latest version (Version 0.2.7) it gives me the same error as you.

**Comment by aboutaaron** [comment]
Err I mean 0.2.2

**Comment by souperneon** [comment]
@aboutaaron try it and see if it works. I believe @rmarianski is going to spend some time to see why that would be happening in the current version.

**Comment by pnorman** [comment]
Could this be related to https://github.com/mapbox/mapbox-studio/pull/1292?

**Comment by zerebubuth** [comment]
Yup, that sounds awfully familiar.

**Comment by rmarianski** [comment]
Yea, a slightly modified version of that pull request fixed the error for me locally.

**Comment by aboutaaron** [comment]
Awesome. I'll build from the patch and check it out. Thanks for the speedy response all!
