### ISSUE TITLE
Return of the son of zombie: mz_is_building: false

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#731]
[tile/12/653/1582](http://vector.dev.mapzen.com/osm/all/12/653/1582.topojson) has `mz_is_building: false` again :(

```
landuse: {
type: "GeometryCollection",
geometries: [
{
type: "Polygon",
properties: {
kind: "national_park",
protect_class: "5",
area: 54302000,
sort_key: 18,
mz_is_building: false,
min_zoom: 4.40875,
source: "openstreetmap.org",
operator: "U.S. National Park Service",
id: -3947724,
osm_relation: true,
name: "Marin Headlands (GGNRA)"
},
arcs: [
[
96
]
]
},
```

**Comment by nvkelso** [comment]
Related: https://github.com/mapzen/vector-datasource/issues/333

**Comment by nvkelso** [comment]
Confirmed this is also a problem on my local dev build against current master branch.

**Comment by nvkelso** [comment]
I still see the offending property on dev tiles :/

**Comment by rmarianski** [comment]
Nice catch! The test was for the `buildings` layer and it's showing up in the `landuse` layer. I'll update the test and dig into why this is still happening.

**Comment by nvkelso** [comment]
Verified.
