### ISSUE TITLE
Many null values for roads in local build of v0.10 dev tiles

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#732]
Similar to the null values in buildings fixed in https://github.com/mapzen/vector-datasource/issues/704. I don't see this on dev, though. Probably a local config error?

**Example:**

* http://localhost:8080/all/12/653/1582.topojson
* [1582.txt](https://github.com/mapzen/vector-datasource/files/225383/1582.txt)

```
roads: {
type: "GeometryCollection",
geometries: [
{
type: "MultiLineString",
properties: {
operator: null,
sport: null,
ascent: null,
id: 24655590,
descent: null,
service: null,
man_made: null,
source: "openstreetmap.org",
state: null,
type: null,
highway: "residential",
description: null,
sort_key: 360,
symbol: null,
leisure: null,
motor_vehicle: null,
distance: null,
kind: "minor_road",
aerialway: null,
roundtrip: null,
landuse_kind: "residential",
colour: null,
route_name: null,
aeroway: null,
ferry: null,
railway: null,
route: null
```

**Comment by zerebubuth** [comment]
I'm not seeing this on my local system, and it sounds like the bug which got fixed in https://github.com/mapzen/tilequeue/pull/84. Could you check that your tilequeue, tileserver and TileStache repos are all up-to-date and you've `python setup.py install`ed the latest versions, please?

If you're still seeing it after updating, could you give the git hash of the installed versions so that I can try to repro?

**Comment by nvkelso** [comment]
@zerebubuth When I run `python setup.py install` for tileserver, I get the following print out. Do versions need to be bumped? Or repointed at master? It looks like it installs a private egg version of these, is it possible to hot link them to my local checkouts instead?

```
Using /Library/Python/2.7/site-packages
Searching for TileStache==1.49.10
Best match: TileStache 1.49.10
TileStache 1.49.10 is already the active version in easy-install.pth

Using /Library/Python/2.7/site-packages
Searching for tilequeue==0.8.0
Best match: tilequeue 0.8.0
tilequeue 0.8.0 is already the active version in easy-install.pth
Installing tilequeue script to /usr/local/bin
```

**Comment by zerebubuth** [comment]
I think if you're running something more recent than prod, then you'll need to have locally checked-out and installed versions of TileStache and tilequeue as well. What's in master (or integration-1 for TileStache) is unreleased (i.e: development in progress) and so can't be installed from PyPI.

The version numbers only get bumped on a release (i.e: prod), so you'll need them checked out locally. The version number by itself doesn't say whether it's a released version or an in-dev version.

**Comment by nvkelso** [comment]
Yep, that did the trick. I'll update the tileserver readme to clarify this point.
