### ISSUE TITLE
Most ski pistes missing from dev

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#743]
**This is a ship block for v0.10 tiles.**

Prod has lots of ski areas, dev has hardly any (as in 1-5% expected coverage):

* http://vector.mapzen.com/osm/all/14/2734/6265.topojson
* http://vector.dev.mapzen.com/osm/all/14/2734/6265.topojson

![missing_pistes](https://cloud.githubusercontent.com/assets/853051/14751043/de149a24-087c-11e6-8166-6ef84cb3f39c.gif)

**Comment by nvkelso** [comment]
This may be related to the path logic, which I'm having a final look thru. Taking this for now.

**Comment by zerebubuth** [comment]
Does this not show up in the tests? If not, we really need more tests!

**Comment by rmarianski** [comment]
Some preliminary tests suggest that this is another instance where the min zoom value doesn't match the calculation from the function. I'll add some tests to catch these and run another migration for this.

**Comment by zerebubuth** [comment]
For what it's worth, I've taken to running this a lot when changing branches. Although it's far from fool-proof, as I keep getting these errors too!

```sql
update planet_osm_point
set mz_poi_min_zoom = null
where coalesce(mz_poi_min_zoom, 999) <> coalesce(mz_calculate_min_zoom_pois(planet_osm_point.*), 999);

update planet_osm_polygon
set mz_poi_min_zoom = null
where coalesce(mz_poi_min_zoom, 999) <> coalesce(mz_calculate_min_zoom_pois(planet_osm_polygon.*), 999);
```

**Comment by rmarianski** [comment]
Alas, I ran `WHERE mz_road_level <> mz_calculate_min_zoom_roads(planet_osm_line.*)`. But I see now that doesn't work for the `null` values and that's why you have the `coalesce`. I'll run the update again.

**Comment by nvkelso** [comment]
Looking good.
