### ISSUE TITLE
Mapbox GL styles produce incorrect maps

### ISSUE THREAD

**Issue by mr** [mapzen/vector-datasource#759]
* **What did you see?**

https://gfycat.com/SecondhandDefiantEwe

* **What did you expect to see?**

https://gfycat.com/PotableSinfulCurlew

* **What map location are you having problems with?**

All of them

I was using basic-v7 from https://github.com/mapbox/mapbox-gl-styles, however I'm pretty sure the results will be the same for all of them. I simply changed the sources from mapbox to local static tiles from tileserver. Is there a way to use styles made with Mapbox studio? I saw this issue: https://github.com/mapzen/mapbox-vector-tile/issues/42#issuecomment-210499733 and thought that might be relevant. Is it?

EDIT: I should also point out that this: https://github.com/mapzen/mapboxgl-vector-tiles/blob/master/index.html works fine.

**Comment by nvkelso** [comment]
Hi @mr, while Mapzen and Mapbox vector tiles share the same MVT file format, the selection of features and the "classes" of those features is different and it's not possible to do a 100% swap between the two without editing your style to accommodate these differences . It is, possible to use Mapzen vector tiles inside of Mapbox studio.

**Comment by zavan** [comment]
Hi @nvkelso, do you know how can I use the mapzen vector tiles in Mapbox Studio?

**Comment by nvkelso** [comment]
You'll need to riff off a style like:

https://github.com/mapzen/mapboxgl-vector-tiles/blob/master/index.html

**Comment by zavan** [comment]
@nvkelso Thank you!
And thanks for the great work.
