### ISSUE TITLE
Disk space needed for .mapbox tiles?

### ISSUE THREAD

**Issue by clintharris** [mapzen/vector-datasource#76]
Do you have a sense for how much space is used by mapbox tiles for the planet?

I'm sure you're not pre-rendering for an area that large, but it would be interesting to know how this compares to raster tiles for the planet (which I believe, in theory, would be 50+ TB).

**Comment by bcamper** [comment]
Both for computation and space, it would probably not be advisable to ever to try render the whole world at a high zoom level. We are pursuing an approach of pre-seeding commonly areas, such as those in our [Metro Extracts](https://mapzen.com/metro-extracts). We're moving to a new production architecture for these tiles soon. When we do, we could post some stats on space for the pre-seed areas, in case it's a useful guideline. cc @rmarianski

**Comment by pnorman** [comment]
Apparently, you can do the entire planet in vector tiles in about 50-100GB (z15ish, which is sufficient for z19 raster tiles).

**Comment by rmarianski** [comment]
I have some numbers for our mapbox vector tiles at zoom level 10:

number of tiles: 1,048,576
total size: 1,173,734,222 bytes
