### ISSUE TITLE
Shouldn't be merging roads at z16

### ISSUE THREAD

**Issue by zerebubuth** [mapzen/vector-datasource#766]
Zoom 16 is the "everything" zoom, so we shouldn't be merging roads at this zoom.

**Comment by nvkelso** [comment]
Hmm, I see just one tunnel feature in that tile, with `id: 89911760`. But no feature for 89912879, but when I view the tile in QGIS, I see that the feature for 89911760 actually includes the geom for 89912879.

<img width="792" alt="screen shot 2016-04-30 at 10 41 28" src="https://cloud.githubusercontent.com/assets/853051/14934920/a075313e-0ec0-11e6-95b8-66302dcf982e.png">

**Comment by nvkelso** [comment]
Oops, tested again ensuring against DEV and while prod does show this problem, it's no longer present on dev.
