### ISSUE TITLE
Line being encoded as multi-line

### ISSUE THREAD

**Issue by zerebubuth** [mapzen/vector-datasource#768]
* **What did you see?**

Tile `16/11473/26126`, feature [325846175](http://www.openstreetmap.org/way/325846175) is encoded as a multilinestring of individual 2-point segments.

* **What did you expect to see?**

A single linestring.

* **Screenshot?**

![image](https://cloud.githubusercontent.com/assets/271360/14901019/3ababcf0-0d8b-11e6-99f1-7bc6004d8cbe.png)

**Comment by zerebubuth** [comment]
I'm **not** seeing this issue on higher zoom roads, e.g: `18/45894/104506`, `17/22947/52253`, but am seeing at at zooms 16 and below, e.g: `16/11473/26126`, `15/5736/13063`.

I'm also not seeing it on my local machine, only on dev.

**Comment by zerebubuth** [comment]
Ah! I **do** see it on my local system at zoom 15, so it must have something to do with #766 and line merging.

**Comment by nvkelso** [comment]
Looking good.

<img width="573" alt="screen shot 2016-04-30 at 10 33 14" src="https://cloud.githubusercontent.com/assets/853051/14934872/f8f5c1b8-0ebe-11e6-8892-1286ce6b58cd.png">
