### ISSUE TITLE
yes/no/maybe bicycle & walking values

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#774]
We're always including yes, no & other values on the new walking, bicycling ways. But should we only include `no` or `yes` values contextually? 

* http://vector.dev.mapzen.com/osm/all/14/2616/6328.topojson?api_key=vector-tiles-HqUVidw

For instance, `motor_vehicle: "no",` is interesting here because tracks are assumed to be `motor_vehicle: "yes",`, but `foot: "yes",` I think is assumed to be `yes`, so why export that?

```
type: "LineString",
properties: {
kind: "path",
bicycle: "yes",
name: "Alta Tr.",
sort_key: 354,
landuse_kind: "national_park",
horse: "yes",
source: "openstreetmap.org",
motor_vehicle: "no",
foot: "yes",
tracktype: "grade2",
id: 239140918,
highway: "track"
},
```

**Comment by nvkelso** [comment]
Another example, `no` isn't useful here for cycleway, we only want to know when it's `yes`.

* https://www.openstreetmap.org/way/22731214

**Comment by nvkelso** [comment]
Related to #453.

**Comment by rmarianski** [comment]
Should we normalize it to `yes` if the value isn't `no`? It can be [other values](http://taginfo.openstreetmap.org/keys/cycleway#values) like "lane". Or do we want to pass it through as long as it isn't `no`?

**Comment by nvkelso** [comment]
Pass thru as long as it's not `no` and not `none`.

(I suspect some of those other values could probably be normalized (there look to be variants), but let's just pass them thru for now.)

**Comment by nvkelso** [comment]
Correctly updated. There's more work to be done to normalize all these, that's tracked in #792.
