### ISSUE TITLE
Unnamed rock is getting label_placement

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#777]
* http://vector.dev.mapzen.com/osm/all/12/687/1583.topojson?api_key=vector-tiles-HqUVidw

```
type: "Point",
properties: {
label_placement: "yes",
kind: "rock",
natural: "rock",
area: 10682,
sort_key: 27,
source: "openstreetmap.org",
min_zoom: 10.5646,
sport: "climbing",
id: 377706598
},
coordinates: [
629,
195
]
```

**Comment by nvkelso** [comment]
<img width="513" alt="screen shot 2016-04-30 at 09 39 08" src="https://cloud.githubusercontent.com/assets/853051/14934633/6cf82946-0eb7-11e6-8481-35918071655c.png">

**Comment by rmarianski** [comment]
It's because we include features for labeling that have a `sport` tag. Do we want to re-evaluate how we handle that?

**Comment by nvkelso** [comment]
Let's update that logic so we also make negative exception for `kind:rock` and `kind:stone`.

**Comment by nvkelso** [comment]
See also: https://github.com/mapzen/TileStache/blob/ac8d0ce189c55ed43007ca27c0d02afcef062daa/TileStache/Goodies/VecTiles/transform.py#L1773-L1779.

**Comment by nvkelso** [comment]
Working for me.
