### ISSUE TITLE
Waterway lines?

### ISSUE THREAD

**Issue by yohanboniface** [mapzen/vector-datasource#81]
Hi :)

I don't see the river lines in the vector tiles (i.e. `waterway=river` or `waterway=canal` for example).

Am I missing it, or is it on purpose, or is it a "to be done" issue? :)

This layer would be needed even in a generic style to display the river labels along the river line (now, having only polygons, we can't).

If it's to be done, I may work on a PR.

Thanks!

Yohan

**Comment by rmarianski** [comment]
Those values should be appearing under the "kind" property on the features. If that's not happening, can you provide an example tile coordinate where it's not doing the right thing?

**Comment by bcamper** [comment]
@rmarianski: @yohanboniface is referring to OSM line geometries (in the `planet_osm_line` table). It does not appear these are included in the `water` layer currently, but I agree with him that they should be added.

@yohanboniface: our approach so far has been to allow different geometry types in the same layer, and group the layers by logical type, so for example, we would add water lines to the `water` layer, intermixed with water polygons, and the client would be responsible for differentiating between the two. We have preferred this consolidation to having separate layers, e.g. `water_polygons` and `water_lines`. While you're here, I am curious if you have any feedback or preference on this approach :)

**Comment by yohanboniface** [comment]
@bcamper you've been faster than me to answer, and your right, I'm referring to line geometries (ex. http://vector.mapzen.com/osm/all/16/33184/22546.json, I would expect to see the object http://www.openstreetmap.org/way/99555154).

About the idea of grouping features semantically, I see it as a good option at this point. Vector tiles are very new, and certainly we are a bit missing distance for this subtleties, at least I am ;)

Thanks both for your answer :)

**Comment by rmarianski** [comment]
Ah, I follow now. Thanks for the clarification guys.

Based on the existing queries, it looks like we should start including these features starting at zoom 9.

What tags should we review for the `kind` value? Looks like at a minimum we'll want to use `waterway`, and after some quick review maybe it makes sense to follow suit with the strategy for polygons, namely `COALESCE("waterway", "natural", "landuse") AS kind`. Some info about it here: http://wiki.openstreetmap.com/wiki/Tag:waterway%3Driver

It looks like we might want to use the same filter criteria as for polygons too, which is `waterway='riverbank' or natural='water' or landuse in ('basin', 'reservoir')`. This would require adding the same kind of index as the polygon table.

Thoughts?

**Comment by yohanboniface** [comment]
I agree about zoom 9 (it could also be 8, but 9 sounds fine).

About the `kind` value, I think only the `waterway` value makes sense for a line geometry, but the COALESCE you are suggestion doesn't hurt.

About the WHERE clause, I don't think your suggestion will work, those tags are used for areas only AFAIK. I would suggest something like `waterway IN ('canal', 'river', 'stream')`.

**Comment by bcamper** [comment]
For reference:

- http://wiki.openstreetmap.org/wiki/Waterways
- http://wiki.openstreetmap.org/wiki/Key:waterway
- http://taginfo.openstreetmap.org/keys/waterway#values

All `waterway` values above 1% would be (in descending popularity): `stream`, `river`, `ditch`, `drain`, `riverbank`, `canal`, `dam`.

We might consider keeping it to the major features for zoom 9, and progressively adding smaller features as zoom goes up, e.g. `ditch` and `drain` look more appropriate for a zoom closer to 14, 15, or 16?

As is the pattern with other layers, we would `COALESCE` all those values into `kind` (along with the polygon water types), and the client would differentiate based on geometry type + `kind`. We'll have to `UNION` the additional query for lines with the existing one for polygons.

@yohanboniface, we would welcome a PR for this if you are interested. Besides changing the query, there is a bit of setup for indexes etc., which @rmarianski could point you to. But, if you aren't able to get to it, no worries, we will take care of it.

**Comment by yohanboniface** [comment]
OK, I'll have a look on that over the week-end :)

**Comment by yohanboniface** [comment]
One question, why are some queries duplicated in the same layer, for example https://github.com/mapzen/vector-datasource/blob/master/tilestache.cfg#L238-L241 ?

**Comment by bcamper** [comment]
@yohanboniface the `queries` field for each layer is a list of queries to use by zoom level. If the same file is repeated, it just means that we want to reuse a past query (mostly to minimize the # of queries, since we don't really need so much detail as to have unique queries per zoom). So in that example, the z0 query is used for zooms 0-3, z4 for zooms 4-5, z6 for zooms 6-8, z9 for zooms 9-10, then there is a unique query for the zooms after that.

**Comment by yohanboniface** [comment]
Oh, right, that makes sense, thanks :)
