### ISSUE TITLE
Issue with load of wof dump

### ISSUE THREAD

**Issue by ijohanne** [mapzen/vector-datasource#853]
Following the [guide](https://github.com/mapzen/vector-datasource/wiki/Mapzen-Vector-Tile-Service) and running the last step 
`wget https://s3.amazonaws.com/mapzen-tiles-prod-us-east/data/wof/wof_neighbourhoods.pgdump
pg_restore --clean --if-exists -d osm -O wof_neighbourhoods.pgdump`

Results in a `wof_neighbourhood` table with no `l10n_name` field. This breaks the tileserver when trying to respond to any type of requests. 

Is there an updated dump, or should this element simply be removed from the guide?

**Comment by nvkelso** [comment]
@ijohanne Thanks for the bug report. We've been refactoring master for our `v1.0` release and looks like we might have missed something related to localized language support that @rmarianski landed recently. 

Can you build off the [v0.10.3](https://github.com/mapzen/vector-datasource/tree/v0.10.3) tag instead and see if that fixes it for you?

**Comment by nvkelso** [comment]
@zerebubuth should we update the wiki guide to ask people to checkout the latest tagged release (instead of master, see [here](https://github.com/mapzen/vector-datasource/wiki/Mapzen-Vector-Tile-Service#download-mapzenvector-datasource)) before proceeding with the rest?

**Comment by zerebubuth** [comment]
@nvkelso I suppose that depends on whether more people are installing this to develop, or just run. If the former, then `master` is definitely better, the latter is probably better pinned to a specific version. Do we need to document the two options separately?

(Also, this is probably going to get version-specific, in which case might it be better to move the docs under the same version control and make them available via the Mapzen documentation site, rather than the Github wiki?)

**Comment by nvkelso** [comment]
Right now it's more of a development guide, but seems like people are using it as a "stand up my own instance" guide, too. I'll add a note for now.

Longer term I think we should make the "stand up my own" folks a package they can easy install, and this doc should move into version control.

**Comment by nvkelso** [comment]
Note added in: https://github.com/mapzen/vector-datasource/wiki/Mapzen-Vector-Tile-Service/eff8ea0973d720c9d7e2456318e4979ffd52b6b0.

**Comment by zerebubuth** [comment]
Added #854 to track packaging for making "stand up my own" easier.

**Comment by nvkelso** [comment]
@ijohanne is this working for you now, can we close the issue?

**Comment by ijohanne** [comment]
@nvkelso Yup, all good - you may close the issue now.

**Comment by nvkelso** [comment]
Glad to hear it!
