### ISSUE TITLE
build from source and error at osm2pgsql

### ISSUE THREAD

**Issue by TGISer** [mapzen/vector-datasource#868]
osm2pgsql -s -C 1024 -S vector-datasource/osm2pgsql.style -k path/to/pbf -d gis -H localhost -W

Using projection SRS 900913 (Spherical Mercator)
Setting up table: planet_osm_point
NOTICE:  table "planet_osm_point" does not exist, skipping
NOTICE:  table "planet_osm_point_tmp" does not exist, skipping
Setting up table: planet_osm_line
NOTICE:  table "planet_osm_line" does not exist, skipping
NOTICE:  table "planet_osm_line_tmp" does not exist, skipping
Setting up table: planet_osm_polygon
NOTICE:  table "planet_osm_polygon" does not exist, skipping
NOTICE:  table "planet_osm_polygon_tmp" does not exist, skipping
Setting up table: planet_osm_roads
NOTICE:  table "planet_osm_roads" does not exist, skipping
NOTICE:  table "planet_osm_roads_tmp" does not exist, skipping
Using built-in tag processing pipeline
Allocating memory for sparse node cache
Node-cache: cache=1024MB, maxblocks=0*131072, allocation method=8192
Mid: pgsql, scale=100 cache=1024
Setting up table: planet_osm_nodes
NOTICE:  table "planet_osm_nodes" does not exist, skipping
Setting up table: planet_osm_ways
NOTICE:  table "planet_osm_ways" does not exist, skipping
Setting up table: planet_osm_rels
NOTICE:  table "planet_osm_rels" does not exist, skipping

Reading in file: path/to/pbf
error while opening file path/to/pbf

can you help me

**Comment by nvkelso** [comment]
@TGISer You need to substitute `path/to/pbf` in the command with the actual path to the PBF file you've downloaded in the earlier step.

* `osm2pgsql` the command to run
* ` -s -C 1024 ` first of the options, these are boilerplate
* `-S vector-datasource/osm2pgsql.style` depending on where you run the command, you'd need to update this, too. (For you this just worked.)
* `-k path/to/pbf` This is the part you need to update.
* `-d gis ` where does it put the output (database in Postgres)
* `-H localhost ` where can it find Postgres
* `-W` more boilerplate
