### ISSUE TITLE
highway=living_street is not included

### ISSUE THREAD

**Issue by mlundblad** [mapzen/vector-datasource#93]
Ways with the tag highway=living_street are not included in vector tiles.
Including it in the function mz_calculate_road_level (maybe at the same level as highway=service) should probably be the solution, if I understand it correctly.

**Comment by rmarianski** [comment]
@bcamper: I'm curious to hear your thoughts here.

Here's a link to the relevant tag info page:
http://taginfo.openstreetmap.org/keys/highway#values

**Comment by bcamper** [comment]
Makes sense, has higher usage than I was aware.

**Comment by rmarianski** [comment]
https://github.com/mapzen/vector-datasource/pull/95

**Comment by yohanboniface** [comment]
Is this change supposed to be rolled in production yet?
Seems to me that `living_streets` are missing from 'tms://vector.mapzen.com/osm/all/{z}/{x}/{y}.mvt' tiles.

**Comment by rmarianski** [comment]
@yohanboniface: yes, this should be in the live service. We are querying for `highway=living_street` (singular), and they would only appear at zoom levels 15 and higher.

Do you have an example feature/tile where it should be appearing but it's not?

**Comment by yohanboniface** [comment]
I have :)
For example, in this tile: http://vector.mapzen.com/osm/roads/18/132803/90193.json I'm expecting to have the "Rue de Cotte" (http://www.openstreetmap.org/way/122682962).

**Comment by rmarianski** [comment]
@yohanboniface: nice catch! It looks like the updated function never got deployed. Sorry about that.

I've corrected the problem, which will fix it for tiles that get updated in the future. I still need to invalidate and update all existing tiles that would have been affected by this. I'll send an update here once that's done.

**Comment by rmarianski** [comment]
This should be updated everywhere now.

**Comment by yohanboniface** [comment]
Confirmed! Thanks :)
