### ISSUE TITLE
railway=preserved is not included in the vector tiles

### ISSUE THREAD

**Issue by mlundblad** [mapzen/vector-datasource#94]
Ways with the tag railway=preserved are not included in the vector tiles.
If I understand how things work, including this tag in the mz_calculate_road_level function to set a minimum zoom level should solve it.

**Comment by bcamper** [comment]
While I know there is an avid historical mapping community in OSM, the aim of these tiles is to provide a simplified, curated view that includes the most common features for everyday mapping. By that criteria, I am not sure that preserved railways qualify. I think those would be more appropriate for a different tile set, possibly focused on historical data. We might be interested in exploring that in the future.
